# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.26)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS remill_settings thirdparty_llvm thirdparty_xed thirdparty_glog thirdparty_gflags remill_arch_aarch32 remill_arch_aarch64 remill_arch_sparc32 remill_arch_sparc64 remill_arch_x86 remill_arch remill_bc remill_os remill_version remill)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target remill_settings
add_library(remill_settings INTERFACE IMPORTED)

set_target_properties(remill_settings PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "NDEBUG;REMILL_INSTALL_SEMANTICS_DIR=\"/home/dungbv/WorkSpace/lifter/third_party/remill_local_install/share/remill/11/semantics\";REMILL_BUILD_SEMANTICS_DIR_X86=\"/home/dungbv/WorkSpace/lifter/third_party/remill-build/lib/Arch/X86/Runtime\";REMILL_BUILD_SEMANTICS_DIR_AARCH32=\"/home/dungbv/WorkSpace/lifter/third_party/remill-build/lib/Arch/AArch32/Runtime\";REMILL_BUILD_SEMANTICS_DIR_AARCH64=\"/home/dungbv/WorkSpace/lifter/third_party/remill-build/lib/Arch/AArch64/Runtime\";REMILL_BUILD_SEMANTICS_DIR_SPARC32=\"/home/dungbv/WorkSpace/lifter/third_party/remill-build/lib/Arch/SPARC32/Runtime\";REMILL_BUILD_SEMANTICS_DIR_SPARC64=\"/home/dungbv/WorkSpace/lifter/third_party/remill-build/lib/Arch/SPARC64/Runtime\""
  INTERFACE_COMPILE_OPTIONS "-Wall;-Wextra;-Wno-unused-parameter;-Wno-c++98-compat;-Wno-unreachable-code-return;-Wno-nested-anon-types;-Wno-extended-offsetof;-Wno-variadic-macros;-Wno-return-type-c-linkage;-Wno-c99-extensions;-Wno-ignored-attributes;-Wno-unused-local-typedef;-Wno-unknown-pragmas;-Wno-unknown-warning-option;-fPIC;-fno-omit-frame-pointer;-fvisibility-inlines-hidden;-fno-asynchronous-unwind-tables;-Wgnu-alignof-expression;-Wno-gnu-anonymous-struct;-Wno-gnu-designator;-Wno-gnu-zero-variadic-macro-arguments;-Wno-gnu-statement-expression;-fno-aligned-allocation;-O2"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "thirdparty_llvm;thirdparty_xed;thirdparty_glog;thirdparty_gflags"
)

# Create imported target thirdparty_llvm
add_library(thirdparty_llvm INTERFACE IMPORTED)

set_target_properties(thirdparty_llvm PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "_GNU_SOURCE -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS"
  INTERFACE_LINK_LIBRARIES "LLVMDemangle;LLVMTableGen;LLVMFuzzMutate;LLVMIRReader;LLVMCodeGen;LLVMSelectionDAG;LLVMAsmPrinter;LLVMMIRParser;LLVMGlobalISel;LLVMBinaryFormat;LLVMBitReader;LLVMBitWriter;LLVMBitstreamReader;LLVMDWARFLinker;LLVMExtensions;LLVMFrontendOpenACC;LLVMFrontendOpenMP;LLVMTransformUtils;LLVMInstrumentation;LLVMAggressiveInstCombine;LLVMInstCombine;LLVMScalarOpts;LLVMipo;LLVMVectorize;LLVMObjCARCOpts;LLVMCoroutines;LLVMCFGuard;LLVMLinker;LLVMAnalysis;LLVMLTO;LLVMMCParser;LLVMMCDisassembler;LLVMMCA;LLVMObject;LLVMObjectYAML;LLVMOption;LLVMRemarks;LLVMDebugInfoDWARF;LLVMDebugInfoGSYM;LLVMDebugInfoMSF;LLVMDebugInfoCodeView;LLVMDebugInfoPDB;LLVMSymbolize;LLVMExecutionEngine;LLVMInterpreter;LLVMJITLink;LLVMMCJIT;LLVMOrcError;LLVMOrcJIT;LLVMRuntimeDyld;LLVMTarget;LLVMAArch64CodeGen;LLVMAArch64AsmParser;LLVMAArch64Disassembler;LLVMAArch64Desc;LLVMAArch64Info;LLVMAArch64Utils;LLVMARMCodeGen;LLVMARMAsmParser;LLVMARMDisassembler;LLVMARMDesc;LLVMARMInfo;LLVMARMUtils;LLVMNVPTXCodeGen;LLVMNVPTXDesc;LLVMNVPTXInfo;LLVMSparcCodeGen;LLVMSparcAsmParser;LLVMSparcDisassembler;LLVMSparcDesc;LLVMSparcInfo;LLVMX86CodeGen;LLVMX86AsmParser;LLVMX86Disassembler;LLVMX86Desc;LLVMX86Info;LLVMAsmParser;LLVMLineEditor;LLVMProfileData;LLVMCoverage;LLVMPasses;LLVMTextAPI;LLVMDlltoolDriver;LLVMLibDriver;LLVMXRay;LLVMWindowsManifest;LLVMMC;LLVMCore;LLVMSupport"
)

# Create imported target thirdparty_xed
add_library(thirdparty_xed INTERFACE IMPORTED)

set_target_properties(thirdparty_xed PROPERTIES
  INTERFACE_LINK_LIBRARIES "XED::XED"
)

# Create imported target thirdparty_glog
add_library(thirdparty_glog INTERFACE IMPORTED)

set_target_properties(thirdparty_glog PROPERTIES
  INTERFACE_LINK_LIBRARIES "glog::glog"
)

# Create imported target thirdparty_gflags
add_library(thirdparty_gflags INTERFACE IMPORTED)

set_target_properties(thirdparty_gflags PROPERTIES
  INTERFACE_LINK_LIBRARIES "gflags"
)

# Create imported target remill_arch_aarch32
add_library(remill_arch_aarch32 STATIC IMPORTED)

set_target_properties(remill_arch_aarch32 PROPERTIES
  INTERFACE_LINK_LIBRARIES "remill_settings"
)

# Create imported target remill_arch_aarch64
add_library(remill_arch_aarch64 STATIC IMPORTED)

set_target_properties(remill_arch_aarch64 PROPERTIES
  INTERFACE_LINK_LIBRARIES "remill_settings"
)

# Create imported target remill_arch_sparc32
add_library(remill_arch_sparc32 STATIC IMPORTED)

set_target_properties(remill_arch_sparc32 PROPERTIES
  INTERFACE_LINK_LIBRARIES "remill_settings"
)

# Create imported target remill_arch_sparc64
add_library(remill_arch_sparc64 STATIC IMPORTED)

set_target_properties(remill_arch_sparc64 PROPERTIES
  INTERFACE_LINK_LIBRARIES "remill_settings"
)

# Create imported target remill_arch_x86
add_library(remill_arch_x86 STATIC IMPORTED)

set_target_properties(remill_arch_x86 PROPERTIES
  INTERFACE_LINK_LIBRARIES "remill_settings"
)

# Create imported target remill_arch
add_library(remill_arch STATIC IMPORTED)

set_target_properties(remill_arch PROPERTIES
  INTERFACE_LINK_LIBRARIES "remill_arch_aarch32;remill_arch_aarch64;remill_arch_sparc32;remill_arch_sparc64;remill_arch_x86;\$<LINK_ONLY:remill_settings>"
)

# Create imported target remill_bc
add_library(remill_bc STATIC IMPORTED)

set_target_properties(remill_bc PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:remill_settings>"
)

# Create imported target remill_os
add_library(remill_os STATIC IMPORTED)

set_target_properties(remill_os PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:remill_settings>"
)

# Create imported target remill_version
add_library(remill_version STATIC IMPORTED)

set_target_properties(remill_version PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:remill_settings>"
)

# Create imported target remill
add_library(remill INTERFACE IMPORTED)

set_target_properties(remill PROPERTIES
  INTERFACE_LINK_LIBRARIES "-Wl,--start-group;thirdparty_llvm;thirdparty_xed;thirdparty_glog;thirdparty_gflags;remill_bc;remill_os;remill_arch;remill_version;-Wl,--end-group"
)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/remillTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
