#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""rev.ng binary recovery pipeline.

This module intentionally keeps three representations separate:

1. runtime root IR (`*.runtime-root.ll`)
   - rev.ng-specific LLVM IR;
   - recompilable through rev.ng's runtime/link pipeline;
   - not expected to link directly with plain Clang.

2. cleanup IR (`*.cleanup.ll`)
   - one LLVM function per recovered binary function;
   - suitable for LLVM analyses;
   - not a standalone program.

3. native-looking IR (`*.native.ll`)
   - generated by Clang from rev.ng's recompilable C archive;
   - valid LLVM IR and compilable to an object file;
   - not assumed to contain `main` or implementations of rev.ng/runtime helpers.

The executable used for semantic differential testing is produced by
`revng artifact recompile-isolated`, because that step links the required
runtime and binary support.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from dataclasses import asdict, dataclass
from pathlib import Path
import shlex
import shutil
import subprocess
import sys
import tarfile
import time
from typing import Optional, Sequence

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "../.."))
REVNG_DIR = os.path.join(PROJECT_ROOT, "dependency", "revng")
CACHE_DIR = os.path.join(PROJECT_ROOT, "result", ".lifting_cache_v4")
CACHE_INDEX = os.path.join(CACHE_DIR, "cache_index.json")
PIPELINE_VERSION = "revng-split-ir-v4"


class Color:
    BLUE = "\033[94m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    RED = "\033[91m"
    GRAY = "\033[90m"
    BOLD = "\033[1m"
    END = "\033[0m"


@dataclass
class RecoveryArtifacts:
    success: bool = False
    binary_path: Optional[str] = None
    output_dir: Optional[str] = None

    # rev.ng runtime-oriented root IR
    runtime_root_zstd: Optional[str] = None
    runtime_root_bc: Optional[str] = None
    runtime_root_ll: Optional[str] = None
    runtime_executable: Optional[str] = None

    # per-function analysis IR
    cleanup_zstd: Optional[str] = None
    cleanup_bc: Optional[str] = None
    cleanup_ll: Optional[str] = None

    # decompiled C and Clang-native-looking IR
    recompilable_archive: Optional[str] = None
    recovered_source_dir: Optional[str] = None
    recovered_c: Optional[str] = None
    native_raw_bc: Optional[str] = None
    native_bc: Optional[str] = None
    native_ll: Optional[str] = None
    native_object: Optional[str] = None

    # rev.ng executable with isolated functions + required runtime
    translated_executable: Optional[str] = None

    model_path: Optional[str] = None
    resume_dir: Optional[str] = None
    manifest_path: Optional[str] = None
    cleanup_function_count: int = 0
    native_function_count: int = 0
    error: Optional[str] = None

    def existing(self, field: str) -> Optional[str]:
        value = getattr(self, field, None)
        return value if value and os.path.exists(value) else None


# ---------------------------------------------------------------------------
# Tool and command helpers
# ---------------------------------------------------------------------------

def _is_executable(path: Optional[str]) -> bool:
    return bool(path and os.path.isfile(path) and os.access(path, os.X_OK))


def _find_revng_bin() -> Optional[str]:
    for candidate in (
        shutil.which("revng"),
        os.path.join(REVNG_DIR, "bin", "revng"),
        os.path.join(REVNG_DIR, "revng"),
    ):
        if _is_executable(candidate):
            return os.path.realpath(candidate)
    return None


def _candidate_tool_dirs(revng_bin: Optional[str]) -> list[str]:
    result: list[str] = []
    if revng_bin:
        base = os.path.dirname(os.path.realpath(revng_bin))
        result.extend(
            [
                base,
                os.path.join(base, "bin"),
                os.path.abspath(os.path.join(base, "..", "bin")),
                os.path.join(base, "root", "lib64", "llvm", "llvm", "bin"),
                os.path.abspath(
                    os.path.join(base, "..", "root", "lib64", "llvm", "llvm", "bin")
                ),
            ]
        )
    result.extend(
        [
            os.path.join(REVNG_DIR, "bin"),
            os.path.join(REVNG_DIR, "root", "lib64", "llvm", "llvm", "bin"),
        ]
    )
    seen: set[str] = set()
    unique: list[str] = []
    for directory in result:
        directory = os.path.abspath(directory)
        if directory not in seen:
            seen.add(directory)
            unique.append(directory)
    return unique


def _find_tool(revng_bin: Optional[str], names: Sequence[str]) -> Optional[str]:
    for directory in _candidate_tool_dirs(revng_bin):
        for name in names:
            candidate = os.path.join(directory, name)
            if _is_executable(candidate):
                return candidate
    for name in names:
        candidate = shutil.which(name)
        if candidate:
            return candidate
    return None


def _tool_version(tool: Optional[str]) -> str:
    if not tool:
        return "missing"
    try:
        result = subprocess.run(
            [tool, "--version"],
            capture_output=True,
            text=True,
            check=False,
            timeout=15,
        )
        text = (result.stdout or result.stderr or "unknown").strip()
        return text.splitlines()[0] if text else "unknown"
    except Exception:
        return "unknown"


def _format_cmd(cmd: Sequence[str]) -> str:
    return " ".join(shlex.quote(str(part)) for part in cmd)


def run_command(
    cmd: Sequence[str],
    label: str,
    *,
    cwd: Optional[str] = None,
    timeout: Optional[float] = None,
) -> bool:
    print(f"\n{Color.BLUE}[*] {label}{Color.END}")
    print(f"{Color.GRAY}    $ {_format_cmd(cmd)}{Color.END}")
    try:
        result = subprocess.run(
            list(cmd),
            cwd=cwd,
            capture_output=True,
            text=True,
            check=False,
            timeout=timeout,
        )
    except FileNotFoundError as exc:
        print(f"{Color.RED}[✗] Không tìm thấy lệnh: {exc}{Color.END}")
        return False
    except subprocess.TimeoutExpired:
        print(f"{Color.RED}[✗] Lệnh vượt quá timeout.{Color.END}")
        return False
    except Exception as exc:
        print(f"{Color.RED}[✗] Lỗi thực thi: {exc}{Color.END}")
        return False

    if result.returncode == 0:
        print(f"{Color.GREEN}[✓] Hoàn tất.{Color.END}")
        if result.stdout.strip():
            print(f"{Color.GRAY}{result.stdout.strip()[:2000]}{Color.END}")
        return True

    print(f"{Color.RED}[✗] Thất bại (code {result.returncode}).{Color.END}")
    if result.stdout.strip():
        print(f"{Color.GRAY}stdout: {result.stdout.strip()[:3000]}{Color.END}")
    if result.stderr.strip():
        print(f"{Color.RED}stderr: {result.stderr.strip()[:5000]}{Color.END}")
    return False


def _decompress_zstd(src: str, dst: str) -> bool:
    try:
        import zstandard as zstd  # type: ignore

        with open(src, "rb") as source, open(dst, "wb") as target:
            zstd.ZstdDecompressor().copy_stream(source, target)
        return True
    except ImportError:
        pass
    except Exception as exc:
        print(f"{Color.YELLOW}[!] Python zstandard thất bại: {exc}{Color.END}")

    zstd_bin = shutil.which("zstd")
    if not zstd_bin:
        return False
    return run_command(
        [zstd_bin, "-d", "--force", src, "-o", dst],
        "Giải nén Zstandard",
    )


def _safe_extract_tar(archive_path: str, destination: str) -> None:
    root = Path(destination).resolve()
    with tarfile.open(archive_path, "r:*") as archive:
        for member in archive.getmembers():
            target = (root / member.name).resolve()
            if target != root and root not in target.parents:
                raise RuntimeError(f"Unsafe archive member: {member.name}")
        archive.extractall(destination)


def _emit_llvm_text(
    bitcode: str,
    output_ll: str,
    llvm_dis: Optional[str],
    clang: str,
    label: str,
) -> bool:
    if llvm_dis:
        return run_command([llvm_dis, bitcode, "-o", output_ll], label)
    return run_command(
        [clang, "-S", "-emit-llvm", bitcode, "-o", output_ll],
        label + " (clang fallback)",
    )


def _count_llvm_definitions(ll_path: str) -> int:
    count = 0
    with open(ll_path, "r", encoding="utf-8", errors="replace") as stream:
        for line in stream:
            if line.lstrip().startswith("define "):
                count += 1
    return count


def _make_executable(path: str) -> bool:
    if not os.path.isfile(path):
        return False
    os.chmod(path, os.stat(path).st_mode | 0o111)
    return os.access(path, os.X_OK)


# ---------------------------------------------------------------------------
# Cache
# ---------------------------------------------------------------------------

def compute_binary_hash(binary_path: str) -> str:
    digest = hashlib.sha256()
    with open(binary_path, "rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _load_cache_index() -> dict:
    try:
        with open(CACHE_INDEX, "r", encoding="utf-8") as stream:
            data = json.load(stream)
            return data if isinstance(data, dict) else {}
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return {}


def _save_cache_index(index: dict) -> None:
    os.makedirs(CACHE_DIR, exist_ok=True)
    temp = CACHE_INDEX + ".tmp"
    with open(temp, "w", encoding="utf-8") as stream:
        json.dump(index, stream, indent=2, ensure_ascii=False)
    os.replace(temp, CACHE_INDEX)


def _cache_key(binary_hash: str, revng_version: str, clang_version: str) -> str:
    raw = f"{binary_hash}|{PIPELINE_VERSION}|{revng_version}|{clang_version}"
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _artifacts_from_dict(data: dict) -> RecoveryArtifacts:
    allowed = RecoveryArtifacts.__dataclass_fields__.keys()
    return RecoveryArtifacts(**{key: value for key, value in data.items() if key in allowed})


def _cache_artifacts_valid(artifacts: RecoveryArtifacts) -> bool:
    required = [
        artifacts.runtime_root_bc,
        artifacts.runtime_root_ll,
        artifacts.runtime_executable,
        artifacts.cleanup_bc,
        artifacts.cleanup_ll,
        artifacts.native_bc,
        artifacts.native_ll,
        artifacts.native_object,
        artifacts.translated_executable,
        artifacts.manifest_path,
    ]
    return artifacts.success and all(path and os.path.exists(path) for path in required)


def list_cache_entries() -> None:
    index = _load_cache_index()
    if not index:
        print(f"{Color.YELLOW}[!] Cache trống.{Color.END}")
        return
    for key, value in index.items():
        print(f"{Color.GRAY}{key}{Color.END}")
        print(f"  binary: {value.get('binary_path')}")
        print(f"  runtime_root_ll: {value.get('runtime_root_ll')}")
        print(f"  native_ll: {value.get('native_ll')}")
        print(f"  translated_executable: {value.get('translated_executable')}")
        print(f"  timestamp: {value.get('timestamp')}")


def clear_cache() -> None:
    if os.path.isdir(CACHE_DIR):
        shutil.rmtree(CACHE_DIR)
    print(f"{Color.GREEN}[✓] Đã xóa cache.{Color.END}")


# ---------------------------------------------------------------------------
# Manifest
# ---------------------------------------------------------------------------

def _write_manifest(artifacts: RecoveryArtifacts) -> None:
    if not artifacts.manifest_path:
        return
    manifest = {
        "pipeline_version": PIPELINE_VERSION,
        "binary": artifacts.binary_path,
        "representations": {
            "runtime_root_ir": {
                "bitcode": artifacts.runtime_root_bc,
                "llvm_ir": artifacts.runtime_root_ll,
                "purpose": "rev.ng runtime-oriented IR",
                "standalone_clang_linkable": False,
                "recompile_route": "revng artifact recompile",
                "executable": artifacts.runtime_executable,
            },
            "cleanup_ir": {
                "bitcode": artifacts.cleanup_bc,
                "llvm_ir": artifacts.cleanup_ll,
                "purpose": "per-function LLVM analysis IR",
                "standalone_program": False,
                "function_count": artifacts.cleanup_function_count,
            },
            "native_looking_ir": {
                "bitcode": artifacts.native_bc,
                "llvm_ir": artifacts.native_ll,
                "object": artifacts.native_object,
                "purpose": "Clang IR generated from rev.ng decompiled C",
                "object_compilable": True,
                "standalone_clang_linkable": False,
                "reason": (
                    "The module may not define main and may reference rev.ng/runtime "
                    "helpers or dynamically resolved binary functions."
                ),
                "function_count": artifacts.native_function_count,
            },
        },
        "semantic_reference": {
            "executable": artifacts.translated_executable,
            "producer": "revng artifact recompile-isolated",
            "scope": (
                "Differential testing validates the rev.ng runtime translation. "
                "It does not by itself prove that native-looking IR is a standalone program."
            ),
        },
    }
    with open(artifacts.manifest_path, "w", encoding="utf-8") as stream:
        json.dump(manifest, stream, indent=2, ensure_ascii=False)


# ---------------------------------------------------------------------------
# Core recovery pipeline
# ---------------------------------------------------------------------------

def recover_binary(
    binary_path: str,
    output_dir: Optional[str] = None,
    *,
    use_cache: bool = True,
    force_relift: bool = False,
    optimize_native_ir: bool = True,
    # Kept only for old callers. Standalone native executable is not promised.
    require_native_executable: bool = False,
) -> RecoveryArtifacts:
    binary_path = os.path.abspath(binary_path)
    if not os.path.isfile(binary_path):
        return RecoveryArtifacts(error=f"Binary không tồn tại: {binary_path}")

    if require_native_executable:
        print(
            f"{Color.YELLOW}[!] --require-native-executable không còn được hỗ trợ: "
            "native-looking IR chỉ được xác nhận compile thành object. "
            "Executable semantic dùng recompile-isolated của rev.ng."
            f"{Color.END}"
        )

    if output_dir is None:
        parent = os.path.basename(os.path.dirname(binary_path)) or "binary"
        output_dir = os.path.join(PROJECT_ROOT, "result", parent)
    output_dir = os.path.abspath(output_dir)
    os.makedirs(output_dir, exist_ok=True)

    basename = os.path.splitext(os.path.basename(binary_path))[0]
    revng = _find_revng_bin()
    if not revng:
        return RecoveryArtifacts(error="Không tìm thấy revng trong PATH hoặc dependency/revng")

    clang = _find_tool(revng, ["clang", "clang-21", "clang-20", "clang-19", "clang-18"])
    llvm_dis = _find_tool(
        revng,
        ["llvm-dis", "llvm-dis-21", "llvm-dis-20", "llvm-dis-19", "llvm-dis-18"],
    )
    opt = _find_tool(revng, ["opt", "opt-21", "opt-20", "opt-19", "opt-18"])
    if not clang:
        return RecoveryArtifacts(error="Thiếu clang tương thích")

    revng_version = _tool_version(revng)
    clang_version = _tool_version(clang)
    cache_key = _cache_key(compute_binary_hash(binary_path), revng_version, clang_version)

    if use_cache and not force_relift:
        cached_data = _load_cache_index().get(cache_key)
        if isinstance(cached_data, dict):
            cached = _artifacts_from_dict(cached_data)
            if _cache_artifacts_valid(cached):
                print(f"{Color.GREEN}[✓] Cache HIT: {binary_path}{Color.END}")
                return cached

    artifacts = RecoveryArtifacts(
        binary_path=binary_path,
        output_dir=output_dir,
        runtime_root_zstd=os.path.join(output_dir, f"{basename}.runtime-root.bc.zstd"),
        runtime_root_bc=os.path.join(output_dir, f"{basename}.runtime-root.bc"),
        runtime_root_ll=os.path.join(output_dir, f"{basename}.runtime-root.ll"),
        runtime_executable=os.path.join(output_dir, f"{basename}.runtime.translated"),
        cleanup_zstd=os.path.join(output_dir, f"{basename}.cleanup.bc.zstd"),
        cleanup_bc=os.path.join(output_dir, f"{basename}.cleanup.bc"),
        cleanup_ll=os.path.join(output_dir, f"{basename}.cleanup.ll"),
        recompilable_archive=os.path.join(output_dir, f"{basename}.recompilable.tar.gz"),
        recovered_source_dir=os.path.join(output_dir, f"{basename}.recovered-source"),
        native_raw_bc=os.path.join(output_dir, f"{basename}.native.raw.bc"),
        native_bc=os.path.join(output_dir, f"{basename}.native.bc"),
        native_ll=os.path.join(output_dir, f"{basename}.native.ll"),
        native_object=os.path.join(output_dir, f"{basename}.native.o"),
        translated_executable=os.path.join(output_dir, f"{basename}.translated"),
        model_path=os.path.join(output_dir, f"{basename}.model.yml"),
        resume_dir=os.path.join(output_dir, f"{basename}.revng-project"),
        manifest_path=os.path.join(output_dir, f"{basename}.artifacts.json"),
    )

    print(f"{Color.BLUE}[*] Binary: {binary_path}{Color.END}")
    print(f"{Color.BLUE}[*] revng: {revng}{Color.END}")
    print(f"{Color.BLUE}[*] clang: {clang}{Color.END}")
    print(f"{Color.BLUE}[*] Output: {output_dir}{Color.END}")

    # 1. Runtime-oriented root IR. This is the LLVM representation tied to the
    #    rev.ng recompile pipeline, not a native Clang application module.
    lift_cmd = [
        revng,
        "artifact",
        "--resume",
        artifacts.resume_dir,
        "--analyze",
        "--save-model",
        artifacts.model_path,
        "lift",
        binary_path,
        "-o",
        artifacts.runtime_root_zstd,
    ]
    if not run_command(lift_cmd, "1/11 binary → rev.ng runtime root IR"):
        artifacts.error = "revng lift thất bại"
        return artifacts
    if not _decompress_zstd(artifacts.runtime_root_zstd, artifacts.runtime_root_bc):
        artifacts.error = "Không giải nén được runtime root IR"
        return artifacts
    if not _emit_llvm_text(
        artifacts.runtime_root_bc,
        artifacts.runtime_root_ll,
        llvm_dis,
        clang,
        "2/11 runtime root bitcode → runtime-root.ll",
    ):
        artifacts.error = "Không xuất được runtime-root.ll"
        return artifacts

    # 2. Recompile directly from the root path with the runtime.
    recompile_cmd = [
        revng,
        "artifact",
        "--resume",
        artifacts.resume_dir,
        "recompile",
        binary_path,
        "-o",
        artifacts.runtime_executable,
    ]
    if not run_command(recompile_cmd, "3/11 rev.ng root IR → runtime executable"):
        artifacts.error = "revng recompile thất bại"
        return artifacts
    if not _make_executable(artifacts.runtime_executable):
        artifacts.error = "Runtime executable không có quyền execute"
        return artifacts

    # 3. Cleanup analysis IR.
    cleanup_cmd = [
        revng,
        "artifact",
        "--resume",
        artifacts.resume_dir,
        "cleanup-ir",
        binary_path,
        "-o",
        artifacts.cleanup_zstd,
    ]
    if not run_command(cleanup_cmd, "4/11 binary → cleanup-ir"):
        artifacts.error = "revng cleanup-ir thất bại"
        return artifacts
    if not _decompress_zstd(artifacts.cleanup_zstd, artifacts.cleanup_bc):
        artifacts.error = "Không giải nén được cleanup-ir"
        return artifacts
    if not _emit_llvm_text(
        artifacts.cleanup_bc,
        artifacts.cleanup_ll,
        llvm_dis,
        clang,
        "5/11 cleanup bitcode → cleanup.ll",
    ):
        artifacts.error = "Không xuất được cleanup.ll"
        return artifacts
    artifacts.cleanup_function_count = _count_llvm_definitions(artifacts.cleanup_ll)
    if artifacts.cleanup_function_count == 0:
        artifacts.error = "cleanup-ir không chứa function definition"
        return artifacts

    # 4. Isolated translated executable used as semantic reference.
    isolated_cmd = [
        revng,
        "artifact",
        "--resume",
        artifacts.resume_dir,
        "recompile-isolated",
        binary_path,
        "-o",
        artifacts.translated_executable,
    ]
    if not run_command(isolated_cmd, "6/11 tạo recompile-isolated executable"):
        artifacts.error = "recompile-isolated thất bại"
        return artifacts
    if not _make_executable(artifacts.translated_executable):
        artifacts.error = "Translated executable không có quyền execute"
        return artifacts

    # 5. Decompiled C → native-looking Clang IR. This lane is verified only up
    #    to object generation; it is not linked as a standalone application.
    archive_cmd = [
        revng,
        "artifact",
        "--resume",
        artifacts.resume_dir,
        "emit-recompilable-archive",
        binary_path,
        "-o",
        artifacts.recompilable_archive,
    ]
    if not run_command(archive_cmd, "7/11 xuất recompilable C archive"):
        artifacts.error = "emit-recompilable-archive thất bại"
        return artifacts

    try:
        if os.path.isdir(artifacts.recovered_source_dir):
            shutil.rmtree(artifacts.recovered_source_dir)
        os.makedirs(artifacts.recovered_source_dir, exist_ok=True)
        _safe_extract_tar(artifacts.recompilable_archive, artifacts.recovered_source_dir)
    except Exception as exc:
        artifacts.error = f"Không giải nén được recompilable archive: {exc}"
        return artifacts

    candidates = sorted(Path(artifacts.recovered_source_dir).rglob("functions.c"))
    if not candidates:
        artifacts.error = "Archive không chứa functions.c"
        return artifacts
    artifacts.recovered_c = str(candidates[0].resolve())
    source_dir = str(candidates[0].parent.resolve())

    include_dirs = sorted({source_dir, artifacts.recovered_source_dir})
    common_c_flags = [
        "-std=gnu11",
        "-O0",
        "-Xclang",
        "-disable-O0-optnone",
        "-fno-discard-value-names",
        "-fno-strict-aliasing",
        "-fwrapv",
        "-Wno-everything",
    ]
    for include_dir in include_dirs:
        common_c_flags.extend(["-I", include_dir])

    compile_bc_cmd = [
        clang,
        *common_c_flags,
        "-emit-llvm",
        "-c",
        artifacts.recovered_c,
        "-o",
        artifacts.native_raw_bc,
    ]
    if not run_command(compile_bc_cmd, "8/11 recovered C → native-looking bitcode"):
        artifacts.error = "Clang không compile được recovered C sang bitcode"
        return artifacts

    if optimize_native_ir and opt:
        if not run_command(
            [opt, "-passes=default<O1>", artifacts.native_raw_bc, "-o", artifacts.native_bc],
            "9/11 tối ưu nhẹ native-looking IR",
        ):
            print(f"{Color.YELLOW}[!] opt thất bại; dùng raw Clang bitcode.{Color.END}")
            shutil.copy2(artifacts.native_raw_bc, artifacts.native_bc)
    else:
        shutil.copy2(artifacts.native_raw_bc, artifacts.native_bc)

    if not _emit_llvm_text(
        artifacts.native_bc,
        artifacts.native_ll,
        llvm_dis,
        clang,
        "10/11 native bitcode → native.ll",
    ):
        artifacts.error = "Không xuất được native.ll"
        return artifacts
    artifacts.native_function_count = _count_llvm_definitions(artifacts.native_ll)

    if not run_command(
        [clang, "-c", artifacts.native_bc, "-o", artifacts.native_object],
        "11/11 xác nhận native-looking IR compile thành object",
    ):
        artifacts.error = "Native-looking IR không compile được thành object"
        return artifacts

    artifacts.success = True
    artifacts.error = None
    _write_manifest(artifacts)

    if use_cache:
        index = _load_cache_index()
        cache_data = asdict(artifacts)
        cache_data["timestamp"] = time.strftime("%Y-%m-%dT%H:%M:%S")
        cache_data["pipeline_version"] = PIPELINE_VERSION
        cache_data["revng_version"] = revng_version
        cache_data["clang_version"] = clang_version
        index[cache_key] = cache_data
        _save_cache_index(index)

    print(f"\n{Color.GREEN}[✓] Recovery hoàn tất.{Color.END}")
    print(f"    runtime root IR:  {artifacts.runtime_root_ll}")
    print(f"    runtime exe:      {artifacts.runtime_executable}")
    print(f"    cleanup IR:       {artifacts.cleanup_ll}")
    print(f"    native-looking IR:{artifacts.native_ll}")
    print(f"    native object:    {artifacts.native_object}")
    print(f"    semantic exe:     {artifacts.translated_executable}")
    print(f"    manifest:         {artifacts.manifest_path}")
    print(
        f"{Color.YELLOW}[!] native-looking IR được xác nhận tới object file; "
        "không link thẳng bằng Clang vì có thể thiếu main/runtime helpers."
        f"{Color.END}"
    )
    return artifacts


def _copy_requested_output(artifacts: RecoveryArtifacts, output: str) -> bool:
    output = os.path.abspath(output)
    os.makedirs(os.path.dirname(output), exist_ok=True)
    lower = output.lower()

    if lower.endswith(".runtime.ll"):
        source = artifacts.runtime_root_ll
    elif lower.endswith(".runtime.bc"):
        source = artifacts.runtime_root_bc
    elif lower.endswith(".cleanup.ll"):
        source = artifacts.cleanup_ll
    elif lower.endswith(".cleanup.bc"):
        source = artifacts.cleanup_bc
    elif lower.endswith(".ll"):
        source = artifacts.native_ll
    elif lower.endswith(".bc"):
        source = artifacts.native_bc
    elif lower.endswith((".exe", ".out", ".bin")):
        # Executable outputs are always the runtime-linked rev.ng translation.
        source = artifacts.translated_executable
    elif lower.endswith(".json"):
        source = artifacts.manifest_path
    else:
        print(
            f"{Color.RED}[✗] --output phải là .ll/.bc/.runtime.ll/.runtime.bc/"
            f".cleanup.ll/.cleanup.bc/.exe/.out/.bin/.json.{Color.END}"
        )
        return False

    if not source or not os.path.isfile(source):
        print(f"{Color.RED}[✗] Artifact yêu cầu chưa được tạo: {source}{Color.END}")
        return False
    if os.path.abspath(source) != output:
        shutil.copy2(source, output)
    if lower.endswith((".exe", ".out", ".bin")):
        _make_executable(output)
    return True


def lift_binary(
    binary_path: str,
    output: Optional[str] = None,
    arch: str = "amd64",
    os_name: str = "linux",
    entrypoint: str = "main",
    use_cache: bool = True,
    force_relift: bool = False,
    disassembler: Optional[str] = None,
    ghidra: Optional[str] = None,
) -> bool:
    """Backward-compatible boolean wrapper.

    `arch`, `os_name`, `entrypoint`, `disassembler`, and `ghidra` are retained
    for old call sites only. rev.ng derives architecture/ABI/entry point from
    the input binary and model.
    """
    del arch, os_name, entrypoint, disassembler, ghidra
    output_dir = os.path.dirname(os.path.abspath(output)) if output else None
    artifacts = recover_binary(
        binary_path,
        output_dir,
        use_cache=use_cache,
        force_relift=force_relift,
    )
    if not artifacts.success:
        print(f"{Color.RED}[✗] Recovery thất bại: {artifacts.error}{Color.END}")
        return False
    return _copy_requested_output(artifacts, output) if output else True


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "binary → runtime rev.ng IR/executable + cleanup IR + native-looking object IR"
        )
    )
    parser.add_argument("-b", "--binary", help="Binary đầu vào")
    parser.add_argument("-o", "--output", help="Copy một artifact ra đường dẫn chỉ định")
    parser.add_argument("--output-dir", help="Thư mục chứa toàn bộ artifact")
    parser.add_argument("--no-opt", action="store_true", help="Không chạy opt O1 cho native IR")
    parser.add_argument("--no-cache", action="store_true")
    parser.add_argument("--force-relift", action="store_true")
    parser.add_argument("--list-cache", action="store_true")
    parser.add_argument("--clear-cache", action="store_true")
    # Accepted for compatibility but intentionally not enforced.
    parser.add_argument("--require-native-exe", action="store_true", help=argparse.SUPPRESS)
    args = parser.parse_args()

    if args.list_cache:
        list_cache_entries()
        return 0
    if args.clear_cache:
        clear_cache()
        return 0
    if not args.binary:
        parser.error("--binary là bắt buộc")

    output_dir = args.output_dir
    if not output_dir and args.output:
        output_dir = os.path.dirname(os.path.abspath(args.output))

    artifacts = recover_binary(
        args.binary,
        output_dir,
        use_cache=not args.no_cache,
        force_relift=args.force_relift,
        optimize_native_ir=not args.no_opt,
        require_native_executable=args.require_native_exe,
    )
    if not artifacts.success:
        print(f"{Color.RED}[✗] {artifacts.error}{Color.END}")
        return 1
    if args.output and not _copy_requested_output(artifacts, args.output):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
