/* This file was generated by the Hex-Rays decompiler version 9.3.0.260213.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
__int64 sub_401020(); // weak
// int puts(const char *s);
// __int64 __isoc99_scanf(const char *, ...); weak
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)());
char *sub_401090();
char *sub_401100();
__int64 sub_401130(); // weak
__int64 *__fastcall sub_401140(__int64 *a1, __int64 *a2);
unsigned __int64 __fastcall sub_401180(__int64 a1, __int64 a2);
__int64 __fastcall sub_401610(unsigned __int64 a1);
unsigned __int64 __fastcall sub_4016C0(unsigned __int64 a1, unsigned __int64 a2);
unsigned __int64 __fastcall sub_4019D0(unsigned __int64 a1, unsigned __int64 a2);
__int64 __fastcall sub_401B90(__int64 a1, __int64 a2);
__int64 __fastcall sub_401D50(__int64 a1, __int64 a2);
__int64 __fastcall sub_402100(unsigned __int64 a1, unsigned __int64 a2);
__int64 __fastcall sub_402370(__int64 a1, __int64 a2);
__int64 __fastcall sub_402940(unsigned __int64 a1, int a2);
__int64 __fastcall sub_402DC0(char *a1, char *a2);
__int64 __fastcall sub_403010(_DWORD *a1, _DWORD *a2);
__int64 __fastcall sub_4033B0(_QWORD *a1, _QWORD *a2);
__int64 __fastcall sub_403730(_QWORD *a1, _QWORD *a2);
__int64 __fastcall sub_403860(__int64 a1, __int64 a2);
__int64 __fastcall sub_403A30(__int64 a1, __int64 a2);
__int64 __fastcall sub_403C40(__int64 a1, __int64 a2);
__int64 __fastcall sub_403D20(_QWORD *a1, _QWORD *a2);
__int64 __fastcall sub_403D50(__int64 a1, __int64 a2);
__int64 __fastcall sub_403D80(_QWORD *a1, _QWORD *a2);
__int64 __fastcall sub_403F80(_QWORD *a1, _QWORD *a2);
__int64 __fastcall sub_403FB0(_QWORD *a1, _QWORD *a2);
__int64 __fastcall sub_403FE0(char a1);
unsigned __int64 __fastcall sub_404010(unsigned __int64 a1, unsigned __int64 a2);
__int64 __fastcall sub_404380(int a1, int a2, int a3);
__int64 sub_404580(void); // weak
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN main;
__int64 (*qword_406FF8)(void) = NULL; // weak
char byte_407020; // weak
__int64 qword_407030; // weak
char byte_407040[200008]; // weak
__int64 qword_437D88; // weak
__int64 qword_437D90; // weak
_UNKNOWN unk_437DD8; // weak
_UNKNOWN unk_437DE0; // weak
_UNKNOWN unk_437DEC; // weak
_UNKNOWN unk_437DF0; // weak
_UNKNOWN unk_437DF4; // weak
_UNKNOWN unk_437DF8; // weak
_UNKNOWN unk_437DFC; // weak
_UNKNOWN unk_437E04; // weak
_UNKNOWN unk_437E08; // weak
_UNKNOWN unk_437E0C; // weak
_UNKNOWN unk_437E10; // weak
_UNKNOWN unk_437E14; // weak
_UNKNOWN unk_437E1C; // weak
_UNKNOWN unk_437E20; // weak
_UNKNOWN unk_437E2C; // weak
_UNKNOWN unk_437E34; // weak
_UNKNOWN unk_437E38; // weak
_UNKNOWN unk_437E3C; // weak
_UNKNOWN unk_437E40; // weak
_UNKNOWN unk_437E44; // weak
_UNKNOWN unk_437E48; // weak
_UNKNOWN unk_437E50; // weak
_UNKNOWN unk_437E64; // weak
_UNKNOWN unk_437E68; // weak
_UNKNOWN unk_437E70; // weak
_UNKNOWN unk_437E74; // weak
_UNKNOWN unk_437E88; // weak
_UNKNOWN unk_437E8C; // weak
_UNKNOWN unk_437E90; // weak
_UNKNOWN unk_437E94; // weak
_UNKNOWN unk_437E98; // weak
_UNKNOWN unk_437EA0; // weak
_UNKNOWN unk_437EA4; // weak
_UNKNOWN unk_437EAC; // weak


//----- (0000000000401000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 437EC8: using guessed type __int64 _gmon_start__(void);

//----- (0000000000401020) ----------------------------------------------------
__int64 sub_401020()
{
  return qword_406FF8();
}
// 401020: using guessed type __int64 sub_401020();
// 406FF8: using guessed type __int64 (*qword_406FF8)(void);

//----- (0000000000401050) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)())
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, nullptr, nullptr, a3, &v5);
  __halt();
}
// 40105A: positive sp value 8 has been found
// 401061: variable 'v3' is possibly undefined

//----- (0000000000401090) ----------------------------------------------------
char *sub_401090()
{
  return &byte_407020;
}
// 407020: using guessed type char byte_407020;

//----- (0000000000401100) ----------------------------------------------------
char *sub_401100()
{
  char *result; // rax

  if ( !byte_407020 )
  {
    result = sub_401090();
    byte_407020 = 1;
  }
  return result;
}
// 407020: using guessed type char byte_407020;

//----- (0000000000401130) ----------------------------------------------------
__int64 sub_401130()
{
  return 0;
}
// 401130: using guessed type __int64 sub_401130();

//----- (0000000000401140) ----------------------------------------------------
__int64 *__fastcall sub_401140(__int64 *a1, __int64 *a2)
{
  __int64 v3; // [rsp+0h] [rbp-18h]

  v3 = *a2;
  *a2 = *a1;
  *a1 = v3;
  return a1;
}

//----- (0000000000401180) ----------------------------------------------------
unsigned __int64 __fastcall sub_401180(__int64 a1, __int64 a2)
{
  int v2; // eax
  int v3; // eax
  int v4; // eax
  int v5; // eax
  int v6; // eax
  int v7; // eax
  _QWORD v9[3]; // [rsp+0h] [rbp-40h] BYREF
  int v10; // [rsp+18h] [rbp-28h]
  bool v11; // [rsp+1Eh] [rbp-22h]
  bool v12; // [rsp+1Fh] [rbp-21h]
  _QWORD *v13; // [rsp+20h] [rbp-20h]
  unsigned __int64 *v14; // [rsp+28h] [rbp-18h]
  _QWORD *v15; // [rsp+30h] [rbp-10h]
  unsigned __int64 *v16; // [rsp+38h] [rbp-8h]

  v9[1] = a1;
  v9[2] = a2;
  v11 = (((unk_437E14 - 1) * unk_437E14) & 1) == 0;
  v12 = unk_437E98 < 10;
  v10 = 1564968849;
  while ( 1 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        HIDWORD(v9[0]) = v10;
        if ( v10 != -568045551 )
          break;
        *v14 = *v14 * *v14 % 0x3B9ACA07;
        *v15 >>= 1;
        v10 = 1966398317;
      }
      if ( HIDWORD(v9[0]) != -324201496 )
        break;
      v9[0] = 1000000005;
      v9[-2] = 1;
      v10 = 510948995;
    }
    if ( HIDWORD(v9[0]) == -42894218 )
      break;
    switch ( HIDWORD(v9[0]) )
    {
      case 0xFDD8150B:
        *v16 = *v14 * *v16 % 0x3B9ACA07;
        v10 = 2042019119;
        break;
      case 0x280CB80:
        v5 = -568045551;
        if ( (*v15 & (*v15 ^ 0xFFFFFFFFFFFFFFFELL)) != 0 )
          v5 = 244754668;
        v10 = v5;
        break;
      case 0xA1170D8:
        v10 = 1966398317;
        break;
      case 0xE96A8EC:
        v6 = -36170485;
        if ( (unk_437E98 < 10 && (((unk_437E14 - 1) * unk_437E14) & 1) == 0)
           | ((unsigned __int8)~(unk_437E98 < 10) ^ (unsigned __int8)~((((unk_437E14 - 1) * unk_437E14) & 1) == 0)) & 1 )
        {
          v6 = 2042019119;
        }
        v10 = v6;
        break;
      case 0x1E747683:
        v13 = v9;
        v14 = v9;
        v15 = v9;
        v16 = &v9[-2];
        v9[0] = 1000000005;
        v9[-2] = 1;
        v3 = -324201496;
        if ( (unk_437E98 < 10) ^ ((((unk_437E14 - 1) * unk_437E14) & 1) == 0)
           | (unk_437E98 < 10 && (((unk_437E14 - 1) * unk_437E14) & 1) == 0) )
        {
          v3 = 168915160;
        }
        v10 = v3;
        break;
      case 0x21830ABA:
        v10 = -568045551;
        break;
      case 0x5D478791:
        v2 = -324201496;
        if ( ((v12 ^ v11 | (v12 && v11)) & 1) != 0 )
          v2 = 510948995;
        v10 = v2;
        break;
      case 0x7534DB6D:
        v4 = -42894218;
        if ( *v15 )
          v4 = 41995136;
        v10 = v4;
        break;
      case 0x79B6BD2F:
        *v16 = *v14 * *v16 % 0x3B9ACA07;
        v7 = -36170485;
        if ( (unk_437E98 < 10 && (((unk_437E14 - 1) * unk_437E14) & 1) == 0)
           | (unk_437E98 < 10) ^ ((((unk_437E14 - 1) * unk_437E14) & 1) == 0) )
        {
          v7 = 562236090;
        }
        v10 = v7;
        break;
    }
  }
  return *v16 * *v13 % 0x3B9ACA07;
}

//----- (0000000000401610) ----------------------------------------------------
__int64 __fastcall sub_401610(unsigned __int64 a1)
{
  int v1; // eax
  int i; // [rsp+4h] [rbp-10h]
  unsigned int v4; // [rsp+8h] [rbp-Ch]

  v4 = 1;
  for ( i = 465297070; ; i = v1 )
  {
    while ( i == -1486008715 )
    {
      a1 /= 0xAu;
      ++v4;
      i = 465297070;
    }
    if ( i != 465297070 )
      break;
    v1 = 473144387;
    if ( a1 >= 0xA )
      v1 = -1486008715;
  }
  return v4;
}
// 401657: conditional instruction was optimized away because %var_10.4==1C339C43

//----- (00000000004016C0) ----------------------------------------------------
unsigned __int64 __fastcall sub_4016C0(unsigned __int64 a1, unsigned __int64 a2)
{
  int v2; // eax
  int v3; // eax
  int v4; // eax
  int v5; // eax
  int v6; // eax
  unsigned __int64 v8; // [rsp+4h] [rbp-40h]
  int v9; // [rsp+10h] [rbp-34h]
  unsigned __int64 v10; // [rsp+34h] [rbp-10h]
  unsigned __int64 v11; // [rsp+3Ch] [rbp-8h]

  v9 = 1906060474;
  while ( 1 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( 1 )
        {
          while ( 1 )
          {
            while ( 1 )
            {
              while ( v9 == -707714363 )
              {
                v10 = a2;
                v4 = -427418931;
                if ( (unk_437E44 < 10 && (((unk_437E20 - 1) * unk_437E20) & 1) == 0)
                   | (unk_437E44 < 10) ^ ((((unk_437E20 - 1) * unk_437E20) & 1) == 0) )
                {
                  v4 = -83838677;
                }
                v9 = v4;
              }
              if ( v9 != -427418931 )
                break;
              v9 = -707714363;
            }
            if ( v9 != -83838677 )
              break;
            v9 = 378020554;
            v8 = v10;
          }
          if ( v9 != 378020554 )
            break;
          v11 = v8;
          v5 = 632221107;
          if ( (unk_437E44 < 10) ^ ((((unk_437E20 - 1) * unk_437E20) & 1) == 0)
             | (unk_437E44 < 10 && (((unk_437E20 - 1) * unk_437E20) & 1) == 0) )
          {
            v5 = 1040543390;
          }
          v9 = v5;
        }
        if ( v9 != 445509198 )
          break;
        v3 = -427418931;
        if ( (unk_437E44 < 10) ^ ((((unk_437E20 - 1) * unk_437E20) & 1) == 0)
           | (unk_437E44 < 10 && (((unk_437E20 - 1) * unk_437E20) & 1) == 0) )
        {
          v3 = -707714363;
        }
        v9 = v3;
      }
      if ( v9 != 632221107 )
        break;
      v9 = 1040543390;
    }
    if ( v9 == 985657995 )
      break;
    if ( v9 == 1040543390 )
    {
      v6 = 632221107;
      if ( (unk_437E44 < 10 && (((unk_437E20 - 1) * unk_437E20) & 1) == 0)
         | (unk_437E44 < 10) ^ ((((unk_437E20 - 1) * unk_437E20) & 1) == 0) )
      {
        v6 = 985657995;
      }
      v9 = v6;
    }
    else if ( v9 == 1771069983 )
    {
      v9 = 378020554;
      v8 = a1;
    }
    else
    {
      v2 = 445509198;
      if ( a1 < a2 )
        v2 = 1771069983;
      v9 = v2;
    }
  }
  return v11;
}
// 401799: conditional instruction was optimized away because %var_34.4==719C2CBA
// 4018CC: variable 'v10' is possibly undefined
// 4018D9: variable 'v8' is possibly undefined
// 4019B1: variable 'v11' is possibly undefined

//----- (00000000004019D0) ----------------------------------------------------
unsigned __int64 __fastcall sub_4019D0(unsigned __int64 a1, unsigned __int64 a2)
{
  int v2; // eax
  int v3; // eax
  int v4; // eax
  unsigned __int64 v6; // [rsp+4h] [rbp-38h]
  int v7; // [rsp+10h] [rbp-2Ch]
  unsigned __int64 v8; // [rsp+34h] [rbp-8h]

  v7 = -1156565636;
  while ( v7 != -1801164776 )
  {
    switch ( v7 )
    {
      case -1742343493:
        v7 = -1602079600;
        break;
      case -1602079600:
        v4 = -1742343493;
        if ( (unk_437E48 < 10) ^ ((((unk_437DFC - 59 + 58) * unk_437DFC) & 1) == 0)
           | (unk_437E48 < 10 && (((unk_437DFC - 59 + 58) * unk_437DFC) & 1) == 0) )
        {
          v4 = -1801164776;
        }
        v7 = v4;
        break;
      case -1163964619:
        v7 = 1506278808;
        v6 = a1;
        break;
      case -1156565636:
        v2 = -96963140;
        if ( a1 > a2 )
          v2 = -1163964619;
        v7 = v2;
        break;
      case -96963140:
        v7 = 1506278808;
        v6 = a2;
        break;
      default:
        v8 = v6;
        v3 = -1742343493;
        if ( (unk_437E48 < 10) ^ ((((unk_437DFC - 1) * unk_437DFC) & 1) == 0)
           | (unk_437E48 < 10 && (((unk_437DFC - 1) * unk_437DFC) & 1) == 0) )
        {
          v3 = -1602079600;
        }
        v7 = v3;
        break;
    }
  }
  return v8;
}
// 401A70: conditional instruction was optimized away because %var_2C.4==59C7FD98
// 401ACC: variable 'v6' is possibly undefined
// 401B7A: variable 'v8' is possibly undefined

//----- (0000000000401B90) ----------------------------------------------------
__int64 __fastcall sub_401B90(__int64 a1, __int64 a2)
{
  int v2; // eax
  int v3; // eax
  int v4; // eax
  __int64 v6; // [rsp+4h] [rbp-38h]
  int i; // [rsp+10h] [rbp-2Ch]
  __int64 v8; // [rsp+34h] [rbp-8h]

  for ( i = -488924056; ; i = v3 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( 1 )
        {
          while ( 1 )
          {
            while ( i == -937098657 )
              i = 271946303;
            if ( i != -488924056 )
              break;
            v2 = 958555320;
            if ( a1 < a2 )
              v2 = 1629770999;
            i = v2;
          }
          if ( i != -205283511 )
            break;
          i = 1999484146;
          v6 = v8;
        }
        if ( i != 271946303 )
          break;
        v8 = a1;
        v4 = -937098657;
        if ( (unk_437E3C < 10) ^ ((((unk_437DF0 - 1) * unk_437DF0) & 1) == 0)
           | (unk_437E3C < 10 && (((unk_437DF0 - 1) * unk_437DF0) & 1) == 0) )
        {
          v4 = -205283511;
        }
        i = v4;
      }
      if ( i != 958555320 )
        break;
      i = 1999484146;
      v6 = a2;
    }
    if ( i != 1629770999 )
      break;
    v3 = -937098657;
    if ( (unk_437E3C < 10) ^ ((((unk_437DF0 - 37 + 36) * unk_437DF0) & 1) == 0)
       | (unk_437E3C < 10 && (((unk_437DF0 - 37 + 36) * unk_437DF0) & 1) == 0) )
    {
      v3 = 271946303;
    }
  }
  return v6;
}
// 401C30: conditional instruction was optimized away because %var_2C.4==772DB4F2
// 401D3A: variable 'v6' is possibly undefined
// 401D1D: variable 'v8' is possibly undefined

//----- (0000000000401D50) ----------------------------------------------------
__int64 __fastcall sub_401D50(__int64 a1, __int64 a2)
{
  int v2; // eax
  int v3; // eax
  int v4; // eax
  __int64 v5; // rax
  __int64 v6; // rax
  int v7; // eax
  int v8; // eax
  __int64 v10; // [rsp+0h] [rbp-50h] BYREF
  int v11; // [rsp+Ch] [rbp-44h]
  __int64 v12; // [rsp+10h] [rbp-40h]
  __int64 v13; // [rsp+18h] [rbp-38h]
  __int64 v14; // [rsp+20h] [rbp-30h]
  int v15; // [rsp+28h] [rbp-28h]
  bool v16; // [rsp+2Eh] [rbp-22h]
  bool v17; // [rsp+2Fh] [rbp-21h]
  __int64 *v18; // [rsp+30h] [rbp-20h]
  __int64 *v19; // [rsp+38h] [rbp-18h]
  bool v20; // [rsp+47h] [rbp-9h]
  __int64 v21; // [rsp+48h] [rbp-8h]

  v12 = a1;
  v13 = a2;
  v16 = (((unk_437DEC - 1) * unk_437DEC) & 1) == 0;
  v17 = unk_437E38 < 10;
  v15 = -1701490254;
  while ( 1 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( 1 )
        {
          while ( 1 )
          {
            while ( 1 )
            {
              while ( 1 )
              {
                while ( 1 )
                {
                  v11 = v15;
                  if ( v15 != -1701490254 )
                    break;
                  v2 = -500467890;
                  if ( (v17 && v16) | v17 ^ v16 )
                    v2 = -1045398771;
                  v15 = v2;
                }
                if ( v11 != -1243146514 )
                  break;
                v5 = *v18;
                v15 = -928557429;
                v14 = v5;
              }
              if ( v11 != -1232363649 )
                break;
              v15 = -1201334106;
            }
            if ( v11 != -1201334106 )
              break;
            v8 = -1232363649;
            if ( (unk_437E38 < 10 && (((unk_437DEC - 1) * unk_437DEC) & 1) == 0)
               | (unk_437E38 < 10) ^ ((((unk_437DEC - 1) * unk_437DEC) & 1) == 0) )
            {
              v8 = -107913291;
            }
            v15 = v8;
          }
          if ( v11 != -1045398771 )
            break;
          v18 = &v10;
          v19 = &v10 - 2;
          v10 = v12;
          *(&v10 - 2) = v13;
          v20 = *v18 > *v19;
          v3 = -500467890;
          if ( (unk_437E38 < 10) ^ ((((unk_437DEC - 1) * unk_437DEC) & 1) == 0)
             | (unk_437E38 < 10 && (((unk_437DEC - 1) * unk_437DEC) & 1) == 0) )
          {
            v3 = 1160116378;
          }
          v15 = v3;
        }
        if ( v11 != -928557429 )
          break;
        v21 = v14;
        v7 = -1232363649;
        if ( (unk_437E38 < 10 && (((unk_437DEC - 1) * unk_437DEC) & 1) == 0)
           | (unk_437E38 < 10) ^ ((((unk_437DEC - 1) * unk_437DEC) & 1) == 0) )
        {
          v7 = -1201334106;
        }
        v15 = v7;
      }
      if ( v11 != -500467890 )
        break;
      v10 = v12;
      *(&v10 - 2) = v13;
      v15 = -1045398771;
    }
    if ( v11 == -107913291 )
      break;
    if ( v11 == 658185422 )
    {
      v6 = *v19;
      v15 = -928557429;
      v14 = v6;
    }
    else if ( v11 == 1160116378 )
    {
      v4 = 658185422;
      if ( v20 )
        v4 = -1243146514;
      v15 = v4;
    }
  }
  return v21;
}

//----- (0000000000402100) ----------------------------------------------------
__int64 __fastcall sub_402100(unsigned __int64 a1, unsigned __int64 a2)
{
  int v2; // eax
  int v3; // eax
  int v4; // eax
  int v5; // eax
  int v7; // [rsp+4h] [rbp-2Ch]
  __int64 v8; // [rsp+18h] [rbp-18h]

  v7 = 8719520;
  while ( v7 != -1944884069 )
  {
    switch ( v7 )
    {
      case -1239686314:
        v8 = a1;
        v7 = -1944884069;
        break;
      case -605523226:
        v3 = 1192370391;
        if ( (unk_437E40 < 10 && (((unk_437DF8 - 1) * unk_437DF8) & 1) == 0)
           | ((unsigned __int8)~(unk_437E40 < 10) ^ (unsigned __int8)~((((unk_437DF8 - 1) * unk_437DF8) & 1) == 0)) & 1 )
        {
          v3 = -315433306;
        }
        v7 = v3;
        break;
      case -315433306:
        v8 = sub_402100(a2, a1);
        v4 = 1192370391;
        if ( (unk_437E40 < 10) ^ ((((unk_437DF8 - 1) * unk_437DF8) & 1) == 0)
           | (unk_437E40 < 10 && (((unk_437DF8 - 1) * unk_437DF8) & 1) == 0) )
        {
          v4 = 1870416422;
        }
        v7 = v4;
        break;
      case 8719520:
        v2 = 417205405;
        if ( a1 < a2 )
          v2 = -605523226;
        v7 = v2;
        break;
      case 69801859:
        v8 = sub_402100(a2, a1 % a2);
        v7 = -1944884069;
        break;
      case 417205405:
        v5 = 69801859;
        if ( !a2 )
          v5 = -1239686314;
        v7 = v5;
        break;
      case 1192370391:
        v8 = sub_402100(a2, a1);
        v7 = -315433306;
        break;
      default:
        v7 = -1944884069;
        break;
    }
  }
  return v8;
}
// 4021CA: conditional instruction was optimized away because %var_2C.4==6F7C4A26
// 402349: variable 'v8' is possibly undefined

//----- (0000000000402370) ----------------------------------------------------
__int64 __fastcall sub_402370(__int64 a1, __int64 a2)
{
  int v2; // eax
  int v3; // eax
  int v4; // eax
  int v5; // eax
  int v6; // eax
  int v7; // eax
  int v8; // eax
  int v9; // eax
  _QWORD v11[2]; // [rsp+0h] [rbp-40h] BYREF
  __int64 v12; // [rsp+10h] [rbp-30h]
  int v13; // [rsp+18h] [rbp-28h]
  char v14; // [rsp+1Eh] [rbp-22h]
  char v15; // [rsp+1Fh] [rbp-21h]
  unsigned __int64 *v16; // [rsp+20h] [rbp-20h]
  _QWORD *v17; // [rsp+28h] [rbp-18h]
  _QWORD *v18; // [rsp+30h] [rbp-10h]
  bool v19; // [rsp+3Fh] [rbp-1h]

  v11[1] = a1;
  v12 = a2;
  v14 = (((unk_437DF4 - 1) * unk_437DF4) & 1) == 0;
  v15 = unk_437E1C < 10;
  v13 = -67114156;
  while ( 1 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( 1 )
        {
          while ( 1 )
          {
            while ( 1 )
            {
              while ( 1 )
              {
                while ( 1 )
                {
                  HIDWORD(v11[0]) = v13;
                  if ( v13 != -1860089336 )
                    break;
                  v13 = -1551982433;
                }
                if ( HIDWORD(v11[0]) != -1713269404 )
                  break;
                v11[0] = v12;
                v11[-2] = 1;
                v13 = 1498522919;
              }
              if ( HIDWORD(v11[0]) != -1613522163 )
                break;
              v13 = -503792192;
            }
            if ( HIDWORD(v11[0]) != -1551982433 )
              break;
            v19 = *v17 != 0;
            v5 = -1860089336;
            if ( (unk_437E1C < 10) ^ ((((unk_437DF4 - 127 + 126) * unk_437DF4) & 1) == 0)
               | (unk_437E1C < 10 && (((unk_437DF4 - 127 + 126) * unk_437DF4) & 1) == 0) )
            {
              v5 = 1812751617;
            }
            v13 = v5;
          }
          if ( HIDWORD(v11[0]) != -1089828902 )
            break;
          v8 = -143560462;
          if ( (unk_437E1C < 10) ^ ((((unk_437DF4 - 1) * unk_437DF4) & 1) == 0)
             | (unk_437E1C < 10 && (((unk_437DF4 - 1) * unk_437DF4) & 1) == 0) )
          {
            v8 = 1433362655;
          }
          v13 = v8;
        }
        if ( HIDWORD(v11[0]) != -648298678 )
          break;
        v7 = -1089828902;
        if ( (~*v17 | 0xFFFFFFFFFFFFFFFELL) != 0xFFFFFFFFFFFFFFFFLL )
          v7 = 1180754290;
        v13 = v7;
      }
      if ( HIDWORD(v11[0]) != -503792192 )
        break;
      v4 = -1860089336;
      if ( (unk_437E1C < 10) ^ ((((unk_437DF4 - 1) * unk_437DF4) & 1) == 0)
         | (unk_437E1C < 10 && (((unk_437DF4 - 1) * unk_437DF4) & 1) == 0) )
      {
        v4 = -1551982433;
      }
      v13 = v4;
    }
    if ( HIDWORD(v11[0]) == -426266229 )
      break;
    switch ( HIDWORD(v11[0]) )
    {
      case 0xF0EA66DA:
        v13 = -503792192;
        break;
      case 0xF77170F2:
        *v17 >>= 1;
        *v16 = *v16 * *v16 % 0x3B9ACA07;
        v13 = 1433362655;
        break;
      case 0xFBFFEB54:
        v2 = -1713269404;
        if ( ((v15 & 1) != 0 && (v14 & 1) != 0) | ((unsigned __int8)~v15 ^ (unsigned __int8)~v14) & 1 )
          v2 = 1498522919;
        v13 = v2;
        break;
      case 0x4660E172:
        *v18 *= *v16;
        *v18 %= 0x3B9ACA07uLL;
        v13 = -1089828902;
        break;
      case 0x556F60DF:
        *v17 >>= 1;
        *v16 = *v16 * *v16 % 0x3B9ACA07;
        v9 = -143560462;
        if ( (unk_437E1C < 10 && (((unk_437DF4 - 1) * unk_437DF4) & 1) == 0)
           | ((unsigned __int8)~(unk_437E1C < 10) ^ (unsigned __int8)~((((unk_437DF4 - 1) * unk_437DF4) & 1) == 0)) & 1 )
        {
          v9 = -1613522163;
        }
        v13 = v9;
        break;
      case 0x5951A527:
        v16 = v11;
        v17 = v11;
        v18 = &v11[-2];
        v11[0] = v12;
        v11[-2] = 1;
        v3 = -1713269404;
        if ( (unk_437E1C < 10 && (((unk_437DF4 - 1) * unk_437DF4) & 1) == 0)
           | ((unsigned __int8)~(unk_437E1C < 10) ^ (unsigned __int8)~((((unk_437DF4 - 1) * unk_437DF4) & 1) == 0)) & 1 )
        {
          v3 = -253073702;
        }
        v13 = v3;
        break;
      case 0x6C0C6501:
        v6 = -426266229;
        if ( v19 )
          v6 = -648298678;
        v13 = v6;
        break;
    }
  }
  return *v18;
}

//----- (0000000000402940) ----------------------------------------------------
__int64 __fastcall sub_402940(unsigned __int64 a1, int a2)
{
  int v2; // eax
  int v3; // eax
  int v4; // eax
  int v5; // eax
  int v6; // eax
  int v7; // eax
  int v8; // eax
  int v9; // eax
  int v11; // [rsp+Ch] [rbp-24h]
  int v12; // [rsp+10h] [rbp-20h]
  unsigned __int64 v13; // [rsp+18h] [rbp-18h]
  unsigned int v14; // [rsp+20h] [rbp-10h]
  int v15; // [rsp+24h] [rbp-Ch]
  bool v16; // [rsp+2Fh] [rbp-1h]

  v13 = a1;
  v12 = sub_401610(a1);
  v15 = v12;
  v11 = -1736119642;
  while ( 1 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( 1 )
        {
          while ( v11 == -2138300525 )
          {
            v16 = v12 > a2;
            v6 = -1349094407;
            if ( (unk_437E08 < 10 && (((unk_437E8C - 1) * unk_437E8C) & 1) == 0)
               | (unk_437E08 < 10) ^ ((((unk_437E8C - 1) * unk_437E8C) & 1) == 0) )
            {
              v6 = 1294571230;
            }
            v11 = v6;
          }
          if ( v11 != -1736119642 )
            break;
          v2 = 639688064;
          if ( v15 < a2 )
            v2 = 679017551;
          v11 = v2;
        }
        if ( v11 != -1349094407 )
          break;
        v11 = -2138300525;
      }
      if ( v11 != -945770006 )
        break;
      v5 = -1349094407;
      if ( (unk_437E08 < 10) ^ ((((unk_437E8C - 1) * unk_437E8C) & 1) == 0)
         | (unk_437E08 < 10 && (((unk_437E8C - 1) * unk_437E8C) & 1) == 0) )
      {
        v5 = -2138300525;
      }
      v11 = v5;
    }
    if ( v11 == -722903651 )
      break;
    switch ( v11 )
    {
      case -606831314:
        v12 = v12 - 1850411135 + 1850411134;
        v13 /= 0xAu;
        v11 = -63184373;
        break;
      case -390006239:
        v4 = 1362999523;
        if ( (unk_437E08 < 10) ^ ((((unk_437E8C - 1) * unk_437E8C) & 1) == 0)
           | (unk_437E08 < 10 && (((unk_437E8C - 1) * unk_437E8C) & 1) == 0) )
        {
          v4 = -66246140;
        }
        v11 = v4;
        break;
      case -66246140:
        v11 = -945770006;
        break;
      case -63184373:
        --v12;
        v13 /= 0xAu;
        v9 = -606831314;
        if ( (unk_437E08 < 10) ^ ((((unk_437E8C - 1) * unk_437E8C) & 1) == 0)
           | (unk_437E08 < 10 && (((unk_437E8C - 1) * unk_437E8C) & 1) == 0) )
        {
          v9 = 2124663975;
        }
        v11 = v9;
        break;
      case 490340242:
        v14 = v13 % 0xA;
        v11 = -722903651;
        break;
      case 639688064:
        v3 = 1362999523;
        if ( (unk_437E08 < 10) ^ ((((unk_437E8C - 1) * unk_437E8C) & 1) == 0)
           | (unk_437E08 < 10 && (((unk_437E8C - 1) * unk_437E8C) & 1) == 0) )
        {
          v3 = -390006239;
        }
        v11 = v3;
        break;
      case 679017551:
        v14 = -1;
        v11 = -722903651;
        break;
      case 1294571230:
        v7 = 490340242;
        if ( v16 )
          v7 = 1954664829;
        v11 = v7;
        break;
      case 1362999523:
        v11 = -390006239;
        break;
      case 1954664829:
        v8 = -606831314;
        if ( (unk_437E08 < 10) ^ ((((unk_437E8C - 1) * unk_437E8C) & 1) == 0)
           | (unk_437E08 < 10 && (((unk_437E8C - 1) * unk_437E8C) & 1) == 0) )
        {
          v8 = -63184373;
        }
        v11 = v8;
        break;
      default:
        v11 = -945770006;
        break;
    }
  }
  return v14;
}
// 402A96: conditional instruction was optimized away because %var_24.4==7EA3CCA7
// 402C73: variable 'v16' is possibly undefined
// 402D6D: variable 'v14' is possibly undefined

//----- (0000000000402DC0) ----------------------------------------------------
__int64 __fastcall sub_402DC0(char *a1, char *a2)
{
  int v2; // eax
  int v3; // eax
  int v4; // eax
  int v5; // eax
  int i; // [rsp+4h] [rbp-24h]
  unsigned int v8; // [rsp+1Ch] [rbp-Ch]

  for ( i = -65964657; ; i = v4 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( 1 )
        {
          while ( 1 )
          {
            while ( 1 )
            {
              while ( 1 )
              {
                while ( i == -1353627199 )
                {
                  v8 = -1;
                  i = 1351892085;
                }
                if ( i != -1351646518 )
                  break;
                v3 = -205299920;
                if ( *a1 > *a2 )
                  v3 = 836973787;
                i = v3;
              }
              if ( i != -361564420 )
                break;
              i = 1351892085;
            }
            if ( i != -346968131 )
              break;
            v8 = 1;
            v5 = 824355969;
            if ( (unk_437E04 < 10) ^ ((((unk_437E88 - 1) * unk_437E88) & 1) == 0)
               | (unk_437E04 < 10 && (((unk_437E88 - 1) * unk_437E88) & 1) == 0) )
            {
              v5 = -361564420;
            }
            i = v5;
          }
          if ( i != -205299920 )
            break;
          v8 = 0;
          i = 1351892085;
        }
        if ( i != -65964657 )
          break;
        v2 = -1351646518;
        if ( *a1 < *a2 )
          v2 = -1353627199;
        i = v2;
      }
      if ( i != 824355969 )
        break;
      v8 = 1;
      i = -346968131;
    }
    if ( i != 836973787 )
      break;
    v4 = 824355969;
    if ( (unk_437E04 < 10 && (((unk_437E88 - 1) * unk_437E88) & 1) == 0)
       | ((unsigned __int8)~(unk_437E04 < 10) ^ (unsigned __int8)~((((unk_437E88 - 1) * unk_437E88) & 1) == 0)) & 1 )
    {
      v4 = -346968131;
    }
  }
  return v8;
}
// 402E8A: conditional instruction was optimized away because %var_24.4==50943C75
// 402FE9: variable 'v8' is possibly undefined

//----- (0000000000403010) ----------------------------------------------------
__int64 __fastcall sub_403010(_DWORD *a1, _DWORD *a2)
{
  int v2; // eax
  int v3; // eax
  int v4; // eax
  int v5; // eax
  int v6; // eax
  int v7; // eax
  int i; // [rsp+4h] [rbp-24h]
  unsigned int v10; // [rsp+18h] [rbp-10h]
  bool v11; // [rsp+27h] [rbp-1h]

  for ( i = 906897301; ; i = v7 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( 1 )
        {
          while ( 1 )
          {
            while ( 1 )
            {
              while ( 1 )
              {
                while ( 1 )
                {
                  while ( 1 )
                  {
                    while ( 1 )
                    {
                      while ( i == -1988544428 )
                      {
                        v11 = *a1 > *a2;
                        v6 = -1063320906;
                        if ( (unk_437E10 < 10 && (((unk_437E94 - 1) * unk_437E94) & 1) == 0)
                           | (unk_437E10 < 10) ^ ((((unk_437E94 - 1) * unk_437E94) & 1) == 0) )
                        {
                          v6 = 2046644676;
                        }
                        i = v6;
                      }
                      if ( i != -1063320906 )
                        break;
                      i = -1988544428;
                    }
                    if ( i != -449940349 )
                      break;
                    v5 = -1063320906;
                    if ( (unk_437E10 < 10 && (((unk_437E94 - 1) * unk_437E94) & 1) == 0)
                       | (unk_437E10 < 10) ^ ((((unk_437E94 - 1) * unk_437E94) & 1) == 0) )
                    {
                      v5 = -1988544428;
                    }
                    i = v5;
                  }
                  if ( i != -387281607 )
                    break;
                  v3 = -156503952;
                  if ( (unk_437E10 < 10) ^ ((((unk_437E94 - 1) * unk_437E94) & 1) == 0)
                     | (unk_437E10 < 10 && (((unk_437E94 - 1) * unk_437E94) & 1) == 0) )
                  {
                    v3 = -300391884;
                  }
                  i = v3;
                }
                if ( i != -300391884 )
                  break;
                v10 = -1;
                v4 = -156503952;
                if ( (unk_437E10 < 10 && (((unk_437E94 - 1) * unk_437E94) & 1) == 0)
                   | (unk_437E10 < 10) ^ ((((unk_437E94 - 1) * unk_437E94) & 1) == 0) )
                {
                  v4 = 1199044083;
                }
                i = v4;
              }
              if ( i != -156503952 )
                break;
              v10 = -1;
              i = -300391884;
            }
            if ( i != 806199947 )
              break;
            v10 = 1;
            i = 1840351474;
          }
          if ( i != 906897301 )
            break;
          v2 = -449940349;
          if ( *a1 < *a2 )
            v2 = -387281607;
          i = v2;
        }
        if ( i != 1199044083 )
          break;
        i = 1840351474;
      }
      if ( i != 1580568659 )
        break;
      v10 = 0;
      i = 1840351474;
    }
    if ( i == 1840351474 )
      break;
    v7 = 1580568659;
    if ( v11 )
      v7 = 806199947;
  }
  return v10;
}
// 403111: conditional instruction was optimized away because %var_24.4==79FD51C4
// 403354: variable 'v11' is possibly undefined
// 403388: variable 'v10' is possibly undefined

//----- (00000000004033B0) ----------------------------------------------------
__int64 __fastcall sub_4033B0(_QWORD *a1, _QWORD *a2)
{
  int v2; // eax
  int v3; // eax
  int v4; // eax
  int v5; // eax
  int v6; // eax
  int v7; // eax
  int v9; // [rsp+4h] [rbp-34h]
  int v10; // [rsp+1Ch] [rbp-1Ch]
  unsigned int v11; // [rsp+34h] [rbp-4h]

  v9 = 1830201551;
  while ( 1 )
  {
    while ( v9 == -1275928607 )
    {
      v10 = 1;
      v5 = -583007373;
      if ( (unk_437E0C < 10) ^ ((((unk_437E90 - 1) * unk_437E90) & 1) == 0)
         | (unk_437E0C < 10 && (((unk_437E90 - 1) * unk_437E90) & 1) == 0) )
      {
        v5 = -1005864817;
      }
      v9 = v5;
    }
    if ( v9 == -1015774842 )
      break;
    switch ( v9 )
    {
      case -1005864817:
        v9 = -590694427;
        break;
      case -590694427:
        v6 = 741832484;
        if ( (unk_437E0C < 10 && (((unk_437E90 - 1) * unk_437E90) & 1) == 0)
           | (unk_437E0C < 10) ^ ((((unk_437E90 - 1) * unk_437E90) & 1) == 0) )
        {
          v6 = 622217486;
        }
        v9 = v6;
        break;
      case -583007373:
        v10 = 1;
        v9 = -1275928607;
        break;
      case -48522314:
        v4 = -583007373;
        if ( (unk_437E0C < 10 && (((unk_437E90 - 1) * unk_437E90) & 1) == 0)
           | ((unsigned __int8)~(unk_437E0C < 10) ^ (unsigned __int8)~((((unk_437E90 - 1) * unk_437E90) & 1) == 0)) & 1 )
        {
          v4 = -1275928607;
        }
        v9 = v4;
        break;
      case -16009608:
        v10 = 0;
        v9 = -590694427;
        break;
      case 27813216:
        v3 = -16009608;
        if ( *a1 > *a2 )
          v3 = -48522314;
        v9 = v3;
        break;
      case 622217486:
        v11 = v10;
        v7 = 741832484;
        if ( (unk_437E0C < 10) ^ ((((unk_437E90 - 58 + 57) * unk_437E90) & 1) == 0)
           | (unk_437E0C < 10 && (((unk_437E90 - 58 + 57) * unk_437E90) & 1) == 0) )
        {
          v7 = -1015774842;
        }
        v9 = v7;
        break;
      case 741832484:
        v9 = 622217486;
        break;
      case 1775118547:
        v10 = -1;
        v9 = -590694427;
        break;
      default:
        v2 = 27813216;
        if ( *a1 < *a2 )
          v2 = 1775118547;
        v9 = v2;
        break;
    }
  }
  return v11;
}
// 4034B5: conditional instruction was optimized away because %var_34.4==6D16A8CF
// 4036A7: variable 'v10' is possibly undefined
// 4036FF: variable 'v11' is possibly undefined

//----- (0000000000403730) ----------------------------------------------------
__int64 __fastcall sub_403730(_QWORD *a1, _QWORD *a2)
{
  int v2; // eax
  int v3; // eax
  int i; // [rsp+4h] [rbp-2Ch]
  unsigned int v6; // [rsp+1Ch] [rbp-14h]

  for ( i = 864738715; ; i = 1242111982 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( i == -126831964 )
        {
          v3 = 308208628;
          if ( *a1 > *a2 )
            v3 = 2143810925;
          i = v3;
        }
        if ( i != 308208628 )
          break;
        v6 = 0;
        i = 1242111982;
      }
      if ( i != 864738715 )
        break;
      v2 = -126831964;
      if ( *a1 < *a2 )
        v2 = 1427349042;
      i = v2;
    }
    if ( i == 1242111982 )
      break;
    if ( i == 1427349042 )
      v6 = -1;
    else
      v6 = 1;
  }
  return v6;
}
// 4037C3: conditional instruction was optimized away because %var_2C.4==7FC7F56D
// 40384F: variable 'v6' is possibly undefined

//----- (0000000000403860) ----------------------------------------------------
__int64 __fastcall sub_403860(__int64 a1, __int64 a2)
{
  int v2; // eax
  __int64 v3; // rdx
  int v4; // eax
  __int64 v6; // rdx
  _BYTE v7[12]; // [rsp+0h] [rbp-30h]
  int v8; // [rsp+Ch] [rbp-24h]
  __int64 v9; // [rsp+10h] [rbp-20h]
  __int64 v10; // [rsp+18h] [rbp-18h]
  int v11; // [rsp+24h] [rbp-Ch]
  bool v12; // [rsp+2Ah] [rbp-6h]
  bool v13; // [rsp+2Bh] [rbp-5h]
  unsigned int v14; // [rsp+2Ch] [rbp-4h]

  v9 = a1;
  v10 = a2;
  v12 = (((unk_437E2C - 1) * unk_437E2C) & 1) == 0;
  v13 = unk_437E74 < 10;
  v11 = -38122575;
  do
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( 1 )
        {
          v8 = v11;
          if ( v11 != -1892691831 )
            break;
          v3 = v10;
          *(_QWORD *)&v7[-16] = v9;
          *(_QWORD *)&v7[-16] = v3;
          v14 = sub_403010(*(_DWORD **)&v7[-16], *(_DWORD **)&v7[-16]);
          v4 = 469920174;
          if ( (unk_437E74 < 10 && (((unk_437E2C - 1) * unk_437E2C) & 1) == 0)
             | ((unsigned __int8)~(unk_437E74 < 10)
              ^ (unsigned __int8)~((((unk_437E2C - 1) * unk_437E2C) & 1) == 0))
             & 1 )
          {
            v4 = 613455773;
          }
          v11 = v4;
        }
        if ( v8 != -38122575 )
          break;
        v2 = 469920174;
        if ( ((v13 ^ v12 | (v13 && v12)) & 1) != 0 )
          v2 = -1892691831;
        v11 = v2;
      }
      if ( v8 != 469920174 )
        break;
      v6 = v10;
      *(_QWORD *)&v7[-16] = v9;
      *(_QWORD *)&v7[-16] = v6;
      sub_403010(*(_DWORD **)&v7[-16], *(_DWORD **)&v7[-16]);
      v11 = -1892691831;
    }
  }
  while ( v8 != 613455773 );
  return v14;
}

//----- (0000000000403A30) ----------------------------------------------------
__int64 __fastcall sub_403A30(__int64 a1, __int64 a2)
{
  int v2; // eax
  __int64 v3; // rdx
  int v4; // eax
  __int64 v6; // rdx
  _BYTE v7[12]; // [rsp+0h] [rbp-30h]
  int v8; // [rsp+Ch] [rbp-24h]
  __int64 v9; // [rsp+10h] [rbp-20h]
  __int64 v10; // [rsp+18h] [rbp-18h]
  int v11; // [rsp+24h] [rbp-Ch]
  char v12; // [rsp+2Ah] [rbp-6h]
  char v13; // [rsp+2Bh] [rbp-5h]
  unsigned int v14; // [rsp+2Ch] [rbp-4h]

  v9 = a1;
  v10 = a2;
  v12 = (((unk_437E34 - 1) * unk_437E34) & 1) == 0;
  v13 = unk_437E70 < 10;
  v11 = 1210233557;
  while ( 1 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        v8 = v11;
        if ( v11 != -2060163261 )
          break;
        v6 = v10;
        *(_QWORD *)&v7[-16] = v9;
        *(_QWORD *)&v7[-16] = v6;
        sub_403010((_DWORD *)(*(_QWORD *)&v7[-16] + 4LL), (_DWORD *)(*(_QWORD *)&v7[-16] + 4LL));
        v11 = -1320856921;
      }
      if ( v8 != -1320856921 )
        break;
      v3 = v10;
      *(_QWORD *)&v7[-16] = v9;
      *(_QWORD *)&v7[-16] = v3;
      v14 = sub_403010((_DWORD *)(*(_QWORD *)&v7[-16] + 4LL), (_DWORD *)(*(_QWORD *)&v7[-16] + 4LL));
      v4 = -2060163261;
      if ( (unk_437E70 < 10 && (((unk_437E34 - 1) * unk_437E34) & 1) == 0)
         | ((unsigned __int8)~(unk_437E70 < 10) ^ (unsigned __int8)~((((unk_437E34 - 1) * unk_437E34) & 1) == 0)) & 1 )
      {
        v4 = -1145757661;
      }
      v11 = v4;
    }
    if ( v8 == -1145757661 )
      break;
    if ( v8 == 1210233557 )
    {
      v2 = -2060163261;
      if ( ((v13 & 1) != 0 && (v12 & 1) != 0) | ((unsigned __int8)~v13 ^ (unsigned __int8)~v12) & 1 )
        v2 = -1320856921;
      v11 = v2;
    }
  }
  return v14;
}

//----- (0000000000403C40) ----------------------------------------------------
__int64 __fastcall sub_403C40(__int64 a1, __int64 a2)
{
  int v2; // eax
  int i; // [rsp+10h] [rbp-20h]
  unsigned int v5; // [rsp+14h] [rbp-1Ch]
  unsigned int v6; // [rsp+28h] [rbp-8h]

  v5 = sub_403860(a1, a2);
  for ( i = -63774204; ; i = v2 )
  {
    while ( 1 )
    {
      while ( i == -1123434133 )
      {
        v6 = sub_403A30(a1, a2);
        i = -447729383;
      }
      if ( i != -1115052158 )
        break;
      v6 = v5;
      i = -447729383;
    }
    if ( i == -447729383 )
      break;
    v2 = -1123434133;
    if ( v5 )
      v2 = -1115052158;
  }
  return v6;
}
// 403CB1: conditional instruction was optimized away because %var_20.4==FC32E204
// 403D0A: variable 'v6' is possibly undefined

//----- (0000000000403D20) ----------------------------------------------------
__int64 __fastcall sub_403D20(_QWORD *a1, _QWORD *a2)
{
  return sub_403730(a1, a2);
}

//----- (0000000000403D50) ----------------------------------------------------
__int64 __fastcall sub_403D50(__int64 a1, __int64 a2)
{
  return sub_403730((_QWORD *)(a1 + 8), (_QWORD *)(a2 + 8));
}

//----- (0000000000403D80) ----------------------------------------------------
__int64 __fastcall sub_403D80(_QWORD *a1, _QWORD *a2)
{
  int v2; // eax
  int v3; // eax
  int v4; // eax
  int v6; // [rsp+10h] [rbp-20h]
  unsigned int v7; // [rsp+14h] [rbp-1Ch]
  unsigned int v8; // [rsp+28h] [rbp-8h]

  v7 = sub_403D20(a1, a2);
  v6 = -497425229;
  while ( 1 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( v6 == -572894977 )
        {
          v8 = sub_403D50((__int64)a1, (__int64)a2);
          v6 = 1341437956;
        }
        if ( v6 != -497425229 )
          break;
        v2 = -452801240;
        if ( v7 )
          v2 = 259291284;
        v6 = v2;
      }
      if ( v6 != -452801240 )
        break;
      v3 = -572894977;
      if ( (unk_437E50 < 10 && (((unk_437DE0 - 1) * unk_437DE0) & 1) == 0)
         | (unk_437E50 < 10) ^ ((((unk_437DE0 - 1) * unk_437DE0) & 1) == 0) )
      {
        v3 = 1341437956;
      }
      v6 = v3;
    }
    if ( v6 == -18500233 )
      break;
    if ( v6 == 259291284 )
    {
      v8 = v7;
      v6 = -18500233;
    }
    else if ( v6 == 1341437956 )
    {
      v8 = sub_403D50((__int64)a1, (__int64)a2);
      v4 = -572894977;
      if ( (unk_437E50 < 10) ^ ((((unk_437DE0 - 1) * unk_437DE0) & 1) == 0)
         | (unk_437E50 < 10 && (((unk_437DE0 - 1) * unk_437DE0) & 1) == 0) )
      {
        v4 = 1867021781;
      }
      v6 = v4;
    }
    else
    {
      v6 = -18500233;
    }
  }
  return v8;
}
// 403E2A: conditional instruction was optimized away because %var_20.4==6F487DD5
// 403F57: variable 'v8' is possibly undefined

//----- (0000000000403F80) ----------------------------------------------------
__int64 __fastcall sub_403F80(_QWORD *a1, _QWORD *a2)
{
  return sub_4033B0(a1, a2);
}

//----- (0000000000403FB0) ----------------------------------------------------
__int64 __fastcall sub_403FB0(_QWORD *a1, _QWORD *a2)
{
  return sub_4033B0(a1, a2);
}

//----- (0000000000403FE0) ----------------------------------------------------
__int64 __fastcall sub_403FE0(char a1)
{
  return (unsigned int)(1 << (a1 - 97));
}

//----- (0000000000404010) ----------------------------------------------------
unsigned __int64 __fastcall sub_404010(unsigned __int64 a1, unsigned __int64 a2)
{
  int v2; // eax
  int v3; // eax
  int v4; // eax
  int v5; // eax
  int v6; // eax
  int v8; // [rsp+4h] [rbp-34h]
  unsigned __int64 v9; // [rsp+18h] [rbp-20h]
  unsigned __int64 v10; // [rsp+30h] [rbp-8h]

  v8 = -513380076;
  while ( 1 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( v8 == -1813103459 )
        {
          v5 = 1271747718;
          if ( (unk_437EA4 < 10) ^ ((((unk_437DD8 - 1) * unk_437DD8) & 1) == 0)
             | (unk_437EA4 < 10 && (((unk_437DD8 - 1) * unk_437DD8) & 1) == 0) )
          {
            v5 = 99211742;
          }
          v8 = v5;
        }
        if ( v8 != -1378998474 )
          break;
        v9 = a2 - a1;
        v8 = -945657386;
      }
      if ( v8 != -945657386 )
        break;
      v9 = a2 - a1;
      v4 = -1378998474;
      if ( (unk_437EA4 < 10 && (((unk_437DD8 - 1) * unk_437DD8) & 1) == 0)
         | ((unsigned __int8)~(unk_437EA4 < 10) ^ (unsigned __int8)~((((unk_437DD8 - 1) * unk_437DD8) & 1) == 0)) & 1 )
      {
        v4 = -288478268;
      }
      v8 = v4;
    }
    if ( v8 == -699273245 )
      break;
    switch ( v8 )
    {
      case -659335685:
        v9 = a1 - a2;
        v8 = -1813103459;
        break;
      case -513380076:
        v2 = 366841508;
        if ( a1 >= a2 )
          v2 = -659335685;
        v8 = v2;
        break;
      case -288478268:
        v8 = -1813103459;
        break;
      case 99211742:
        v10 = v9;
        v6 = 1271747718;
        if ( (unk_437EA4 < 10 && (((unk_437DD8 - 1) * unk_437DD8) & 1) == 0)
           | (unk_437EA4 < 10) ^ ((((unk_437DD8 - 1) * unk_437DD8) & 1) == 0) )
        {
          v6 = -699273245;
        }
        v8 = v6;
        break;
      case 366841508:
        v3 = -1378998474;
        if ( (unk_437EA4 < 10 && (((unk_437DD8 - 1) * unk_437DD8) & 1) == 0)
           | (unk_437EA4 < 10) ^ ((((unk_437DD8 - 1) * unk_437DD8) & 1) == 0) )
        {
          v3 = -945657386;
        }
        v8 = v3;
        break;
      default:
        v8 = 99211742;
        break;
    }
  }
  return v10;
}
// 4040E9: conditional instruction was optimized away because %var_34.4==4BCD5486
// 4042B8: variable 'v9' is possibly undefined
// 404343: variable 'v10' is possibly undefined

//----- (0000000000404380) ----------------------------------------------------
__int64 __fastcall sub_404380(int a1, int a2, int a3)
{
  int v3; // eax
  int v4; // eax
  int v5; // eax
  int v6; // eax
  int i; // [rsp+4h] [rbp-18h]
  int v9; // [rsp+8h] [rbp-14h]
  bool v10; // [rsp+1Bh] [rbp-1h]

  v9 = a1 / a2;
  for ( i = -1838282946; ; i = v5 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( 1 )
        {
          while ( 1 )
          {
            while ( 1 )
            {
              while ( i == -1891775096 )
              {
                v4 = -511741441;
                if ( (unk_437EA0 < 10) ^ ((((unk_437E68 - 1) * unk_437E68) & 1) == 0)
                   | (unk_437EA0 < 10 && (((unk_437E68 - 1) * unk_437E68) & 1) == 0) )
                {
                  v4 = 830885088;
                }
                i = v4;
              }
              if ( i != -1838282946 )
                break;
              v3 = 1955989973;
              if ( v9 >= 0 )
                v3 = -1891775096;
              i = v3;
            }
            if ( i != -1828565342 )
              break;
            i = 1955989973;
          }
          if ( i != -1242658861 )
            break;
          --v9;
          i = -1838282946;
        }
        if ( i != -745001806 )
          break;
        v6 = -1242658861;
        if ( v10 )
          v6 = -1828565342;
        i = v6;
      }
      if ( i != -511741441 )
        break;
      i = 830885088;
    }
    if ( i != 830885088 )
      break;
    v10 = (a1 - v9 * a2) % a3 == 0;
    v5 = -511741441;
    if ( (unk_437EA0 < 10) ^ ((((unk_437E68 - 1) * unk_437E68) & 1) == 0)
       | (unk_437EA0 < 10 && (((unk_437E68 - 1) * unk_437E68) & 1) == 0) )
    {
      v5 = -745001806;
    }
  }
  return (unsigned int)v9;
}
// 40442E: conditional instruction was optimized away because %var_18.4==749609D5
// 40452D: variable 'v10' is possibly undefined

//----- (0000000000404580) ----------------------------------------------------
__int64 sub_404580()
{
  bool v0; // cl
  bool v1; // cl
  bool v2; // cl
  int v4; // [rsp+4h] [rbp-2Ch]
  unsigned __int64 v5; // [rsp+8h] [rbp-28h]
  __int64 v6; // [rsp+10h] [rbp-20h]
  int i; // [rsp+2Ch] [rbp-4h]

  v6 = 0;
  v5 = 0;
  for ( i = 0; i < (unsigned __int64)qword_407030; ++i )
  {
    do
    {
      v4 = byte_407040[i];
      v0 = (((unk_437E64 - 65 + 64) * unk_437E64) & 1) == 0;
    }
    while ( !(((unk_437EAC < 10) ^ v0) & 1 | (unk_437EAC < 10 && v0)) );
    switch ( v4 )
    {
      case 'a':
        do
          v1 = (((unk_437E64 - 1) * unk_437E64) & 1) == 0;
        while ( !(((unk_437EAC < 10) ^ v1) & 1 | (unk_437EAC < 10 && v1)) );
        if ( v5 + v6 < qword_437D88 + qword_437D90 )
        {
          puts("Yes");
          ++v6;
          continue;
        }
LABEL_19:
        puts("No");
        continue;
      case 'b':
        if ( v6 + v5 >= qword_437D90 + qword_437D88 || v5 >= qword_437D90 )
        {
          if ( !((unk_437EAC < 10 && (((unk_437E64 - 1) * unk_437E64) & 1) == 0)
               | ((unsigned __int8)~(unk_437EAC < 10)
                ^ (unsigned __int8)~((((unk_437E64 - 1) * unk_437E64) & 1) == 0))
               & 1) )
            goto LABEL_24;
          while ( 1 )
          {
            puts("No");
            if ( (unk_437EAC < 10 && (((unk_437E64 - 118 + 117) * unk_437E64) & 1) == 0)
               | ((unsigned __int8)~(unk_437EAC < 10)
                ^ (unsigned __int8)~((((unk_437E64 - 118 + 117) * unk_437E64) & 1) == 0))
               & 1 )
            {
              break;
            }
LABEL_24:
            puts("No");
          }
        }
        else
        {
          puts("Yes");
          ++v5;
        }
        do
          v2 = (((unk_437E64 - 1) * unk_437E64) & 1) == 0;
        while ( !(((unk_437EAC < 10) ^ v2) & 1 | (unk_437EAC < 10 && v2)) );
        continue;
      case 'c':
        goto LABEL_19;
    }
  }
  return 0;
}
// 404580: using guessed type __int64 sub_404580();
// 407030: using guessed type __int64 qword_407030;
// 437D88: using guessed type __int64 qword_437D88;
// 437D90: using guessed type __int64 qword_437D90;

//----- (0000000000404AD0) ----------------------------------------------------
__int64 __fastcall main(int a1, char **a2, char **a3)
{
  __isoc99_scanf("%llu", &qword_407030);
  __isoc99_scanf("%llu%llu", &qword_437D88, &qword_437D90);
  __isoc99_scanf("%s", byte_407040);
  sub_404580();
  return 0;
}
// 401040: using guessed type __int64 __isoc99_scanf(const char *, ...);
// 404580: using guessed type __int64 sub_404580(void);
// 407030: using guessed type __int64 qword_407030;
// 437D88: using guessed type __int64 qword_437D88;
// 437D90: using guessed type __int64 qword_437D90;

//----- (0000000000404B54) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=40 queued=34 decompiled=34 lumina nreq=0 worse=0 better=0
// ALL OK, 34 function(s) have been successfully decompiled
