;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2026 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 14-0000-FFFF-88                      |
; |                        auth <admin@hex-rays.com>                        |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : D7E46A2537C958B301385BC926415A6A4976A66B9E9763A97BDBED4CDD110EEC
; Input MD5    : 8FB80D4E034BCB2D9B377E4766DC0816
; Input CRC32  : 12E0D4A3
; Compiler     : GNU C++

; File Name   : /home/dungbv/capstone_project/data/obfuscated/p00016/s594333826_instsub.elf
; Format      : ELF64 for x86-64 (Executable)
; Imagebase   : 400000
; Interpreter '/lib64/ld-linux-x86-64.so.2'
; Needed Library 'libm.so.6'
; Needed Library 'libc.so.6'
;

                .686p
                .mmx
                .model flat
.intel_syntax noprefix

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read
LOAD            segment mempage public 'DATA' use64
                assume cs:LOAD
                ;org 400000h
dword_400000    dd 464C457Fh            ; DATA XREF: LOAD:00000000004000C0↓o
                                        ; File format: \x7FELF
                db 2                    ; File class: 64-bit
                db 1                    ; Data encoding: little-endian
                db 1                    ; File version
                db 0                    ; OS/ABI: UNIX System V ABI
                db 0                    ; ABI Version
                db 7 dup(0)             ; Padding
                dw 2                    ; File type: Executable
                dw 3Eh                  ; Machine: x86-64
                dd 1                    ; File version
                dq offset start         ; Entry point
                dq 40h                  ; PHT file offset
                dq 31D0h                ; SHT file offset
                dd 0                    ; Processor-specific flags
                dw 40h                  ; ELF header size
                dw 38h                  ; PHT entry size
                dw 0Dh                  ; Number of entries in PHT
                dw 40h                  ; SHT entry size
                dw 1Bh                  ; Number of entries in SHT
                dw 1Ah                  ; SHT entry index for string table
; ELF64 Program Header
; PHT Entry 0
dword_400040    dd 6                    ; DATA XREF: LOAD:0000000000400050↓o
                                        ; Type: PHDR
                dd 4                    ; Flags
                dq 40h                  ; File offset
                dq offset dword_400040  ; Virtual address
                dq 400040h              ; Physical address
                dq 2D8h                 ; Size in file image
                dq 2D8h                 ; Size in memory image
                dq 8                    ; Alignment
; PHT Entry 1
                dd 3                    ; Type: INTERP
                dd 4                    ; Flags
                dq 318h                 ; File offset
                dq offset aLib64LdLinuxX8 ; Virtual address
                dq 400318h              ; Physical address
                dq 1Ch                  ; Size in file image
                dq 1Ch                  ; Size in memory image
                dq 1                    ; Alignment
; PHT Entry 2
                dd 1                    ; Type: LOAD
                dd 4                    ; Flags
                dq 0                    ; File offset
                dq offset dword_400000  ; Virtual address
                dq 400000h              ; Physical address
                dq 620h                 ; Size in file image
                dq 620h                 ; Size in memory image
                dq 1000h                ; Alignment
; PHT Entry 3
                dd 1                    ; Type: LOAD
                dd 5                    ; Flags
                dq 1000h                ; File offset
                dq offset _init_proc    ; Virtual address
                dq 401000h              ; Physical address
                dq 49Dh                 ; Size in file image
                dq 49Dh                 ; Size in memory image
                dq 1000h                ; Alignment
; PHT Entry 4
                dd 1                    ; Type: LOAD
                dd 4                    ; Flags
                dq 2000h                ; File offset
                dq offset qword_402000  ; Virtual address
                dq 402000h              ; Physical address
                dq 1D0h                 ; Size in file image
                dq 1D0h                 ; Size in memory image
                dq 1000h                ; Alignment
; PHT Entry 5
                dd 1                    ; Type: LOAD
                dd 6                    ; Flags
                dq 2DE8h                ; File offset
                dq offset off_403DE8    ; Virtual address
                dq 403DE8h              ; Physical address
                dq 260h                 ; Size in file image
                dq 268h                 ; Size in memory image
                dq 1000h                ; Alignment
; PHT Entry 6
                dd 2                    ; Type: DYNAMIC
                dd 6                    ; Flags
                dq 2DF8h                ; File offset
                dq offset stru_403DF8   ; Virtual address
                dq 403DF8h              ; Physical address
                dq 1E0h                 ; Size in file image
                dq 1E0h                 ; Size in memory image
                dq 8                    ; Alignment
; PHT Entry 7
                dd 4                    ; Type: NOTE
                dd 4                    ; Flags
                dq 2190h                ; File offset
                dq offset dword_402190  ; Virtual address
                dq 402190h              ; Physical address
                dq 20h                  ; Size in file image
                dq 20h                  ; Size in memory image
                dq 8                    ; Alignment
; PHT Entry 8
                dd 4                    ; Type: NOTE
                dd 4                    ; Flags
                dq 21B0h                ; File offset
                dq offset dword_4021B0  ; Virtual address
                dq 4021B0h              ; Physical address
                dq 20h                  ; Size in file image
                dq 20h                  ; Size in memory image
                dq 4                    ; Alignment
; PHT Entry 9
                dd 6474E553h            ; Type: 6474E553
                dd 4                    ; Flags
                dq 2190h                ; File offset
                dq offset dword_402190  ; Virtual address
                dq 402190h              ; Physical address
                dq 20h                  ; Size in file image
                dq 20h                  ; Size in memory image
                dq 8                    ; Alignment
; PHT Entry 10
                dd 6474E550h            ; Type: EH_FRAME
                dd 4                    ; Flags
                dq 2030h                ; File offset
                dq offset qword_402030  ; Virtual address
                dq 402030h              ; Physical address
                dq 4Ch                  ; Size in file image
                dq 4Ch                  ; Size in memory image
                dq 4                    ; Alignment
; PHT Entry 11
                dd 6474E551h            ; Type: STACK
                dd 6                    ; Flags
                dq 0                    ; File offset
                dq 0                    ; Virtual address
                dq 0                    ; Physical address
                dq 0                    ; Size in file image
                dq 0                    ; Size in memory image
                dq 10h                  ; Alignment
; PHT Entry 12
                dd 6474E552h            ; Type: RO-AFTER
                dd 4                    ; Flags
                dq 2DE8h                ; File offset
                dq offset off_403DE8    ; Virtual address
                dq 403DE8h              ; Physical address
                dq 218h                 ; Size in file image
                dq 218h                 ; Size in memory image
                dq 1                    ; Alignment
aLib64LdLinuxX8 db '/lib64/ld-linux-x86-64.so.2',0
                                        ; DATA XREF: LOAD:0000000000400088↑o
                align 8
; ELF GNU Hash Table
elf_gnu_hash_nbuckets dd 1
elf_gnu_hash_symbias dd 1
elf_gnu_hash_bitmask_nwords dd 1
elf_gnu_hash_shift dd 0
elf_gnu_hash_indexes dq 0
elf_gnu_hash_bucket dd 0
elf_gnu_hash_chain dd 0
; ELF Symbol Table
                Elf64_Sym <0>
                Elf64_Sym <offset aLibcStartMain - offset byte_400448, 12h, 0, 0, 0, \ ; "__libc_start_main"
                           0>
                Elf64_Sym <offset aPrintf - offset byte_400448, 12h, 0, 0, 0, 0> ; "printf"
                Elf64_Sym <offset aMemset - offset byte_400448, 12h, 0, 0, 0, 0> ; "memset"
                Elf64_Sym <offset aCos - offset byte_400448, 12h, 0, 0, 0, 0> ; "cos"
                Elf64_Sym <offset aGmonStart - offset byte_400448, 20h, 0, 0, 0, 0> ; "__gmon_start__"
                Elf64_Sym <offset aSin - offset byte_400448, 12h, 0, 0, 0, 0> ; "sin"
                Elf64_Sym <offset aFloor - offset byte_400448, 12h, 0, 0, 0, 0> ; "floor"
                Elf64_Sym <offset aIsoc99Scanf - offset byte_400448, 12h, 0, 0, 0, 0> ; "__isoc99_scanf"
                Elf64_Sym <offset aCeil - offset byte_400448, 12h, 0, 0, 0, 0> ; "ceil"
; ELF String Table
byte_400448     db 0                    ; DATA XREF: LOAD:0000000000400370↑o
                                        ; LOAD:0000000000400388↑o ...
aGmonStart      db '__gmon_start__',0   ; DATA XREF: LOAD:00000000004003D0↑o
aFloor          db 'floor',0            ; DATA XREF: LOAD:0000000000400400↑o
aCeil           db 'ceil',0             ; DATA XREF: LOAD:0000000000400430↑o
aCos            db 'cos',0              ; DATA XREF: LOAD:00000000004003B8↑o
aSin            db 'sin',0              ; DATA XREF: LOAD:00000000004003E8↑o
aLibcStartMain  db '__libc_start_main',0 ; DATA XREF: LOAD:0000000000400370↑o
aMemset         db 'memset',0           ; DATA XREF: LOAD:00000000004003A0↑o
aPrintf         db 'printf',0           ; DATA XREF: LOAD:0000000000400388↑o
aIsoc99Scanf    db '__isoc99_scanf',0   ; DATA XREF: LOAD:0000000000400418↑o
aLibmSo6        db 'libm.so.6',0        ; DATA XREF: LOAD:00000000004004E8↓o
aLibcSo6        db 'libc.so.6',0        ; DATA XREF: LOAD:0000000000400508↓o
aGlibc225       db 'GLIBC_2.2.5',0      ; DATA XREF: LOAD:00000000004004F8↓o
                                        ; LOAD:0000000000400528↓o
aGlibc27        db 'GLIBC_2.7',0        ; DATA XREF: LOAD:0000000000400518↓o
aGlibc234       db 'GLIBC_2.34',0       ; DATA XREF: LOAD:0000000000400538↓o
                align 10h
; ELF GNU Symbol Version Table
                dw 0
                dw 2                    ; __libc_start_main@@GLIBC_2.34
                dw 3                    ; printf@@GLIBC_2.2.5
                dw 3                    ; memset@@GLIBC_2.2.5
                dw 4                    ; cos@@GLIBC_2.2.5
                dw 0                    ; local  symbol: __gmon_start__
                dw 4                    ; sin@@GLIBC_2.2.5
                dw 4                    ; floor@@GLIBC_2.2.5
                dw 5                    ; __isoc99_scanf@@GLIBC_2.7
                dw 4                    ; ceil@@GLIBC_2.2.5
                dw 0
                dw 0
; ELF GNU Symbol Version Requirements
                Elf64_Verneed <1, 1, offset aLibmSo6 - offset byte_400448, 10h, 20h> ; "libm.so.6"
                Elf64_Vernaux <9691A75h, 0, 4, offset aGlibc225 - offset byte_400448, \ ; "GLIBC_2.2.5"
                               0>
                Elf64_Verneed <1, 3, offset aLibcSo6 - offset byte_400448, 10h, 0> ; "libc.so.6"
                Elf64_Vernaux <0D696917h, 0, 5, offset aGlibc27 - offset byte_400448, \ ; "GLIBC_2.7"
                               10h>
                Elf64_Vernaux <9691A75h, 0, 3, offset aGlibc225 - offset byte_400448, \ ; "GLIBC_2.2.5"
                               10h>
                Elf64_Vernaux <69691B4h, 0, 2, offset aGlibc234 - offset byte_400448, \ ; "GLIBC_2.34"
                               0>
; ELF RELA Relocation Table
                Elf64_Rela <403FD8h, 100000006h, 0> ; R_X86_64_GLOB_DAT __libc_start_main
                Elf64_Rela <403FE0h, 500000006h, 0> ; R_X86_64_GLOB_DAT __gmon_start__
; ELF JMPREL Relocation Table
                Elf64_Rela <404000h, 200000007h, 0> ; R_X86_64_JUMP_SLOT printf
                Elf64_Rela <404008h, 300000007h, 0> ; R_X86_64_JUMP_SLOT memset
                Elf64_Rela <404010h, 400000007h, 0> ; R_X86_64_JUMP_SLOT cos
                Elf64_Rela <404018h, 600000007h, 0> ; R_X86_64_JUMP_SLOT sin
                Elf64_Rela <404020h, 700000007h, 0> ; R_X86_64_JUMP_SLOT floor
                Elf64_Rela <404028h, 800000007h, 0> ; R_X86_64_JUMP_SLOT __isoc99_scanf
                Elf64_Rela <404030h, 900000007h, 0> ; R_X86_64_JUMP_SLOT ceil
LOAD            ends

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
_init           segment dword public 'CODE' use64
                assume cs:_init
                ;org 401000h
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B R O U T I N E =======================================


                public _init_proc
_init_proc      proc near               ; DATA XREF: LOAD:00000000004000F8↑o
                endbr64
                sub     rsp, 8
                mov     rax, cs:__gmon_start___ptr
                test    rax, rax
                jz      short loc_401016
                call    rax ; __gmon_start__

loc_401016:                             ; CODE XREF: _init_proc+12↑j
                add     rsp, 8
                retn
_init_proc      endp

_init           ends

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
LOAD            segment mempage public 'CODE' use64
                assume cs:LOAD
                ;org 40101Bh
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
                align 20h
LOAD            ends

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
_plt            segment para public 'CODE' use64
                assume cs:_plt
                ;org 401020h
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B R O U T I N E =======================================


sub_401020      proc near               ; CODE XREF: .plt:000000000040103B↓j
                                        ; .plt:000000000040104B↓j ...
; __unwind {
                push    cs:qword_403FF0
                jmp     cs:qword_403FF8
sub_401020      endp

; ---------------------------------------------------------------------------
                align 10h
; [00000006 BYTES: COLLAPSED FUNCTION _printf]
; ---------------------------------------------------------------------------
                push    0
                jmp     sub_401020
; [00000006 BYTES: COLLAPSED FUNCTION _memset]
; ---------------------------------------------------------------------------
                push    1
                jmp     sub_401020
; [00000006 BYTES: COLLAPSED FUNCTION _cos]
; ---------------------------------------------------------------------------
                push    2
                jmp     sub_401020
; [00000006 BYTES: COLLAPSED FUNCTION _sin]
; ---------------------------------------------------------------------------
                push    3
                jmp     sub_401020
; [00000006 BYTES: COLLAPSED FUNCTION _floor]
; ---------------------------------------------------------------------------
                push    4
                jmp     sub_401020
; [00000006 BYTES: COLLAPSED FUNCTION ___isoc99_scanf]
; ---------------------------------------------------------------------------
                push    5
                jmp     sub_401020
; [00000006 BYTES: COLLAPSED FUNCTION _ceil]
; ---------------------------------------------------------------------------
                push    6
                jmp     sub_401020
; } // starts at 401020
_plt            ends

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
_text           segment para public 'CODE' use64
                assume cs:_text
                ;org 4010A0h
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B R O U T I N E =======================================

; Attributes: noreturn fuzzy-sp

                public start
start           proc near               ; DATA XREF: LOAD:0000000000400018↑o
; __unwind {
                endbr64
                xor     ebp, ebp
                mov     r9, rdx         ; rtld_fini
                pop     rsi             ; argc
                mov     rdx, rsp        ; ubp_av
                and     rsp, 0FFFFFFFFFFFFFFF0h
                push    rax
                push    rsp             ; stack_end
                xor     r8d, r8d        ; fini
                xor     ecx, ecx        ; init
                mov     rdi, offset main ; main
                call    cs:__libc_start_main_ptr
                hlt
; } // starts at 4010A0
start           endp

; ---------------------------------------------------------------------------
                align 10h
; __unwind {
                endbr64
                retn
; } // starts at 4010D0
; ---------------------------------------------------------------------------
                align 20h

; =============== S U B R O U T I N E =======================================


sub_4010E0      proc near               ; CODE XREF: sub_401150+11↓p
                mov     eax, offset byte_404048
                cmp     rax, offset byte_404048
                jz      short locret_401100
                mov     eax, 0
                test    rax, rax
                jz      short locret_401100
                mov     edi, offset byte_404048
                jmp     rax
; ---------------------------------------------------------------------------
                align 20h

locret_401100:                          ; CODE XREF: sub_4010E0+B↑j
                                        ; sub_4010E0+15↑j
                retn
sub_4010E0      endp

; ---------------------------------------------------------------------------
                align 10h
; START OF FUNCTION CHUNK FOR sub_401180

loc_401110:                             ; CODE XREF: sub_401180+4↓j
                mov     esi, offset byte_404048
                sub     rsi, offset byte_404048
                mov     rax, rsi
                shr     rsi, 3Fh
                sar     rax, 3
                add     rsi, rax
                sar     rsi, 1
                jz      short locret_401140
                mov     eax, 0
                test    rax, rax
                jz      short locret_401140
                mov     edi, offset byte_404048
                jmp     rax
; ---------------------------------------------------------------------------

locret_401140:                          ; CODE XREF: sub_401180-53↑j
                                        ; sub_401180-49↑j
                retn
; END OF FUNCTION CHUNK FOR sub_401180
; ---------------------------------------------------------------------------
                align 10h

; =============== S U B R O U T I N E =======================================


sub_401150      proc near               ; DATA XREF: .fini_array:0000000000403DF0↓o
                endbr64
                cmp     cs:byte_404048, 0
                jnz     short locret_401170
                push    rbp
                mov     rbp, rsp
                call    sub_4010E0
                mov     cs:byte_404048, 1
                pop     rbp
                retn
; ---------------------------------------------------------------------------
                align 10h

locret_401170:                          ; CODE XREF: sub_401150+B↑j
                retn
sub_401150      endp

; ---------------------------------------------------------------------------
                align 20h

; =============== S U B R O U T I N E =======================================


sub_401180      proc near               ; DATA XREF: .init_array:off_403DE8↓o

; FUNCTION CHUNK AT 0000000000401110 SIZE 00000031 BYTES

                endbr64
                jmp     short loc_401110
sub_401180      endp

; ---------------------------------------------------------------------------
                align 10h

; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

; int main(int, char **, char **)
main            proc near               ; DATA XREF: start+18↑o

var_41          = byte ptr -41h
s               = qword ptr -40h
var_38          = qword ptr -38h
var_28          = qword ptr -28h
var_20          = qword ptr -20h
var_18          = qword ptr -18h
var_10          = qword ptr -10h
var_4           = dword ptr -4

; __unwind {
                push    rbp
                mov     rbp, rsp
                sub     rsp, 50h
                mov     [rbp+var_4], 0
                xorps   xmm0, xmm0
                movsd   [rbp+var_10], xmm0
                xorps   xmm0, xmm0
                movsd   [rbp+var_18], xmm0
                xorps   xmm0, xmm0
                movsd   [rbp+var_20], xmm0
                xorps   xmm0, xmm0
                movsd   [rbp+var_28], xmm0
                lea     rdi, [rbp+s]    ; s
                xor     esi, esi        ; c
                mov     edx, 10h        ; n
                call    _memset
                movsd   xmm0, cs:qword_402008
                movsd   [rbp+var_20], xmm0
                mov     rdi, offset aLfLf ; "%lf,%lf"
                lea     rsi, [rbp+var_10]
                lea     rdx, [rbp+var_18]
                mov     al, 0
                call    ___isoc99_scanf

loc_4011F5:                             ; CODE XREF: main+11E↓j
                mov     al, 1
                xorps   xmm0, xmm0
                ucomisd xmm0, [rbp+var_10]
                mov     [rbp+var_41], al
                jnz     loc_401221
                jp      loc_401221
                xorps   xmm0, xmm0
                ucomisd xmm0, [rbp+var_18]
                setnz   al
                setp    cl
                or      al, cl
                mov     [rbp+var_41], al

loc_401221:                             ; CODE XREF: main+72↑j main+78↑j
                mov     al, [rbp+var_41]
                test    al, 1
                jnz     loc_401231
                jmp     loc_4012B3
; ---------------------------------------------------------------------------

loc_401231:                             ; CODE XREF: main+96↑j
                movsd   xmm0, [rbp+var_20]
                call    sub_4012D0
                movsd   [rbp+var_28], xmm0
                movsd   xmm0, [rbp+var_10]
                movsd   xmm1, [rbp+var_28]
                movsd   xmm2, [rbp+s]
                call    sub_401310
                movsd   [rbp+s], xmm0
                movsd   xmm0, [rbp+var_10]
                movsd   xmm1, [rbp+var_28]
                movsd   xmm2, [rbp+var_38]
                call    sub_401370
                movsd   [rbp+var_38], xmm0
                movsd   xmm1, [rbp+var_18]
                movsd   xmm0, [rbp+var_20]
                subsd   xmm0, xmm1
                movsd   [rbp+var_20], xmm0
                xorps   xmm0, xmm0
                movsd   [rbp+var_10], xmm0
                xorps   xmm0, xmm0
                movsd   [rbp+var_18], xmm0
                mov     rdi, offset aLfLf ; "%lf,%lf"
                lea     rsi, [rbp+var_10]
                lea     rdx, [rbp+var_18]
                mov     al, 0
                call    ___isoc99_scanf
                jmp     loc_4011F5
; ---------------------------------------------------------------------------

loc_4012B3:                             ; CODE XREF: main+9C↑j
                lea     rdi, [rbp+s]
                mov     esi, 2
                call    sub_4013D0
                xor     eax, eax
                add     rsp, 50h
                pop     rbp
                retn
; } // starts at 401190
main            endp

; ---------------------------------------------------------------------------
                align 10h

; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

sub_4012D0      proc near               ; CODE XREF: main+A6↑p

var_10          = qword ptr -10h
var_8           = qword ptr -8

; __unwind {
                push    rbp
                mov     rbp, rsp
                movsd   [rbp+var_8], xmm0
                xorps   xmm0, xmm0
                movsd   [rbp+var_10], xmm0
                movsd   xmm0, cs:qword_402018
                mulsd   xmm0, [rbp+var_8]
                movsd   xmm1, cs:qword_402010
                divsd   xmm0, xmm1
                movsd   [rbp+var_10], xmm0
                movsd   xmm0, [rbp+var_10]
                pop     rbp
                retn
; } // starts at 4012D0
sub_4012D0      endp

; ---------------------------------------------------------------------------
                align 10h

; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

sub_401310      proc near               ; CODE XREF: main+BF↑p

var_28          = qword ptr -28h
var_20          = qword ptr -20h
var_18          = qword ptr -18h
x               = qword ptr -10h
var_8           = qword ptr -8

; __unwind {
                push    rbp
                mov     rbp, rsp
                sub     rsp, 30h
                movsd   [rbp+var_8], xmm0
                movsd   [rbp+x], xmm1
                movsd   [rbp+var_18], xmm2
                xorps   xmm0, xmm0
                movsd   [rbp+var_20], xmm0
                movsd   xmm0, [rbp+var_8]
                movsd   [rbp+var_28], xmm0
                movsd   xmm0, [rbp+x]   ; x
                call    _cos
                movaps  xmm2, xmm0
                movsd   xmm0, [rbp+var_28]
                movsd   xmm1, [rbp+var_18]
                mulsd   xmm0, xmm2
                addsd   xmm0, xmm1
                movsd   [rbp+var_20], xmm0
                movsd   xmm0, [rbp+var_20]
                add     rsp, 30h
                pop     rbp
                retn
; } // starts at 401310
sub_401310      endp

; ---------------------------------------------------------------------------
                align 10h

; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

sub_401370      proc near               ; CODE XREF: main+D8↑p

var_28          = qword ptr -28h
var_20          = qword ptr -20h
var_18          = qword ptr -18h
x               = qword ptr -10h
var_8           = qword ptr -8

; __unwind {
                push    rbp
                mov     rbp, rsp
                sub     rsp, 30h
                movsd   [rbp+var_8], xmm0
                movsd   [rbp+x], xmm1
                movsd   [rbp+var_18], xmm2
                xorps   xmm0, xmm0
                movsd   [rbp+var_20], xmm0
                movsd   xmm0, [rbp+var_8]
                movsd   [rbp+var_28], xmm0
                movsd   xmm0, [rbp+x]   ; x
                call    _sin
                movaps  xmm2, xmm0
                movsd   xmm0, [rbp+var_28]
                movsd   xmm1, [rbp+var_18]
                mulsd   xmm0, xmm2
                addsd   xmm0, xmm1
                movsd   [rbp+var_20], xmm0
                movsd   xmm0, [rbp+var_20]
                add     rsp, 30h
                pop     rbp
                retn
; } // starts at 401370
sub_401370      endp

; ---------------------------------------------------------------------------
                align 10h

; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

sub_4013D0      proc near               ; CODE XREF: main+12C↑p

var_10          = dword ptr -10h
var_C           = dword ptr -0Ch
var_8           = qword ptr -8

; __unwind {
                push    rbp
                mov     rbp, rsp
                sub     rsp, 10h
                mov     [rbp+var_8], rdi
                mov     [rbp+var_C], esi
                mov     [rbp+var_10], 0
                mov     [rbp+var_10], 0

loc_4013ED:                             ; CODE XREF: sub_4013D0+B3↓j
                mov     eax, [rbp+var_10]
                cmp     eax, [rbp+var_C]
                jge     loc_401488
                mov     rax, [rbp+var_8]
                movsxd  rcx, [rbp+var_10]
                xorps   xmm0, xmm0
                ucomisd xmm0, qword ptr [rax+rcx*8]
                jbe     loc_401433
                mov     rax, [rbp+var_8]
                movsxd  rcx, [rbp+var_10]
                movsd   xmm0, qword ptr [rax+rcx*8] ; x
                call    _ceil
                mov     rax, [rbp+var_8]
                movsxd  rcx, [rbp+var_10]
                movsd   qword ptr [rax+rcx*8], xmm0
                jmp     loc_401452
; ---------------------------------------------------------------------------

loc_401433:                             ; CODE XREF: sub_4013D0+39↑j
                mov     rax, [rbp+var_8]
                movsxd  rcx, [rbp+var_10]
                movsd   xmm0, qword ptr [rax+rcx*8] ; x
                call    _floor
                mov     rax, [rbp+var_8]
                movsxd  rcx, [rbp+var_10]
                movsd   qword ptr [rax+rcx*8], xmm0

loc_401452:                             ; CODE XREF: sub_4013D0+5E↑j
                mov     rax, [rbp+var_8]
                movsxd  rcx, [rbp+var_10]
                movsd   xmm0, qword ptr [rax+rcx*8]
                mov     rdi, offset format ; "%.0lf\n"
                mov     al, 1
                call    _printf
                mov     eax, [rbp+var_10]
                add     eax, 2E50ECE9h
                add     eax, 1
                sub     eax, 2E50ECE9h
                mov     [rbp+var_10], eax
                jmp     loc_4013ED
; ---------------------------------------------------------------------------

loc_401488:                             ; CODE XREF: sub_4013D0+23↑j
                add     rsp, 10h
                pop     rbp
                retn
; } // starts at 4013D0
sub_4013D0      endp

_text           ends

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
LOAD            segment mempage public 'CODE' use64
                assume cs:LOAD
                ;org 40148Eh
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
                align 10h
LOAD            ends

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
_fini           segment dword public 'CODE' use64
                assume cs:_fini
                ;org 401490h
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B R O U T I N E =======================================


                public _term_proc
_term_proc      proc near
                endbr64
                sub     rsp, 8
                add     rsp, 8
                retn
_term_proc      endp

_fini           ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read
_rodata         segment qword public 'CONST' use64
                assume cs:_rodata
                ;org 402000h
qword_402000    dq 20001h               ; DATA XREF: LOAD:0000000000400130↑o
qword_402008    dq 4056800000000000h    ; DATA XREF: main+3F↑r
qword_402010    dq 4066800000000000h    ; DATA XREF: sub_4012D0+1E↑r
qword_402018    dq 400921FB54442D18h    ; DATA XREF: sub_4012D0+11↑r
aLfLf           db '%lf,%lf',0          ; DATA XREF: main+4C↑o main+105↑o
; const char format[]
format          db '%.0lf',0Ah,0        ; DATA XREF: sub_4013D0+8F↑o
_rodata         ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read
LOAD            segment mempage public 'DATA' use64
                assume cs:LOAD
                ;org 40202Fh
                align 10h
LOAD            ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read
_eh_frame_hdr   segment dword public 'CONST' use64
                assume cs:_eh_frame_hdr
                ;org 402030h
qword_402030    dq 4C3B031B01h, 0FFFFEFF000000008h, 0FFFFF07000000090h
                                        ; DATA XREF: LOAD:0000000000400280↑o
                dq 0FFFFF0A000000068h, 0FFFFF1600000007Ch, 0FFFFF2A0000000B8h
                dq 0FFFFF2E0000000D8h, 0FFFFF340000000F8h, 0FFFFF3A000000118h
                db 38h, 1, 2 dup(0)
_eh_frame_hdr   ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read
LOAD            segment mempage public 'DATA' use64
                assume cs:LOAD
                ;org 40207Ch
                align 20h
LOAD            ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read
_eh_frame       segment qword public 'CONST' use64
                assume cs:_eh_frame
                ;org 402080h
                dq 14h, 110780100527A01h, 19008070C1Bh, 1C00000010h, 26FFFFF000h
                dq 1010074400h, 0FFFFF01C00000030h, 5, 4400000024h, 80FFFFEF58h
                dq 0F4A180E46100E00h, 3B1A3F008008770Bh, 2224332Ah, 6C0000001Ch
                dq 139FFFFF0A0h, 0D430286100E4100h, 8070C01340306h, 8C0000001Ch
                dq 36FFFFF1C0h, 0D430286100E4100h, 8070C7106h, 0AC0000001Ch
                dq 58FFFFF1E0h, 0D430286100E4100h, 8070C530206h, 0CC0000001Ch
                dq 58FFFFF220h, 0D430286100E4100h, 8070C530206h, 0EC0000001Ch
                dq 0BEFFFFF260h, 0D430286100E4100h, 8070CB90206h
                db 4 dup(0)
_eh_frame       ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read
LOAD            segment mempage public 'DATA' use64
                assume cs:LOAD
                ;org 40218Ch
                align 10h
; ELF Note Entry
dword_402190    dd 4                    ; DATA XREF: LOAD:00000000004001D8↑o
                                        ; LOAD:0000000000400248↑o
                                        ; Name Size
                dd 10h                  ; Desc Size
                dd 5                    ; Type: NT_GNU_PROPERTY_TYPE_0
aGnu            db 'GNU',0              ; Name
                db 2, 80h, 0, 0C0h, 4, 3 dup(0), 1, 7 dup(0) ; Desc
; ELF Note Entry
dword_4021B0    dd 4                    ; DATA XREF: LOAD:0000000000400210↑o
                                        ; Name Size
                dd 10h                  ; Desc Size
                dd 1                    ; Type: NT_GNU_ABI_TAG
aGnu_0          db 'GNU',0              ; Name
                dd 0, 3, 2, 0           ; ABI: Linux 3.2.0
LOAD            ends

; ELF Initialization Function Table
; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read/Write
_init_array     segment qword public 'DATA' use64
                assume cs:_init_array
                ;org 403DE8h
off_403DE8      dq offset sub_401180    ; DATA XREF: LOAD:0000000000400168↑o
                                        ; LOAD:00000000004002F0↑o
_init_array     ends

; ELF Termination Function Table
; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read/Write
_fini_array     segment qword public 'DATA' use64
                assume cs:_fini_array
                ;org 403DF0h
                dq offset sub_401150
_fini_array     ends

; ELF Dynamic Information
; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read/Write
LOAD            segment mempage public 'DATA' use64
                assume cs:LOAD
                ;org 403DF8h
stru_403DF8     Elf64_Dyn <1, 52h>      ; DATA XREF: LOAD:00000000004001A0↑o
                                        ; .got.plt:0000000000403FE8↓o
                                        ; DT_NEEDED libm.so.6
                Elf64_Dyn <1, 5Ch>      ; DT_NEEDED libc.so.6
                Elf64_Dyn <0Ch, 401000h> ; DT_INIT
                Elf64_Dyn <0Dh, 401490h> ; DT_FINI
                Elf64_Dyn <19h, 403DE8h> ; DT_INIT_ARRAY
                Elf64_Dyn <1Bh, 8>      ; DT_INIT_ARRAYSZ
                Elf64_Dyn <1Ah, 403DF0h> ; DT_FINI_ARRAY
                Elf64_Dyn <1Ch, 8>      ; DT_FINI_ARRAYSZ
                Elf64_Dyn <6FFFFEF5h, 400338h> ; DT_GNU_HASH
                Elf64_Dyn <5, 400448h>  ; DT_STRTAB
                Elf64_Dyn <6, 400358h>  ; DT_SYMTAB
                Elf64_Dyn <0Ah, 87h>    ; DT_STRSZ
                Elf64_Dyn <0Bh, 18h>    ; DT_SYMENT
                Elf64_Dyn <15h, 0>      ; DT_DEBUG
                Elf64_Dyn <3, 403FE8h>  ; DT_PLTGOT
                Elf64_Dyn <2, 0A8h>     ; DT_PLTRELSZ
                Elf64_Dyn <14h, 7>      ; DT_PLTREL
                Elf64_Dyn <17h, 400578h> ; DT_JMPREL
                Elf64_Dyn <7, 400548h>  ; DT_RELA
                Elf64_Dyn <8, 30h>      ; DT_RELASZ
                Elf64_Dyn <9, 18h>      ; DT_RELAENT
                Elf64_Dyn <6FFFFFFEh, 4004E8h> ; DT_VERNEED
                Elf64_Dyn <6FFFFFFFh, 2> ; DT_VERNEEDNUM
                Elf64_Dyn <6FFFFFF0h, 4004D0h> ; DT_VERSYM
                Elf64_Dyn <0>           ; DT_NULL
                dq 0Ah dup(0)
LOAD            ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read/Write
_got            segment qword public 'DATA' use64
                assume cs:_got
                ;org 403FD8h
__libc_start_main_ptr dq offset __libc_start_main ; DATA XREF: start+1F↑r
__gmon_start___ptr dq offset __gmon_start__ ; DATA XREF: _init_proc+8↑r
_got            ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read/Write
_got_plt        segment qword public 'DATA' use64
                assume cs:_got_plt
                ;org 403FE8h
                dq offset stru_403DF8
qword_403FF0    dq 0                    ; DATA XREF: sub_401020↑r
qword_403FF8    dq 0                    ; DATA XREF: sub_401020+6↑r
off_404000      dq offset printf        ; DATA XREF: _printf↑r
off_404008      dq offset memset        ; DATA XREF: _memset↑r
off_404010      dq offset cos           ; DATA XREF: _cos↑r
off_404018      dq offset sin           ; DATA XREF: _sin↑r
off_404020      dq offset floor         ; DATA XREF: _floor↑r
off_404028      dq offset __isoc99_scanf ; DATA XREF: ___isoc99_scanf↑r
off_404030      dq offset ceil          ; DATA XREF: _ceil↑r
_got_plt        ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read/Write
_data           segment qword public 'DATA' use64
                assume cs:_data
                ;org 404038h
                dq 2 dup(0)
_data           ends

; ===========================================================================

; Segment type: Uninitialized
; Segment permissions: Read/Write
_bss            segment byte public 'BSS' use64
                assume cs:_bss
                ;org 404048h
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
byte_404048     db ?                    ; DATA XREF: sub_4010E0↑o sub_4010E0+5↑o ...
                align 10h
_bss            ends

; ===========================================================================

; Segment type: Externs
; extern
; int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end)
                extrn __libc_start_main:near ; CODE XREF: start+1F↑p
                                        ; DATA XREF: .got:__libc_start_main_ptr↑o
; int printf(const char *format, ...)
                extrn printf:near       ; CODE XREF: _printf↑j
                                        ; DATA XREF: .got.plt:off_404000↑o
; void *memset(void *s, int c, size_t n)
                extrn memset:near       ; CODE XREF: _memset↑j
                                        ; DATA XREF: .got.plt:off_404008↑o
; double cos(double x)
                extrn cos:near          ; CODE XREF: _cos↑j
                                        ; DATA XREF: .got.plt:off_404010↑o
; double sin(double x)
                extrn sin:near          ; CODE XREF: _sin↑j
                                        ; DATA XREF: .got.plt:off_404018↑o
; double floor(double x)
                extrn floor:near        ; CODE XREF: _floor↑j
                                        ; DATA XREF: .got.plt:off_404020↑o
                extrn __isoc99_scanf:near ; CODE XREF: ___isoc99_scanf↑j
                                        ; DATA XREF: .got.plt:off_404028↑o
; double ceil(double x)
                extrn ceil:near         ; CODE XREF: _ceil↑j
                                        ; DATA XREF: .got.plt:off_404030↑o
                extrn __gmon_start__:near ; weak ; CODE XREF: _init_proc+14↑p
                                        ; DATA XREF: .got:__gmon_start___ptr↑o


                end start
