/* This file was generated by the Hex-Rays decompiler version 9.3.0.260213.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
__int64 sub_401020(); // weak
// int printf(const char *format, ...);
// void *memset(void *s, int c, size_t n);
// __int64 __isoc99_scanf(const char *, ...); weak
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)());
char *sub_4010A0();
char *sub_401110();
__int64 sub_401140(); // weak
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN main;
__int64 (*qword_405FF8)(void) = NULL; // weak
char byte_406028; // weak
_UNKNOWN unk_40602C; // weak
_UNKNOWN unk_406030; // weak


//----- (0000000000401000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 406058: using guessed type __int64 _gmon_start__(void);

//----- (0000000000401020) ----------------------------------------------------
__int64 sub_401020()
{
  return qword_405FF8();
}
// 401020: using guessed type __int64 sub_401020();
// 405FF8: using guessed type __int64 (*qword_405FF8)(void);

//----- (0000000000401060) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)())
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, nullptr, nullptr, a3, &v5);
  __halt();
}
// 40106A: positive sp value 8 has been found
// 401071: variable 'v3' is possibly undefined

//----- (00000000004010A0) ----------------------------------------------------
char *sub_4010A0()
{
  return &byte_406028;
}
// 406028: using guessed type char byte_406028;

//----- (0000000000401110) ----------------------------------------------------
char *sub_401110()
{
  char *result; // rax

  if ( !byte_406028 )
  {
    result = sub_4010A0();
    byte_406028 = 1;
  }
  return result;
}
// 406028: using guessed type char byte_406028;

//----- (0000000000401140) ----------------------------------------------------
__int64 sub_401140()
{
  return 0;
}
// 401140: using guessed type __int64 sub_401140();

//----- (0000000000401150) ----------------------------------------------------
__int64 __fastcall main(int a1, char **a2, char **a3)
{
  int v3; // eax
  int v4; // eax
  int v5; // eax
  int v6; // eax
  int v7; // eax
  int v8; // eax
  int v9; // eax
  int v10; // eax
  int v11; // eax
  int v12; // eax
  char *v13; // rax
  char *v14; // rax
  char *v15; // rax
  char *v16; // rax
  int v17; // eax
  int v18; // eax
  int v19; // eax
  int v20; // eax
  int v21; // eax
  int v22; // eax
  int v23; // eax
  int v24; // eax
  int v25; // eax
  int v26; // eax
  int v27; // eax
  int v28; // eax
  int v29; // eax
  int v30; // eax
  int v31; // eax
  int v32; // eax
  int v33; // eax
  int v34; // eax
  int v35; // eax
  int v36; // eax
  int v37; // eax
  int v38; // eax
  int v39; // eax
  int v40; // eax
  int v41; // eax
  int v42; // eax
  int v43; // eax
  int v44; // eax
  int v45; // eax
  int v46; // eax
  int v47; // eax
  int v48; // eax
  int v49; // eax
  int v50; // eax
  int v51; // eax
  __int64 *v53; // rax
  __int64 *v54; // rsi
  __int64 v55; // [rsp+0h] [rbp-C0h] BYREF
  __int64 *v56; // [rsp+8h] [rbp-B8h]
  __int64 *v57; // [rsp+10h] [rbp-B0h]
  __int64 *v58; // [rsp+18h] [rbp-A8h]
  int v59; // [rsp+24h] [rbp-9Ch]
  int v60; // [rsp+28h] [rbp-98h]
  bool v61; // [rsp+2Eh] [rbp-92h]
  bool v62; // [rsp+2Fh] [rbp-91h]
  int *v63; // [rsp+30h] [rbp-90h]
  __int64 *v64; // [rsp+38h] [rbp-88h]
  __int64 *v65; // [rsp+40h] [rbp-80h]
  __int64 *v66; // [rsp+48h] [rbp-78h]
  __int64 *v67; // [rsp+50h] [rbp-70h]
  __int64 *v68; // [rsp+58h] [rbp-68h]
  int *v69; // [rsp+60h] [rbp-60h]
  int *v70; // [rsp+68h] [rbp-58h]
  int *v71; // [rsp+70h] [rbp-50h]
  __int64 *v72; // [rsp+78h] [rbp-48h]
  __int64 *v73; // [rsp+80h] [rbp-40h]
  __int64 *v74; // [rsp+88h] [rbp-38h]
  void *s; // [rsp+90h] [rbp-30h]
  int *v76; // [rsp+98h] [rbp-28h]
  int *v77; // [rsp+A0h] [rbp-20h]
  __int64 *v78; // [rsp+A8h] [rbp-18h]
  __int64 *v79; // [rsp+B0h] [rbp-10h]
  bool v80; // [rsp+BBh] [rbp-5h]
  bool v81; // [rsp+BCh] [rbp-4h]
  bool v82; // [rsp+BDh] [rbp-3h]
  bool v83; // [rsp+BEh] [rbp-2h]
  bool v84; // [rsp+BFh] [rbp-1h]

  v61 = (((unk_40602C - 1) * unk_40602C) & 1) == 0;
  v62 = unk_406030 < 10;
  v60 = -133646008;
  do
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( 1 )
        {
          while ( 1 )
          {
            while ( 1 )
            {
              while ( 1 )
              {
                while ( 1 )
                {
                  while ( 1 )
                  {
                    while ( 1 )
                    {
                      while ( 1 )
                      {
                        while ( 1 )
                        {
                          while ( 1 )
                          {
                            while ( 1 )
                            {
                              while ( 1 )
                              {
                                while ( 1 )
                                {
                                  while ( 1 )
                                  {
                                    while ( 1 )
                                    {
                                      while ( 1 )
                                      {
                                        while ( 1 )
                                        {
                                          while ( 1 )
                                          {
                                            while ( 1 )
                                            {
                                              while ( 1 )
                                              {
                                                while ( 1 )
                                                {
                                                  while ( 1 )
                                                  {
                                                    while ( 1 )
                                                    {
                                                      while ( 1 )
                                                      {
                                                        while ( 1 )
                                                        {
                                                          while ( 1 )
                                                          {
                                                            while ( 1 )
                                                            {
                                                              while ( 1 )
                                                              {
                                                                while ( 1 )
                                                                {
                                                                  while ( 1 )
                                                                  {
                                                                    while ( 1 )
                                                                    {
                                                                      while ( 1 )
                                                                      {
                                                                        while ( 1 )
                                                                        {
                                                                          while ( 1 )
                                                                          {
                                                                            while ( 1 )
                                                                            {
                                                                              while ( 1 )
                                                                              {
                                                                                while ( 1 )
                                                                                {
                                                                                  while ( 1 )
                                                                                  {
                                                                                    while ( 1 )
                                                                                    {
                                                                                      while ( 1 )
                                                                                      {
                                                                                        while ( 1 )
                                                                                        {
                                                                                          while ( 1 )
                                                                                          {
                                                                                            while ( 1 )
                                                                                            {
                                                                                              while ( 1 )
                                                                                              {
                                                                                                while ( 1 )
                                                                                                {
                                                                                                  while ( 1 )
                                                                                                  {
                                                                                                    while ( 1 )
                                                                                                    {
                                                                                                      while ( 1 )
                                                                                                      {
                                                                                                        while ( 1 )
                                                                                                        {
                                                                                                          while ( 1 )
                                                                                                          {
                                                                                                            while ( 1 )
                                                                                                            {
                                                                                                              while ( 1 )
                                                                                                              {
                                                                                                                while ( 1 )
                                                                                                                {
                                                                                                                  while ( 1 )
                                                                                                                  {
                                                                                                                    while ( 1 )
                                                                                                                    {
                                                                                                                      while ( 1 )
                                                                                                                      {
                                                                                                                        while ( 1 )
                                                                                                                        {
                                                                                                                          while ( 1 )
                                                                                                                          {
                                                                                                                            while ( 1 )
                                                                                                                            {
                                                                                                                              while ( 1 )
                                                                                                                              {
                                                                                                                                while ( 1 )
                                                                                                                                {
                                                                                                                                  while ( 1 )
                                                                                                                                  {
                                                                                                                                    while ( 1 )
                                                                                                                                    {
                                                                                                                                      while ( 1 )
                                                                                                                                      {
                                                                                                                                        while ( 1 )
                                                                                                                                        {
                                                                                                                                          while ( 1 )
                                                                                                                                          {
                                                                                                                                            while ( 1 )
                                                                                                                                            {
                                                                                                                                              while ( 1 )
                                                                                                                                              {
                                                                                                                                                while ( 1 )
                                                                                                                                                {
                                                                                                                                                  while ( 1 )
                                                                                                                                                  {
                                                                                                                                                    while ( 1 )
                                                                                                                                                    {
                                                                                                                                                      while ( 1 )
                                                                                                                                                      {
                                                                                                                                                        while ( 1 )
                                                                                                                                                        {
                                                                                                                                                          while ( 1 )
                                                                                                                                                          {
                                                                                                                                                            while ( 1 )
                                                                                                                                                            {
                                                                                                                                                              while ( 1 )
                                                                                                                                                              {
                                                                                                                                                                while ( 1 )
                                                                                                                                                                {
                                                                                                                                                                  while ( 1 )
                                                                                                                                                                  {
                                                                                                                                                                    while ( 1 )
                                                                                                                                                                    {
                                                                                                                                                                      while ( 1 )
                                                                                                                                                                      {
                                                                                                                                                                        while ( 1 )
                                                                                                                                                                        {
                                                                                                                                                                          while ( 1 )
                                                                                                                                                                          {
                                                                                                                                                                            while ( 1 )
                                                                                                                                                                            {
                                                                                                                                                                              while ( 1 )
                                                                                                                                                                              {
                                                                                                                                                                                while ( 1 )
                                                                                                                                                                                {
                                                                                                                                                                                  v59 = v60;
                                                                                                                                                                                  if ( v60 != -2084067327 )
                                                                                                                                                                                    break;
                                                                                                                                                                                  *v69 = 0;
                                                                                                                                                                                  v60 = 292725771;
                                                                                                                                                                                }
                                                                                                                                                                                if ( v59 != -2045905542 )
                                                                                                                                                                                  break;
                                                                                                                                                                                v12 = -2084067327;
                                                                                                                                                                                if ( v80 )
                                                                                                                                                                                  v12 = 1448726913;
                                                                                                                                                                                v60 = v12;
                                                                                                                                                                              }
                                                                                                                                                                              if ( v59 != -1997311128 )
                                                                                                                                                                                break;
                                                                                                                                                                              *(_DWORD *)v67 -= *(_DWORD *)v74;
                                                                                                                                                                              printf("%d\n", *(_DWORD *)v67);
                                                                                                                                                                              __isoc99_scanf("%d", v63);
                                                                                                                                                                              *(_DWORD *)v74 = 0;
                                                                                                                                                                              *v76 = 0;
                                                                                                                                                                              *v77 = 0;
                                                                                                                                                                              *(_DWORD *)v67 = 0;
                                                                                                                                                                              v60 = -787736163;
                                                                                                                                                                            }
                                                                                                                                                                            if ( v59 != -1980003658 )
                                                                                                                                                                              break;
                                                                                                                                                                            *(_DWORD *)v67 -= *((_DWORD *)v79 + 23 * *v69 + 20);
                                                                                                                                                                            v26 = -815473137;
                                                                                                                                                                            if ( (unk_406030 < 10) ^ ((((unk_40602C - 21 + 20) * unk_40602C) & 1) == 0) | (unk_406030 < 10 && (((unk_40602C - 21 + 20) * unk_40602C) & 1) == 0) )
                                                                                                                                                                              v26 = -325670137;
                                                                                                                                                                            v60 = v26;
                                                                                                                                                                          }
                                                                                                                                                                          if ( v59 != -1833928960 )
                                                                                                                                                                            break;
                                                                                                                                                                          ++*(_DWORD *)v72;
                                                                                                                                                                          v9 = 1640645770;
                                                                                                                                                                          if ( (unk_406030 < 10) ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0) | (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0) )
                                                                                                                                                                            v9 = 1130767922;
                                                                                                                                                                          v60 = v9;
                                                                                                                                                                        }
                                                                                                                                                                        if ( v59 != -1827269235 )
                                                                                                                                                                          break;
                                                                                                                                                                        v60 = 817331749;
                                                                                                                                                                      }
                                                                                                                                                                      if ( v59 != -1797107743 )
                                                                                                                                                                        break;
                                                                                                                                                                      v60 = -124461693;
                                                                                                                                                                    }
                                                                                                                                                                    if ( v59 != -1776776920 )
                                                                                                                                                                      break;
                                                                                                                                                                    v35 = 817331749;
                                                                                                                                                                    if ( v83 )
                                                                                                                                                                      v35 = -190225936;
                                                                                                                                                                    v60 = v35;
                                                                                                                                                                  }
                                                                                                                                                                  if ( v59 != -1650990996 )
                                                                                                                                                                    break;
                                                                                                                                                                  v25 = -815473137;
                                                                                                                                                                  if ( (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0) | (unk_406030 < 10) ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0) )
                                                                                                                                                                    v25 = -1980003658;
                                                                                                                                                                  v60 = v25;
                                                                                                                                                                }
                                                                                                                                                                if ( v59 != -1604744986 )
                                                                                                                                                                  break;
                                                                                                                                                                *(_DWORD *)v73 = 0;
                                                                                                                                                                v60 = 1720322304;
                                                                                                                                                              }
                                                                                                                                                              if ( v59 != -1594647106 )
                                                                                                                                                                break;
                                                                                                                                                              v60 = 1395594262;
                                                                                                                                                            }
                                                                                                                                                            if ( v59 != -1561894986 )
                                                                                                                                                              break;
                                                                                                                                                            v40 = 817331749;
                                                                                                                                                            if ( v84 )
                                                                                                                                                              v40 = -1443446007;
                                                                                                                                                            v60 = v40;
                                                                                                                                                          }
                                                                                                                                                          if ( v59 != -1448447936 )
                                                                                                                                                            break;
                                                                                                                                                          v30 = 1255321064;
                                                                                                                                                          if ( (unk_406030 < 10) ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0) | (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0) )
                                                                                                                                                            v30 = 410412540;
                                                                                                                                                          v60 = v30;
                                                                                                                                                        }
                                                                                                                                                        if ( v59 != -1443446007 )
                                                                                                                                                          break;
                                                                                                                                                        v41 = 850857385;
                                                                                                                                                        if ( (unk_406030 < 10) ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0) | (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0) )
                                                                                                                                                          v41 = -981814073;
                                                                                                                                                        v60 = v41;
                                                                                                                                                      }
                                                                                                                                                      if ( v59 != -1324612325 )
                                                                                                                                                        break;
                                                                                                                                                      v10 = -525867394;
                                                                                                                                                      if ( (unk_406030 < 10) ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0) | (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0) )
                                                                                                                                                        v10 = 135160421;
                                                                                                                                                      v60 = v10;
                                                                                                                                                    }
                                                                                                                                                    if ( v59 != -1231926658 )
                                                                                                                                                      break;
                                                                                                                                                    v45 = 881525933;
                                                                                                                                                    if ( *((_DWORD *)v79 + 23 * *v71 + 22) > *(_DWORD *)v74 )
                                                                                                                                                      v45 = 1931058174;
                                                                                                                                                    v60 = v45;
                                                                                                                                                  }
                                                                                                                                                  if ( v59 != -1146001860 )
                                                                                                                                                    break;
                                                                                                                                                  --*v77;
                                                                                                                                                  v60 = 1130102563;
                                                                                                                                                }
                                                                                                                                                if ( v59 != -1112165473 )
                                                                                                                                                  break;
                                                                                                                                                v60 = -981794591;
                                                                                                                                              }
                                                                                                                                              if ( v59 != -1071029506 )
                                                                                                                                                break;
                                                                                                                                              ++*(_DWORD *)v68;
                                                                                                                                              v60 = -1324612325;
                                                                                                                                            }
                                                                                                                                            if ( v59 != -1048082117 )
                                                                                                                                              break;
                                                                                                                                            *(_DWORD *)v68 = 0;
                                                                                                                                            v60 = -1324612325;
                                                                                                                                          }
                                                                                                                                          if ( v59 != -1013691792 )
                                                                                                                                            break;
                                                                                                                                          v60 = 1972150270;
                                                                                                                                        }
                                                                                                                                        if ( v59 != -981814073 )
                                                                                                                                          break;
                                                                                                                                        *((_DWORD *)v79 + 23 * *v70 + 22) = *((_DWORD *)v79 + 23 * *((int *)s + *v76) + 22) + *((_DWORD *)v79 + 23 * *((int *)s + *v76) + *v70);
                                                                                                                                        *((_DWORD *)s + ++*v77) = *v70;
                                                                                                                                        ++*(_DWORD *)v78;
                                                                                                                                        v42 = 850857385;
                                                                                                                                        if ( (unk_406030 < 10) ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0) | (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0) )
                                                                                                                                          v42 = -1827269235;
                                                                                                                                        v60 = v42;
                                                                                                                                      }
                                                                                                                                      if ( v59 != -981794591 )
                                                                                                                                        break;
                                                                                                                                      v83 = *((_DWORD *)v79 + 23 * *((int *)s + *v76) + *v70) > 0;
                                                                                                                                      v34 = -1112165473;
                                                                                                                                      if ( (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0) | (unk_406030 < 10) ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0) )
                                                                                                                                        v34 = -1776776920;
                                                                                                                                      v60 = v34;
                                                                                                                                    }
                                                                                                                                    if ( v59 != -870655145 )
                                                                                                                                      break;
                                                                                                                                    v24 = 204959625;
                                                                                                                                    if ( *((_DWORD *)v79 + 23 * *v69 + 21) == 1 )
                                                                                                                                      v24 = -1650990996;
                                                                                                                                    v60 = v24;
                                                                                                                                  }
                                                                                                                                  if ( v59 != -870626633 )
                                                                                                                                    break;
                                                                                                                                  v19 = -47814801;
                                                                                                                                  if ( v81 )
                                                                                                                                    v19 = 939378666;
                                                                                                                                  v60 = v19;
                                                                                                                                }
                                                                                                                                if ( v59 != -826348925 )
                                                                                                                                  break;
                                                                                                                                v32 = 1188580436;
                                                                                                                                if ( v82 )
                                                                                                                                  v32 = 239264145;
                                                                                                                                v60 = v32;
                                                                                                                              }
                                                                                                                              if ( v59 != -815473137 )
                                                                                                                                break;
                                                                                                                              *(_DWORD *)v67 -= *((_DWORD *)v79 + 23 * *v69 + 20);
                                                                                                                              v60 = -1980003658;
                                                                                                                            }
                                                                                                                            if ( v59 != -787736163 )
                                                                                                                              break;
                                                                                                                            *(_DWORD *)v67 -= *(_DWORD *)v74;
                                                                                                                            printf("%d\n", *(_DWORD *)v67);
                                                                                                                            __isoc99_scanf("%d", v63);
                                                                                                                            *(_DWORD *)v74 = 0;
                                                                                                                            *v76 = 0;
                                                                                                                            *v77 = 0;
                                                                                                                            *(_DWORD *)v67 = 0;
                                                                                                                            v49 = -1997311128;
                                                                                                                            if ( (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0) | (unk_406030 < 10) ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0) )
                                                                                                                              v49 = -539861189;
                                                                                                                            v60 = v49;
                                                                                                                          }
                                                                                                                          if ( v59 != -734820376 )
                                                                                                                            break;
                                                                                                                          ++*v70;
                                                                                                                          v60 = -1448447936;
                                                                                                                        }
                                                                                                                        if ( v59 != -675304887 )
                                                                                                                          break;
                                                                                                                        v5 = -534473472;
                                                                                                                        if ( *v63 > 0 )
                                                                                                                          v5 = 1113363915;
                                                                                                                        v60 = v5;
                                                                                                                      }
                                                                                                                      if ( v59 != -539861189 )
                                                                                                                        break;
                                                                                                                      v60 = -675304887;
                                                                                                                    }
                                                                                                                    if ( v59 != -534473472 )
                                                                                                                      break;
                                                                                                                    v50 = -1594647106;
                                                                                                                    if ( (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0) | (unk_406030 < 10) ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0) )
                                                                                                                      v50 = 1395594262;
                                                                                                                    v60 = v50;
                                                                                                                  }
                                                                                                                  if ( v59 != -525867394 )
                                                                                                                    break;
                                                                                                                  v60 = 135160421;
                                                                                                                }
                                                                                                                if ( v59 != -389323848 )
                                                                                                                  break;
                                                                                                                *v71 = 0;
                                                                                                                v60 = 1419121445;
                                                                                                              }
                                                                                                              if ( v59 != -357191112 )
                                                                                                                break;
                                                                                                              v84 = *v70 > 0;
                                                                                                              v39 = 1871499774;
                                                                                                              if ( (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0) | (unk_406030 < 10) ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0) )
                                                                                                                v39 = -1561894986;
                                                                                                              v60 = v39;
                                                                                                            }
                                                                                                            if ( v59 != -325670137 )
                                                                                                              break;
                                                                                                            v60 = 204959625;
                                                                                                          }
                                                                                                          if ( v59 != -322380090 )
                                                                                                            break;
                                                                                                          *(_DWORD *)v67 += *((_DWORD *)v79 + 23 * *v69 + 20);
                                                                                                          v23 = 1402433113;
                                                                                                          if ( (unk_406030 < 10) ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0) | (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0) )
                                                                                                            v23 = -1013691792;
                                                                                                          v60 = v23;
                                                                                                        }
                                                                                                        if ( v59 != -190225936 )
                                                                                                          break;
                                                                                                        v36 = 817331749;
                                                                                                        if ( *((int *)v79 + 23 * *v70 + 21) >= 2 )
                                                                                                          v36 = 1478388514;
                                                                                                        v60 = v36;
                                                                                                      }
                                                                                                      if ( v59 != -133646008 )
                                                                                                        break;
                                                                                                      v3 = 1477896442;
                                                                                                      if ( (v62 && v61) | v62 ^ v61 )
                                                                                                        v3 = 1009057083;
                                                                                                      v60 = v3;
                                                                                                    }
                                                                                                    if ( v59 != -124461693 )
                                                                                                      break;
                                                                                                    v28 = -1797107743;
                                                                                                    if ( (unk_406030 < 10) ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0) | (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0) )
                                                                                                      v28 = 329691358;
                                                                                                    v60 = v28;
                                                                                                  }
                                                                                                  if ( v59 != -47814801 )
                                                                                                    break;
                                                                                                  v60 = 923133321;
                                                                                                }
                                                                                                if ( v59 != -44748112 )
                                                                                                  break;
                                                                                                v38 = 1871499774;
                                                                                                if ( (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0) | ((unsigned __int8)~(unk_406030 < 10) ^ (unsigned __int8)~((((unk_40602C - 1) * unk_40602C) & 1) == 0)) & 1 )
                                                                                                  v38 = -357191112;
                                                                                                v60 = v38;
                                                                                              }
                                                                                              if ( v59 != 17838557 )
                                                                                                break;
                                                                                              v60 = -675304887;
                                                                                            }
                                                                                            if ( v59 != 34758751 )
                                                                                              break;
                                                                                            *((_DWORD *)v79
                                                                                            + 23 * *(int *)v72
                                                                                            + *(int *)v73) = 0;
                                                                                            v60 = 2002520572;
                                                                                          }
                                                                                          if ( v59 != 135160421 )
                                                                                            break;
                                                                                          v80 = *(_DWORD *)v68 < *v63 - 1;
                                                                                          v11 = -525867394;
                                                                                          if ( (unk_406030 < 10
                                                                                             && (((unk_40602C - 1)
                                                                                                * unk_40602C)
                                                                                               & 1) == 0)
                                                                                             | (unk_406030 < 10)
                                                                                             ^ ((((unk_40602C - 1)
                                                                                                * unk_40602C)
                                                                                               & 1) == 0) )
                                                                                          {
                                                                                            v11 = -2045905542;
                                                                                          }
                                                                                          v60 = v11;
                                                                                        }
                                                                                        if ( v59 != 204959625 )
                                                                                          break;
                                                                                        v60 = 1972150270;
                                                                                      }
                                                                                      if ( v59 != 239264145 )
                                                                                        break;
                                                                                      v33 = -1112165473;
                                                                                      if ( (unk_406030 < 10
                                                                                         && (((unk_40602C - 1)
                                                                                            * unk_40602C)
                                                                                           & 1) == 0)
                                                                                         | ((unsigned __int8)~(unk_406030 < 10)
                                                                                          ^ (unsigned __int8)~((((unk_40602C - 1) * unk_40602C) & 1) == 0))
                                                                                         & 1 )
                                                                                      {
                                                                                        v33 = -981794591;
                                                                                      }
                                                                                      v60 = v33;
                                                                                    }
                                                                                    if ( v59 != 265325195 )
                                                                                      break;
                                                                                    v60 = 1943828167;
                                                                                  }
                                                                                  if ( v59 != 292725771 )
                                                                                    break;
                                                                                  v17 = 1391889282;
                                                                                  if ( (unk_406030 < 10
                                                                                     && (((unk_40602C - 111 + 110)
                                                                                        * unk_40602C)
                                                                                       & 1) == 0)
                                                                                     | ((unsigned __int8)~(unk_406030 < 10)
                                                                                      ^ (unsigned __int8)~((((unk_40602C - 111 + 110) * unk_40602C) & 1) == 0))
                                                                                     & 1 )
                                                                                  {
                                                                                    v17 = 1375938533;
                                                                                  }
                                                                                  v60 = v17;
                                                                                }
                                                                                if ( v59 != 329691358 )
                                                                                  break;
                                                                                v60 = 1430813966;
                                                                              }
                                                                              if ( v59 != 353450044 )
                                                                                break;
                                                                              ++*v71;
                                                                              v60 = 528936226;
                                                                            }
                                                                            if ( v59 != 410412540 )
                                                                              break;
                                                                            v82 = *v70 < *v63;
                                                                            v31 = 1255321064;
                                                                            if ( (unk_406030 < 10)
                                                                               ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0)
                                                                               | (unk_406030 < 10
                                                                               && (((unk_40602C - 1) * unk_40602C) & 1) == 0) )
                                                                            {
                                                                              v31 = -826348925;
                                                                            }
                                                                            v60 = v31;
                                                                          }
                                                                          if ( v59 != 524716358 )
                                                                            break;
                                                                          v6 = -1048082117;
                                                                          if ( *(int *)v72 < 20 )
                                                                            v6 = -1604744986;
                                                                          v60 = v6;
                                                                        }
                                                                        if ( v59 != 528936226 )
                                                                          break;
                                                                        ++*v71;
                                                                        v47 = 353450044;
                                                                        if ( (unk_406030 < 10
                                                                           && (((unk_40602C - 1) * unk_40602C) & 1) == 0)
                                                                           | ((unsigned __int8)~(unk_406030 < 10)
                                                                            ^ (unsigned __int8)~((((unk_40602C - 1)
                                                                                                 * unk_40602C)
                                                                                                & 1) == 0))
                                                                           & 1 )
                                                                        {
                                                                          v47 = 697339087;
                                                                        }
                                                                        v60 = v47;
                                                                      }
                                                                      if ( v59 != 697339087 )
                                                                        break;
                                                                      v60 = 1419121445;
                                                                    }
                                                                    if ( v59 != 817331749 )
                                                                      break;
                                                                    v60 = -734820376;
                                                                  }
                                                                  if ( v59 != 850857385 )
                                                                    break;
                                                                  *((_DWORD *)v79 + 23 * *v70 + 22) = *((_DWORD *)v79 + 23 * *((int *)s + *v76) + 22) + *((_DWORD *)v79 + 23 * *((int *)s + *v76) + *v70);
                                                                  *((_DWORD *)s + ++*v77) = *v70;
                                                                  ++*(_DWORD *)v78;
                                                                  v60 = -981814073;
                                                                }
                                                                if ( v59 != 881525933 )
                                                                  break;
                                                                v60 = 1190582112;
                                                              }
                                                              if ( v59 != 923133321 )
                                                                break;
                                                              v29 = -389323848;
                                                              if ( *v76 >= 0 )
                                                                v29 = 1457373990;
                                                              v60 = v29;
                                                            }
                                                            if ( v59 != 939378666 )
                                                              break;
                                                            v20 = 1578871506;
                                                            if ( *((int *)v79 + 23 * *v69 + 21) >= 2 )
                                                              v20 = 1459601619;
                                                            v60 = v20;
                                                          }
                                                          if ( v59 != 1009057083 )
                                                            break;
                                                          v63 = (int *)(&v55 - 2);
                                                          v64 = &v55 - 2;
                                                          v65 = &v55 - 2;
                                                          v66 = &v55 - 2;
                                                          v67 = &v55 - 2;
                                                          v68 = &v55 - 2;
                                                          v69 = (int *)(&v55 - 2);
                                                          v70 = (int *)(&v55 - 2);
                                                          v71 = (int *)(&v55 - 2);
                                                          v72 = &v55 - 2;
                                                          v73 = &v55 - 2;
                                                          v74 = &v55 - 2;
                                                          s = &v55 - 10;
                                                          v76 = (int *)(&v55 - 2);
                                                          v77 = (int *)(&v55 - 2);
                                                          v78 = &v55 - 2;
                                                          v79 = &v55 - 230;
                                                          *((_DWORD *)&v55 - 4) = 0;
                                                          *(_DWORD *)v67 = 0;
                                                          *(_DWORD *)v74 = 0;
                                                          memset(s, 0, 0x50u);
                                                          *v76 = 0;
                                                          *v77 = 0;
                                                          __isoc99_scanf("%d", v63);
                                                          v4 = 1477896442;
                                                          if ( (unk_406030 < 10)
                                                             ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0)
                                                             | (unk_406030 < 10
                                                             && (((unk_40602C - 1) * unk_40602C) & 1) == 0) )
                                                          {
                                                            v4 = 17838557;
                                                          }
                                                          v60 = v4;
                                                        }
                                                        if ( v59 != 1113363915 )
                                                          break;
                                                        *(_DWORD *)v72 = 0;
                                                        v60 = 524716358;
                                                      }
                                                      if ( v59 != 1130102563 )
                                                        break;
                                                      *v76 = *v77;
                                                      v60 = 923133321;
                                                    }
                                                    if ( v59 != 1130767922 )
                                                      break;
                                                    v60 = 524716358;
                                                  }
                                                  if ( v59 != 1188580436 )
                                                    break;
                                                  v43 = 1130102563;
                                                  if ( !*(_DWORD *)v78 )
                                                    v43 = -1146001860;
                                                  v60 = v43;
                                                }
                                                if ( v59 != 1190582112 )
                                                  break;
                                                v46 = 353450044;
                                                if ( (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0)
                                                   | (unk_406030 < 10) ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0) )
                                                {
                                                  v46 = 528936226;
                                                }
                                                v60 = v46;
                                              }
                                              if ( v59 != 1255321064 )
                                                break;
                                              v60 = 410412540;
                                            }
                                            if ( v59 != 1375938533 )
                                              break;
                                            v81 = *v69 < *v63;
                                            v18 = 1391889282;
                                            if ( (unk_406030 < 10) ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0)
                                               | (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0) )
                                            {
                                              v18 = -870626633;
                                            }
                                            v60 = v18;
                                          }
                                          if ( v59 != 1391889282 )
                                            break;
                                          v60 = 1375938533;
                                        }
                                        if ( v59 != 1395594262 )
                                          break;
                                        v51 = -1594647106;
                                        if ( (unk_406030 < 10) ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0)
                                           | (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0) )
                                        {
                                          v51 = 2106838288;
                                        }
                                        v60 = v51;
                                      }
                                      if ( v59 != 1402433113 )
                                        break;
                                      *(_DWORD *)v67 += *((_DWORD *)v79 + 23 * *v69 + 20);
                                      v60 = -322380090;
                                    }
                                    if ( v59 != 1419121445 )
                                      break;
                                    v44 = 1569912168;
                                    if ( *v71 < *v63 )
                                      v44 = -1231926658;
                                    v60 = v44;
                                  }
                                  if ( v59 != 1430813966 )
                                    break;
                                  ++*v69;
                                  v60 = 292725771;
                                }
                                if ( v59 != 1448726913 )
                                  break;
                                __isoc99_scanf("%d %d %d", v64, v65, v66);
                                *((_DWORD *)v79 + 23 * *(_DWORD *)v64 + *(_DWORD *)v65 - 24) = *(_DWORD *)v66;
                                v13 = (char *)v79 + 92 * *(_DWORD *)v64 - 92;
                                *((_DWORD *)v13 + 20) += *(_DWORD *)v66;
                                v14 = (char *)v79 + 92 * *(_DWORD *)v64 - 92;
                                ++*((_DWORD *)v14 + 21);
                                *((_DWORD *)v79 + 23 * *(_DWORD *)v65 + *(_DWORD *)v64 - 24) = *(_DWORD *)v66;
                                v15 = (char *)v79 + 92 * *(_DWORD *)v65 - 92;
                                *((_DWORD *)v15 + 20) += *(_DWORD *)v66;
                                v16 = (char *)v79 + 92 * *(_DWORD *)v65 - 92;
                                ++*((_DWORD *)v16 + 21);
                                v60 = -1071029506;
                              }
                              if ( v59 != 1457373990 )
                                break;
                              *(_DWORD *)v78 = 0;
                              *v70 = 0;
                              v60 = -1448447936;
                            }
                            if ( v59 != 1459601619 )
                              break;
                            v22 = 1402433113;
                            if ( (unk_406030 < 10 && (((unk_40602C - 127 + 126) * unk_40602C) & 1) == 0)
                               | (unk_406030 < 10) ^ ((((unk_40602C - 127 + 126) * unk_40602C) & 1) == 0) )
                            {
                              v22 = -322380090;
                            }
                            v60 = v22;
                          }
                          if ( v59 != 1477896442 )
                            break;
                          v58 = &v55 - 2;
                          v56 = &v55 - 2;
                          v57 = &v55 - 2;
                          *((_DWORD *)&v55 - 4) = 0;
                          *((_DWORD *)&v55 - 4) = 0;
                          *((_DWORD *)&v55 - 4) = 0;
                          memset(&v55 - 10, 0, 0x50u);
                          v53 = v57;
                          v54 = v58;
                          *(_DWORD *)v56 = 0;
                          *(_DWORD *)v53 = 0;
                          __isoc99_scanf("%d", v54);
                          v60 = 1009057083;
                        }
                        if ( v59 != 1478388514 )
                          break;
                        v37 = 817331749;
                        if ( !*((_DWORD *)v79 + 23 * *v70 + 22) )
                          v37 = -44748112;
                        v60 = v37;
                      }
                      if ( v59 != 1569912168 )
                        break;
                      v48 = -1997311128;
                      if ( (unk_406030 < 10) ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0)
                         | (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0) )
                      {
                        v48 = -787736163;
                      }
                      v60 = v48;
                    }
                    if ( v59 != 1578871506 )
                      break;
                    v21 = -870655145;
                    if ( !*v69 )
                      v21 = 1459601619;
                    v60 = v21;
                  }
                  if ( v59 != 1640645770 )
                    break;
                  ++*(_DWORD *)v72;
                  v60 = -1833928960;
                }
                if ( v59 != 1720322304 )
                  break;
                v7 = 265325195;
                if ( *(int *)v73 < 23 )
                  v7 = 34758751;
                v60 = v7;
              }
              if ( v59 != 1871499774 )
                break;
              v60 = -357191112;
            }
            if ( v59 != 1931058174 )
              break;
            *(_DWORD *)v74 = *((_DWORD *)v79 + 23 * *v71 + 22);
            v60 = 881525933;
          }
          if ( v59 != 1943828167 )
            break;
          v8 = 1640645770;
          if ( (unk_406030 < 10) ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0)
             | (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0) )
          {
            v8 = -1833928960;
          }
          v60 = v8;
        }
        if ( v59 != 1972150270 )
          break;
        v27 = -1797107743;
        if ( (unk_406030 < 10 && (((unk_40602C - 1) * unk_40602C) & 1) == 0)
           | (unk_406030 < 10) ^ ((((unk_40602C - 1) * unk_40602C) & 1) == 0) )
        {
          v27 = -124461693;
        }
        v60 = v27;
      }
      if ( v59 != 2002520572 )
        break;
      ++*(_DWORD *)v73;
      v60 = 1720322304;
    }
  }
  while ( v59 != 2106838288 );
  return 0;
}
// 401050: using guessed type __int64 __isoc99_scanf(const char *, ...);

//----- (0000000000403310) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=16 queued=8 decompiled=8 lumina nreq=0 worse=0 better=0
// ALL OK, 8 function(s) have been successfully decompiled
