#!/usr/bin/env python3
import sys
import os
import re

def transpile_llvm_ir_to_c(ir_path, out_c_path):
    with open(ir_path, "r", encoding="utf-8", errors="ignore") as f:
        lines = f.readlines()
        
    out = [
        "/* Auto-generated by LLVM-to-C Transpiler (LLVM2C) */\n",
        "#include <stdio.h>\n",
        "#include <stdint.h>\n",
        "#include <stdlib.h>\n",
        "#include <stdbool.h>\n",
        "#include <math.h>\n\n"
    ]
    
    in_func = False
    indent = "  "
    
    for line in lines:
        s = line.strip()
        if not s or s.startswith(";") or s.startswith("source_filename") or s.startswith("target "):
            continue
            
        if s.startswith("define "):
            in_func = True
            m = re.search(r"define\s+.*?@([a-zA-Z0-9_\.]+)\((.*?)\)", s)
            if m:
                fn_name = m.group(1).replace(".", "_")
                out.append(f"void {fn_name}() {{\n")
            else:
                out.append("void function_unknown() {\n")
            continue
            
        if s == "}":
            in_func = False
            out.append("}\n\n")
            continue
            
        if not in_func:
            continue
            
        if s.endswith(":"):
            lbl = s[:-1].replace(".", "_")
            out.append(f"{lbl}:\n")
            continue
            
        # Parse allocas
        m_alloca = re.search(r"%(%\S+|\S+)\s*=\s*alloca\s+(\[[^\]]+\]|\w+)", s)
        if m_alloca:
            var = m_alloca.group(1).replace("%", "v_").replace(".", "_")
            ty = m_alloca.group(2)
            if "[" in ty:
                out.append(f"{indent}uint8_t {var}[4096];\n")
            else:
                out.append(f"{indent}uint64_t {var};\n")
            continue
            
        # Parse stores
        m_store = re.search(r"store\s+\w+\s+(\S+),\s+ptr\s+(%\S+|\S+)", s)
        if m_store:
            val = m_store.group(1).replace("%", "v_").replace(".", "_")
            ptr = m_store.group(2).replace("%", "v_").replace(".", "_")
            out.append(f"{indent}*(uint64_t*)({ptr}) = {val};\n")
            continue
            
        # Parse loads
        m_load = re.search(r"%(%\S+|\S+)\s*=\s*load\s+\w+,\s+ptr\s+(%\S+|\S+)", s)
        if m_load:
            res = m_load.group(1).replace("%", "v_").replace(".", "_")
            ptr = m_load.group(2).replace("%", "v_").replace(".", "_")
            out.append(f"{indent}uint64_t {res} = *(uint64_t*)({ptr});\n")
            continue
            
        # Parse binary ops
        m_bin = re.search(r"%(%\S+|\S+)\s*=\s*(add|sub|mul|xor|and|or)\s+\w+\s+(\S+),\s+(\S+)", s)
        if m_bin:
            res = m_bin.group(1).replace("%", "v_").replace(".", "_")
            op_map = {"add": "+", "sub": "-", "mul": "*", "xor": "^", "and": "&", "or": "|"}
            v1 = m_bin.group(3).replace("%", "v_").replace(".", "_")
            v2 = m_bin.group(4).replace("%", "v_").replace(".", "_")
            op = op_map[m_bin.group(2)]
            out.append(f"{indent}uint64_t {res} = {v1} {op} {v2};\n")
            continue
            
        # Parse returns and branches
        if s.startswith("ret"):
            out.append(f"{indent}return;\n")
            continue
            
        if s.startswith("br label"):
            m_br = re.search(r"br label\s+%(%\S+|\S+)", s)
            if m_br:
                target = m_br.group(1).replace("%", "v_").replace(".", "_")
                out.append(f"{indent}goto {target};\n")
            continue
            
        if s.startswith("br i1"):
            m_br_cond = re.search(r"br i1\s+(\S+),\s+label\s+%(%\S+|\S+),\s+label\s+%(%\S+|\S+)", s)
            if m_br_cond:
                cond = m_br_cond.group(1).replace("%", "v_").replace(".", "_")
                t1 = m_br_cond.group(2).replace("%", "v_").replace(".", "_")
                t2 = m_br_cond.group(3).replace("%", "v_").replace(".", "_")
                out.append(f"{indent}if ({cond}) goto {t1}; else goto {t2};\n")
            continue
            
    with open(out_c_path, "w", encoding="utf-8") as f:
        f.write("".join(out))
    print(f"[✓] Transpiled LLVM IR -> C: {ir_path} -> {out_c_path}")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python3 llvm_to_c.py <input.ll> <output.c>")
        sys.exit(1)
    transpile_llvm_ir_to_c(sys.argv[1], sys.argv[2])
