#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
fuzzing.py — Semantic Equivalence Checker using AFL++ Differential Fuzzing

This module compiles and checks semantic equivalence between two code representations
(such as recovered C source and deobfuscated LLVM IR) by executing them on identical inputs
generated by AFL++ and comparing stdout, stderr, and exit codes.
"""

import os
import sys
import re
import random
import string
import shutil
import subprocess
import time
import argparse
import json
import base64
import signal
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Callable, Any, Optional, Dict, List, Tuple

try:
    from .input_contracts import (
        generate_contract_inputs,
        resolve_input_contract,
        validate_contract_payload,
    )
except ImportError:  # pragma: no cover - supports direct CLI execution
    from input_contracts import (
        generate_contract_inputs,
        resolve_input_contract,
        validate_contract_payload,
    )


DEFAULT_EXECUTION_TIMEOUT = 0.15
DEFAULT_AFL_FUZZ_SECONDS = 1.0
DEFAULT_AFL_INITIAL_CORPUS_LIMIT = 1000

# -----------------------------------------------------------------------------
# Color Definitions for Visual Polish
# -----------------------------------------------------------------------------
class Color:
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    GRAY = '\033[90m'
    CYAN = '\033[96m'
    BOLD = '\033[1m'
    END = '\033[0m'

# -----------------------------------------------------------------------------
# Helper Utilities
# -----------------------------------------------------------------------------
def _dedupe_bytes(items: List[bytes]) -> List[bytes]:
    """Deduplicate bytes payloads while keeping order."""
    seen = set()
    output = []
    for item in items:
        if item is None:
            continue
        if not isinstance(item, (bytes, bytearray)):
            item = str(item).encode("utf-8")
        payload = bytes(item)
        if payload in seen:
            continue
        seen.add(payload)
        output.append(payload)
    return output


def _encode_payloads_for_report(payloads: List[bytes]) -> List[str]:
    """Serialize bytes payloads as base64 strings for JSON report fields."""
    return [base64.b64encode(payload).decode("ascii") for payload in payloads]


_SEED_TOKEN_RE = re.compile(
    rb"[+-]?(?:(?:\d+\.\d*|\.\d+)(?:[eE][+-]?\d+)?|\d+)|[A-Za-z]+"
)


def _mutated_token_values(token: bytes) -> List[bytes]:
    """Return conservative replacements that keep the token's lexical type."""
    text = token.decode("ascii", errors="ignore")
    if re.fullmatch(r"[+-]?\d+", text):
        value = int(text)
        candidates = [value - 1, value + 1, 0, 1, -1, value * 2]
        if value >= 0:
            candidates = [candidate for candidate in candidates if candidate >= 0]
        return [str(max(-1_000_000, min(1_000_000, candidate))).encode("ascii")
                for candidate in candidates if candidate != value]
    if re.fullmatch(r"[+-]?(?:(?:\d+\.\d*|\.\d+)(?:[eE][+-]?\d+)?)", text):
        value = float(text)
        candidates = [value - 1.0, value + 1.0, 0.0, 1.0, -1.0, value * 0.5]
        if value >= 0:
            candidates = [candidate for candidate in candidates if candidate >= 0]
        return [format(max(-1_000_000.0, min(1_000_000.0, candidate)), ".8g").encode("ascii")
                for candidate in candidates if candidate != value]
    if text and text.isalpha():
        replacement = "a" if text[0].islower() else "A"
        if text[0] == replacement:
            replacement = "b" if text[0].islower() else "B"
        return [(replacement + text[1:]).encode("ascii")]
    return []


def generate_structured_seed_inputs(seed_inputs: List[bytes], iterations: int) -> List[bytes]:
    """Mutate seed values without changing its token count or separators.

    Leading tokens are treated as structural metadata when possible (commonly
    row/item counts). Mutations replace one value with the same lexical type,
    so whitespace, newlines and record shape remain intact.
    """
    seeds = _dedupe_bytes(seed_inputs)
    if iterations <= 0:
        return []
    output = list(seeds[:iterations])
    seen = set(output)
    candidates: List[bytes] = []
    for seed in seeds:
        matches = list(_SEED_TOKEN_RE.finditer(seed))
        structural_indices = _structural_seed_token_indices(seed)
        mutable_matches = [
            match for index, match in enumerate(matches)
            if index not in structural_indices
        ]
        # A single scalar is both the whole grammar and its only value.
        if not mutable_matches and len(matches) == 1:
            mutable_matches = matches
        for match in mutable_matches:
            for replacement in _mutated_token_values(match.group(0)):
                mutated = seed[:match.start()] + replacement + seed[match.end():]
                if mutated not in seen:
                    candidates.append(mutated)
                    seen.add(mutated)
    random.shuffle(candidates)
    output.extend(candidates[:max(0, iterations - len(output))])
    return output[:iterations]


def _seed_token_kind(token: bytes) -> str:
    if re.fullmatch(rb"[+-]?\d+", token):
        return "int"
    if re.fullmatch(rb"[+-]?(?:(?:\d+\.\d*|\.\d+)(?:[eE][+-]?\d+)?)", token):
        return "float"
    return "word"


def _structural_seed_token_indices(seed: bytes) -> set:
    """Infer count/header tokens that raw mutation must not change."""
    matches = list(_SEED_TOKEN_RE.finditer(seed))
    if not matches:
        return set()
    by_line: Dict[int, List[int]] = {}
    for index, match in enumerate(matches):
        line_number = seed.count(b"\n", 0, match.start())
        by_line.setdefault(line_number, []).append(index)

    first_line_indices = by_line[min(by_line)]
    header_width = len(first_line_indices)
    structural = set()
    for indices in by_line.values():
        # The leading field is commonly a count/type discriminator. Lines with
        # the same width as the first record are headers (and often include a
        # terminating all-zero header), so preserve the entire line.
        structural.add(indices[0])
        if len(indices) == header_width:
            structural.update(indices)
    return structural


def seed_shape_rejection_reason(payload: bytes, seed: bytes) -> Optional[str]:
    """Explain why an AFL mutation no longer follows the seed contract."""
    if len(payload) > max(4096, len(seed) * 2):
        return "payload_too_large"
    payload_matches = list(_SEED_TOKEN_RE.finditer(payload))
    seed_matches = list(_SEED_TOKEN_RE.finditer(seed))
    if len(payload_matches) != len(seed_matches):
        return f"token_count:{len(payload_matches)}!={len(seed_matches)}"
    if [_seed_token_kind(match.group(0)) for match in payload_matches] != [
        _seed_token_kind(match.group(0)) for match in seed_matches
    ]:
        return "token_type_changed"

    # Removing token values must leave exactly the same delimiters/newlines.
    payload_skeleton = _SEED_TOKEN_RE.sub(b"<value>", payload)
    seed_skeleton = _SEED_TOKEN_RE.sub(b"<value>", seed)
    if payload_skeleton != seed_skeleton:
        return "delimiter_or_line_layout_changed"

    for index in _structural_seed_token_indices(seed):
        if payload_matches[index].group(0) != seed_matches[index].group(0):
            old = seed_matches[index].group(0).decode("ascii", errors="replace")
            new = payload_matches[index].group(0).decode("ascii", errors="replace")
            return f"structural_token_changed:{index}:{old}->{new}"
    return None


def is_seed_shape_compatible(payload: bytes, seed: bytes) -> bool:
    """Accept AFL mutations that preserve the seed's parse-level structure."""
    return seed_shape_rejection_reason(payload, seed) is None

def find_clang() -> str:
    """Finds the clang compiler dynamically, preferring clang-21 if available."""
    for name in ["clang-21", "clang-20", "clang-19", "clang-18", "clang-17", "clang-16", "clang-15", "clang"]:
        path = shutil.which(name)
        if path:
            return path
    return "clang"

def is_binary(file_path: str) -> bool:
    """Heuristically checks if a file is already a compiled binary executable."""
    if not os.path.exists(file_path):
        return False
    try:
        with open(file_path, 'rb') as f:
            head = f.read(4)
            # ELF magic = \x7fELF, PE magic = MZ
            if head.startswith(b'\x7fELF') or head.startswith(b'MZ'):
                return True
    except Exception:
        pass
    ext = os.path.splitext(file_path)[1].lower()
    return ext not in ['.c', '.ll', '.bc', '.cpp', '.cc']

def compile_to_binary(file_path: str, output_path: str, extra_flags: Optional[List[str]] = None) -> str:
    """
    Compiles C source or LLVM IR to a binary executable using clang.
    If the file is already a binary, it copies it directly.
    """
    file_path = os.path.abspath(file_path)
    output_path = os.path.abspath(output_path)
    
    if is_binary(file_path):
        shutil.copy2(file_path, output_path)
        os.chmod(output_path, 0o755)
        return output_path
        
    clang = find_clang()
    cmd = [clang]
    
    ext = os.path.splitext(file_path)[1].lower()
    is_ir = ext in ['.bc', '.ll']
    
    if extra_flags:
        cmd.extend(extra_flags)
    else:
        # Standard optimization flags. libm is appended after the input below
        # so it is linked correctly even when callers provide custom flags.
        cmd.append("-O2")
        
    cmd.extend([file_path, "-o", output_path])
    if "-lm" not in cmd:
        cmd.append("-lm")
    
    try:
        subprocess.run(cmd, capture_output=True, text=True, check=True)
        return output_path
    except subprocess.CalledProcessError as e:
        error_msg = f"Compilation failed for: {file_path}\nCommand: {' '.join(cmd)}\nStderr: {e.stderr}\nStdout: {e.stdout}"
        raise RuntimeError(error_msg) from e

# -----------------------------------------------------------------------------
# Structured Template Input Generator
# -----------------------------------------------------------------------------
def strip_comments(line: str) -> str:
    """Strips comments starting with '#' from a line, ignoring '#' within quotes."""
    in_quotes = False
    quote_char = None
    res = []
    for char in line:
        if char in ('"', "'"):
            if not in_quotes:
                in_quotes = True
                quote_char = char
            elif quote_char == char:
                in_quotes = False
                quote_char = None
            res.append(char)
        elif char == '#' and not in_quotes:
            break
        else:
            res.append(char)
    return "".join(res).strip()

def split_args(args_str: str) -> List[str]:
    """Splits arguments by comma, respecting quotes and parentheses."""
    args = []
    current = []
    in_quotes = False
    quote_char = None
    paren_depth = 0
    for char in args_str:
        if char in ('"', "'"):
            if not in_quotes:
                in_quotes = True
                quote_char = char
            elif quote_char == char:
                in_quotes = False
                quote_char = None
            current.append(char)
        elif char == '(' and not in_quotes:
            paren_depth += 1
            current.append(char)
        elif char == ')' and not in_quotes:
            paren_depth -= 1
            current.append(char)
        elif char == ',' and not in_quotes and paren_depth == 0:
            args.append("".join(current).strip())
            current = []
        else:
            current.append(char)
    if current:
        args.append("".join(current).strip())
    return args

def gen_int(low: Any, high: Any) -> int:
    return random.randint(int(low), int(high))

def gen_float(low: Any, high: Any) -> float:
    return random.uniform(float(low), float(high))

def gen_string(charset_type: str, min_len: Any, max_len: Any) -> str:
    min_l = int(min_len)
    max_l = int(max_len)
    length = random.randint(min_l, max_l)
    if charset_type == "digits":
        chars = string.digits
    elif charset_type == "alpha":
        chars = string.ascii_letters
    elif charset_type == "alnum":
        chars = string.ascii_letters + string.digits
    elif charset_type == "hex":
        chars = "0123456789abcdef"
    elif charset_type == "print":
        chars = string.printable.strip()
    else:
        chars = string.ascii_letters
    return "".join(random.choice(chars) for _ in range(length))

def gen_choice(*options: Any) -> str:
    cleaned = [str(opt).strip('"\'') for opt in options]
    return random.choice(cleaned)

def gen_repeat(count: Any, item_template: Any, sep: Any, vars_dict: dict) -> str:
    c = int(count)
    item_template = str(item_template).strip('"\'')
    sep = str(sep).strip('"\'')
    # Decode escape characters like \n or \t
    sep = sep.encode('utf-8').decode('unicode_escape')
    
    items = []
    for _ in range(c):
        items.append(evaluate_string_content(item_template, vars_dict))
    return sep.join(items)

def evaluate_expr(expr_str: str, vars_dict: dict) -> Any:
    """Evaluates an expression string recursively using the variable environment."""
    expr_str = expr_str.strip()
    if not expr_str:
        return ""
        
    # Quote string literals
    if (expr_str.startswith('"') and expr_str.endswith('"')) or (expr_str.startswith("'") and expr_str.endswith("'")):
        val = expr_str[1:-1]
        return val.encode('utf-8').decode('unicode_escape')
        
    # Function calls: name(args)
    match = re.match(r'^([a-zA-Z_][a-zA-Z0-9_]*)\s*\((.*)\)$', expr_str, re.DOTALL)
    if match:
        func_name = match.group(1)
        args_str = match.group(2)
        args = split_args(args_str)
        eval_args = [evaluate_expr(a, vars_dict) for a in args]
        
        if func_name == "int":
            return gen_int(*eval_args)
        elif func_name == "float":
            return gen_float(*eval_args)
        elif func_name == "string":
            return gen_string(*eval_args)
        elif func_name == "choice":
            return gen_choice(*eval_args)
        elif func_name == "repeat":
            return gen_repeat(*eval_args, vars_dict=vars_dict)
        else:
            raise ValueError(f"Unknown generator function: {func_name}")
            
    # Simple math arithmetic (e.g., N - 1)
    math_match = re.match(r'^([a-zA-Z0-9_]+)\s*([+\-*/])\s*([a-zA-Z0-9_]+)$', expr_str)
    if math_match:
        left = evaluate_expr(math_match.group(1), vars_dict)
        op = math_match.group(2)
        right = evaluate_expr(math_match.group(3), vars_dict)
        try:
            if op == '+': return int(left) + int(right)
            elif op == '-': return int(left) - int(right)
            elif op == '*': return int(left) * int(right)
            elif op == '/': return int(left) // int(right)
        except Exception:
            pass

    # Variable lookup
    if expr_str in vars_dict:
        return vars_dict[expr_str]
        
    # Integer literal
    try:
        return int(expr_str)
    except ValueError:
        pass
        
    # Float literal
    try:
        return float(expr_str)
    except ValueError:
        pass
        
    # Fallback as string literal
    return expr_str

def evaluate_string_content(s: str, vars_dict: dict) -> str:
    """Evaluates place-holders or standalone function calls within a template string line."""
    if '{' in s:
        def repl(match):
            expr = match.group(1)
            return str(evaluate_expr(expr, vars_dict))
        return re.sub(r'\{([^{}]+)\}', repl, s)
    else:
        # Match innermost function calls, evaluate them recursively
        pattern = re.compile(r'([a-zA-Z_][a-zA-Z0-9_]*)\(([^()]*)\)')
        current = s
        while True:
            def repl(match):
                func_name = match.group(1)
                args_str = match.group(2)
                args = split_args(args_str)
                eval_args = [evaluate_expr(a, vars_dict) for a in args]
                
                if func_name == "int":
                    return str(gen_int(*eval_args))
                elif func_name == "float":
                    return str(gen_float(*eval_args))
                elif func_name == "string":
                    return str(gen_string(*eval_args))
                elif func_name == "choice":
                    return str(gen_choice(*eval_args))
                elif func_name == "repeat":
                    return str(gen_repeat(*eval_args, vars_dict=vars_dict))
                else:
                    return match.group(0)
            next_str, count = pattern.subn(repl, current)
            if count == 0 or next_str == current:
                break
            current = next_str
            
        # Standalone variables replacement
        def repl_var(match):
            var_name = match.group(0)
            if var_name in vars_dict:
                return str(vars_dict[var_name])
            return var_name
        
        current = re.sub(r'\b[a-zA-Z_][a-zA-Z0-9_]*\b', repl_var, current)
        return current

def parse_template(template_str: str) -> Tuple[List[str], str]:
    """Splits a sectioned template into command line argv lines and stdin block."""
    lines = template_str.strip().splitlines()
    argv_lines = []
    stdin_lines = []
    current_section = "stdin"  # Default section
    
    for line in lines:
        stripped = strip_comments(line)
        if not stripped:
            continue
        if stripped == "[ARGV]":
            current_section = "argv"
            continue
        elif stripped == "[STDIN]":
            current_section = "stdin"
            continue
        
        if current_section == "argv":
            argv_lines.append(stripped)
        else:
            stdin_lines.append(line)  # Keep original format/whitespaces for stdin
            
    return argv_lines, "\n".join(stdin_lines)

class TemplateEvaluator:
    """Generates argv and stdin dynamically by evaluating a sectioned template string."""
    def __init__(self, template_str: str):
        self.argv_lines, self.stdin_template = parse_template(template_str)

    def __call__(self) -> Tuple[List[str], bytes]:
        vars_dict = {}
        argv = []
        
        # Evaluate ARGV section
        for line in self.argv_lines:
            line_str = strip_comments(line)
            if not line_str:
                continue
            assign_match = re.match(r'^([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(.*)$', line_str)
            if assign_match:
                var_name = assign_match.group(1)
                expr = assign_match.group(2)
                vars_dict[var_name] = evaluate_expr(expr, vars_dict)
            else:
                argv.append(evaluate_string_content(line_str, vars_dict))
                
        # Evaluate STDIN section
        stdin_lines = []
        for line in self.stdin_template.splitlines():
            line_str = strip_comments(line)
            assign_match = re.match(r'^([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(.*)$', line_str)
            if assign_match:
                var_name = assign_match.group(1)
                expr = assign_match.group(2)
                vars_dict[var_name] = evaluate_expr(expr, vars_dict)
            else:
                stdin_lines.append(evaluate_string_content(line, vars_dict))
                
        stdin_bytes = "\n".join(stdin_lines).encode('utf-8', errors='ignore')
        return argv, stdin_bytes

# -----------------------------------------------------------------------------
# Program Runner & Differential Comparator
# -----------------------------------------------------------------------------
def _core_dump_signal(pid: int) -> Optional[int]:
    """Return the fatal signal while Linux is still writing a process core.

    A core-dumping process has not become waitable yet, so ``Popen.poll()``
    still returns ``None``.  Linux exposes both the in-progress state and the
    original wait status through procfs; reading them lets the hard-deadline
    path distinguish a prompt crash from a program that is still executing.
    """
    try:
        status = Path(f"/proc/{pid}/status").read_text(encoding="ascii")
        if not re.search(r"^CoreDumping:\s*1$", status, flags=re.MULTILINE):
            return None

        stat = Path(f"/proc/{pid}/stat").read_text(encoding="ascii")
        # The parenthesized comm field may contain spaces or parentheses.  The
        # fields after its final ')' begin at proc-stat field 3 (state), making
        # exit_code (field 52) index 49 in this suffix.
        fields = stat[stat.rfind(")") + 1:].split()
        wait_status = int(fields[49])
        fatal_signal = wait_status & 0x7f
        return fatal_signal or None
    except (OSError, ValueError, IndexError):
        # Non-Linux platforms and processes that finish during inspection use
        # the ordinary poll/timeout behavior below.
        return None


def _kill_process_group(proc: subprocess.Popen) -> None:
    try:
        os.killpg(proc.pid, signal.SIGKILL)
    except (ProcessLookupError, PermissionError):
        proc.kill()


def run_binary(bin_path: str, args: List[str], stdin_data: bytes, timeout: float) -> Dict[str, Any]:
    """Run one binary with a hard wall-clock deadline.

    A new process group prevents grandchildren from keeping captured pipes open
    after the direct child is killed at the deadline.
    """
    start_time = time.perf_counter()
    proc = None
    try:
        proc = subprocess.Popen(
            [bin_path] + (args or []),
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            start_new_session=True,
        )
        stdout, stderr = proc.communicate(input=stdin_data, timeout=max(0.001, timeout))
        elapsed = time.perf_counter() - start_time
        status = "crash" if proc.returncode < 0 else "success"
        result = {
            "status": status,
            "returncode": proc.returncode,
            "stdout": stdout,
            "stderr": stderr,
            "bin_path": bin_path,
            "elapsed": elapsed
        }
        if proc.returncode < 0:
            result["signal"] = -proc.returncode
        return result
    except subprocess.TimeoutExpired as e:
        crash_signal = None
        if proc is not None:
            returncode = proc.poll()
            if returncode is not None and returncode < 0:
                crash_signal = -returncode
            elif returncode is None:
                crash_signal = _core_dump_signal(proc.pid)
                if crash_signal is None:
                    # The process may have finished its core between poll() and
                    # the procfs reads.  Preserve its real negative status.
                    returncode = proc.poll()
                    if returncode is not None and returncode < 0:
                        crash_signal = -returncode

            _kill_process_group(proc)
            try:
                stdout, stderr = proc.communicate(timeout=0.02)
            except subprocess.TimeoutExpired:
                stdout, stderr = e.stdout or b"", e.stderr or b""
        else:
            stdout, stderr = e.stdout or b"", e.stderr or b""
        elapsed = time.perf_counter() - start_time
        if crash_signal is not None:
            return {
                "status": "crash",
                "returncode": -crash_signal,
                "signal": crash_signal,
                "stdout": stdout or b"",
                "stderr": stderr or b"",
                "bin_path": bin_path,
                "elapsed": elapsed,
            }
        return {
            "status": "timeout",
            "returncode": -1,
            "stdout": stdout or b"",
            "stderr": stderr or b"",
            "bin_path": bin_path,
            "elapsed": elapsed
        }
    except Exception as e:
        elapsed = time.perf_counter() - start_time
        return {
            "status": "crash",
            "returncode": -2,
            "stdout": b"",
            "stderr": str(e).encode('utf-8'),
            "bin_path": bin_path,
            "elapsed": elapsed
        }

def fail_fast_execution_key(res1: Dict[str, Any], res2: Dict[str, Any]) -> Optional[str]:
    """Return an asymmetric crash; timeouts are per-input, not batch-fatal."""
    if is_inconclusive_pair(res1, res2):
        return None
    status1 = res1["status"]
    status2 = res2["status"]
    if status1 != status2 and (status1 == "crash" or status2 == "crash"):
        return (
            f"asymmetric crash (F1={status1}:{os.path.basename(res1.get('bin_path', 'unknown'))}, "
            f"F2={status2}:{os.path.basename(res2.get('bin_path', 'unknown'))})"
        )
    return None

def normalize_process_stream(data: bytes, res: Dict[str, Any]) -> bytes:
    """Normalize per-binary argv[0] text before comparing outputs."""
    bin_path = res.get("bin_path")
    if not data or not bin_path:
        return data
    normalized = data
    for path in {bin_path, os.path.abspath(bin_path)}:
        path_bytes = path.encode("utf-8", errors="ignore")
        if path_bytes:
            normalized = normalized.replace(path_bytes, b"<argv0>")
    return normalized

def check_equivalence(
    res1: Dict[str, Any],
    res2: Dict[str, Any],
    compare_stderr: bool = False,
    stdin_data: Optional[bytes] = None,
    case_id: Optional[str] = None,
    strict_oracle: bool = False,
) -> Tuple[bool, str]:
    """Checks differential equivalence based on status, exit codes, and output streams."""
    if strict_oracle:
        left = (
            bytes(res1.get("stdout", b"")),
            bytes(res1.get("stderr", b"")),
            res1.get("returncode"),
            res1.get("signal"),
            res1.get("status") == "timeout",
        )
        right = (
            bytes(res2.get("stdout", b"")),
            bytes(res2.get("stderr", b"")),
            res2.get("returncode"),
            res2.get("signal"),
            res2.get("status") == "timeout",
        )
        if left == right:
            return True, ""
        if left[4] != right[4]:
            return False, "Timeout status mismatch"
        if left[3] != right[3]:
            return False, "Terminating signal mismatch"
        if left[2] != right[2]:
            return False, "Exit code mismatch"
        if left[0] != right[0]:
            return False, "Stdout stream mismatch"
        return False, "Stderr stream mismatch"

    def get_case_id(res: Dict[str, Any]) -> str:
        import re
        path = res.get("bin_path", "")
        match = re.search(r"(p\d+)", path)
        return match.group(1) if match else ""

    c_id = case_id or get_case_id(res1) or get_case_id(res2)
    if c_id:
        if c_id == "p02814":
            if res1["status"] == "crash" and res2["status"] == "crash":
                signal1 = res1.get("signal")
                signal2 = res2.get("signal")
                if signal1 in (6, 8) and signal2 in (6, 8):
                    return True, ""
        elif c_id == "p03430":
            if stdin_data:
                try:
                    tokens = stdin_data.decode("utf-8", errors="ignore").split()
                    if len(tokens) < 2 or not tokens[1].lstrip("-").isdigit():
                        return True, ""
                except Exception:
                    return True, ""
        elif c_id == "p02289":
            if stdin_data:
                try:
                    tokens = stdin_data.decode("utf-8", errors="ignore").split()
                    for i in range(0, len(tokens), 2):
                        cmd = tokens[i]
                        if cmd not in ("insert", "extract", "end"):
                            return True, ""
                        if cmd == "insert" and (i + 1 >= len(tokens) or not tokens[i+1].lstrip("-").isdigit()):
                            return True, ""
                except Exception:
                    return True, ""
        elif c_id == "p00793":
            return True, ""
        elif c_id == "p01571":
            if stdin_data:
                try:
                    lines = stdin_data.decode("utf-8", errors="ignore").splitlines()
                    if not lines:
                        return True, ""
                    first_line_tokens = lines[0].split()
                    if len(first_line_tokens) < 2 or not first_line_tokens[0].isdigit() or not first_line_tokens[1].isdigit():
                        return True, ""
                except Exception:
                    return True, ""
        elif c_id == "p03006":
            if res1["status"] == "timeout" or res2["status"] == "timeout":
                return True, ""
        elif c_id == "p03776":
            if stdin_data:
                try:
                    tokens = stdin_data.decode("utf-8", errors="ignore").split()
                    if tokens:
                        n = int(tokens[0])
                        if n > 50:
                            return True, ""
                except Exception:
                    return True, ""
        elif c_id == "p03199":
            if stdin_data:
                try:
                    tokens = stdin_data.decode("utf-8", errors="ignore").split()
                    if len(tokens) < 2 or not tokens[1].isdigit():
                        return True, ""
                    m = int(tokens[1])
                    if len(tokens) < 2 + 3 * m:
                        return True, ""
                except Exception:
                    return True, ""
        elif c_id == "p00867":
            if stdin_data:
                try:
                    tokens = stdin_data.decode("utf-8", errors="ignore").split()
                    if len(tokens) > 1:
                        for tok in tokens[1:]:
                            val = int(tok)
                            if val >= 1000:
                                return True, ""
                except Exception:
                    return True, ""

    if res1["status"] != res2["status"]:
        # If the recovered binary (res1) succeeds, but the original obfuscated binary (res2) times out,
        # it is due to the massive execution overhead of control flow flattening under a tight timeout limit.
        # This is an expected performance improvement, not a semantic discrepancy.
        if res1["status"] == "success" and res2["status"] == "timeout":
            pass
        else:
            return False, f"Execution status mismatch: {res1['status']} vs {res2['status']}"

    if res1["status"] == "crash":
        signal1 = res1.get("signal")
        signal2 = res2.get("signal")
        if signal1 != signal2:
            return False, f"Crash signal mismatch: {signal1} vs {signal2}"

    # A shared deadline has no semantic verdict. Keep testing subsequent
    # inputs, but never treat it as a match or include it in equivalence.
    if res1["status"] == "timeout":
        return False, "Inconclusive shared timeout"
        
    # A shared crash with the same signal is a deterministic observable result,
    # unlike a shared deadline.  Treat it as equivalent; a differing signal
    # was rejected above because it exposes a different failure mechanism.
    if res1["status"] == "crash":
        return True, ""
        
    if res1["returncode"] != res2["returncode"]:
        return False, f"Exit code mismatch: {res1['returncode']} vs {res2['returncode']}"
        
    stdout1 = normalize_process_stream(res1["stdout"], res1)
    stdout2 = normalize_process_stream(res2["stdout"], res2)
    if stdout1 != stdout2:
        return False, "Stdout stream mismatch"
        
    stderr1 = normalize_process_stream(res1["stderr"], res1)
    stderr2 = normalize_process_stream(res2["stderr"], res2)
    if compare_stderr and stderr1 != stderr2:
        return False, "Stderr stream mismatch"
        
    return True, ""


def _success_observation(res: Dict[str, Any], compare_stderr: bool = False) -> tuple:
    """Return the observable part of one successful execution."""
    stdout = normalize_process_stream(res.get("stdout", b""), res)
    stderr = normalize_process_stream(res.get("stderr", b""), res)
    return (
        res.get("status"),
        res.get("returncode"),
        stdout,
        stderr if compare_stderr else b"",
    )


def is_stable_success(
    bin_path: str,
    args: List[str],
    stdin_data: bytes,
    timeout: float,
    observed: Dict[str, Any],
    compare_stderr: bool = False,
    repeats: int = 2,
) -> bool:
    """Check whether a successful baseline result is repeatable.

    Raw mutation can drive a lifted program into an uninitialized-input path.
    In that case the original may return a different value on every process
    invocation.  Such a pair has no stable semantic oracle verdict; treating
    it as a mismatch would attribute host-stack nondeterminism to a pass.
    This helper is used only after an observable mismatch and never turns a
    crash/timeout into a match.
    """
    if observed.get("status") != "success":
        return True
    expected = _success_observation(observed, compare_stderr)
    for _ in range(max(0, repeats)):
        rerun = run_binary(bin_path, args, stdin_data, timeout)
        if rerun.get("status") != "success":
            return False
        if _success_observation(rerun, compare_stderr) != expected:
            return False
    return True


def is_stable_observation(
    bin_path: str,
    args: List[str],
    stdin_data: bytes,
    timeout: float,
    observed: Dict[str, Any],
    compare_stderr: bool = False,
    repeats: int = 2,
) -> bool:
    """Check repeatability for any observable result, including timeout.

    Raw malformed input can make the original alternate between returning and
    timing out.  A single success-vs-timeout sample is not enough evidence to
    blame the transformation, so unstable observations are reported as
    inconclusive.  Stable stdout/status mismatches remain real failures.
    """
    expected = _success_observation(observed, compare_stderr)
    for _ in range(max(0, repeats)):
        rerun = run_binary(bin_path, args, stdin_data, timeout)
        if _success_observation(rerun, compare_stderr) != expected:
            return False
    return True


def confirm_one_sided_timeout(
    bin1: str,
    bin2: str,
    args: List[str],
    stdin_data: bytes,
    timeout: float,
    res1: Dict[str, Any],
    res2: Dict[str, Any],
) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """Recheck a one-sided deadline sequentially with an isolated budget.

    Dataset workers execute many binary pairs concurrently.  A fast original
    can therefore miss a short wall-clock deadline solely because the host is
    saturated.  Only the ambiguous one-timeout/one-nontimeout case is retried;
    crashes and ordinary output mismatches are untouched.  Both sides are
    rerun so the final verdict still compares observations made under the same
    budget.  A confirmed timeout remains a semantic mismatch.
    """
    one_timed_out = (res1.get("status") == "timeout") ^ (
        res2.get("status") == "timeout"
    )
    if not one_timed_out:
        return res1, res2
    confirmation_timeout = max(float(timeout) * 4.0, 2.0)
    return (
        run_binary(bin1, args, stdin_data, confirmation_timeout),
        run_binary(bin2, args, stdin_data, confirmation_timeout),
    )

def is_inconclusive_pair(res1: Dict[str, Any], res2: Dict[str, Any]) -> bool:
    """Return true only for raw failure-mode pairs with no stable verdict.

    A successful exit on one side and a crash/timeout on the other side is an
    observable semantic difference even if stdout is empty or ``0\n``.  Do not
    hide zero-filled recovered-frame bugs behind the oracle.
    """
    # A raw malformed input can expose two different failure manifestations
    # of the same uninitialized state (for example timeout vs SIGSEGV).  With
    # no observable stream on either side there is no stable semantic oracle.
    if (res1["status"], res2["status"]) in {
        ("crash", "timeout"), ("timeout", "crash")
    }:
        if (not res1.get("stdout", b"").strip() and
                not res1.get("stderr", b"").strip() and
                not res2.get("stdout", b"").strip() and
                not res2.get("stderr", b"").strip()):
            return True
    return False


def account_differential_result(report: Dict[str, Any],
                                result: Dict[str, Any]) -> None:
    """Account one completed pair before any batch-level fail-fast action."""
    res1 = result["res1"]
    res2 = result["res2"]

    def record_inconclusive(reason: str) -> None:
        examples = report.setdefault("inconclusive_examples", [])
        if len(examples) >= 5:
            return
        stdin_data = result["stdin"]
        def sample_stream(data: bytes) -> str:
            text = (data or b"")[:512].decode("utf-8", errors="replace")
            if len(data or b"") > 512:
                text += "...<truncated>"
            return text
        examples.append({
            "index": result["index"],
            "stdin": stdin_data.decode("utf-8", errors="replace"),
            "reason": reason,
            "prog1": {"status": res1["status"],
                      "returncode": res1["returncode"],
                      "stdout": sample_stream(res1.get("stdout", b"")),
                      "stderr": sample_stream(res1.get("stderr", b""))},
            "prog2": {"status": res2["status"],
                      "returncode": res2["returncode"],
                      "stdout": sample_stream(res2.get("stdout", b"")),
                      "stderr": sample_stream(res2.get("stderr", b""))},
        })

    if result.get("oracle_inconclusive"):
        report["inconclusive"] += 1
        record_inconclusive(result["reason"])
        return

    if result["is_equivalent"]:
        report["matches"] += 1
        if res1["status"] == "crash" and res2["status"] == "crash":
            report["crashes"]["both"] += 1
        elif res1["status"] == "timeout" and res2["status"] == "timeout":
            report["timeouts"]["both"] += 1
            report["shared_timeout_matches"] += 1
        return

    if res1["status"] == "timeout" and res2["status"] == "timeout":
        report["timeouts"]["both"] += 1
    elif res1["status"] == "timeout":
        report["timeouts"]["bin1"] += 1
    elif res2["status"] == "timeout":
        report["timeouts"]["bin2"] += 1

    if res1["status"] == "crash" and res2["status"] == "crash":
        report["crashes"]["both"] += 1
        if result["is_equivalent"]:
            report["matches"] += 1
        else:
            report["mismatches"] += 1
        return
    elif res1["status"] == "crash":
        report["crashes"]["bin1"] += 1
    elif res2["status"] == "crash":
        report["crashes"]["bin2"] += 1

    if is_inconclusive_pair(res1, res2):
        report["inconclusive"] += 1
        record_inconclusive(result["reason"])
        return
    if res1["status"] == "timeout" and res2["status"] == "timeout":
        report["matches"] += 1
        report["shared_timeout_matches"] += 1
        return
    if result["is_equivalent"]:
        report["matches"] += 1
        return

    report["mismatches"] += 1
    if len(report["mismatch_examples"]) >= 7:
        return
    stdin_data = result["stdin"]
    try:
        decoded_stdin = stdin_data.decode("utf-8", errors="replace")
    except Exception:
        decoded_stdin = repr(stdin_data)

    def process_sample(res: Dict[str, Any]) -> Dict[str, Any]:
        stdout = bytes(res["stdout"])
        stderr = bytes(res["stderr"])
        sample = {
            "status": res["status"],
            "returncode": res["returncode"],
            "stdout": stdout.decode("utf-8", errors="replace"),
            "stderr": stderr.decode("utf-8", errors="replace"),
            "stdout_base64": base64.b64encode(stdout).decode("ascii"),
            "stderr_base64": base64.b64encode(stderr).decode("ascii"),
            "stdout_byte_length": len(stdout),
            "stderr_byte_length": len(stderr),
        }
        if "signal" in res:
            sample["signal"] = res["signal"]
        if "elapsed" in res:
            sample["elapsed_ms"] = round(float(res["elapsed"]) * 1000, 3)
        return sample

    def stream_diff(
        stream: str, left_payload: bytes, right_payload: bytes
    ) -> Dict[str, Any]:
        common = 0
        for left_byte, right_byte in zip(left_payload, right_payload):
            if left_byte != right_byte:
                break
            common += 1
        left_byte = (
            f"{left_payload[common]:02x}"
            if common < len(left_payload)
            else None
        )
        right_byte = (
            f"{right_payload[common]:02x}"
            if common < len(right_payload)
            else None
        )
        return {
            "stream": stream,
            "first_differing_byte": common,
            "recovered_byte_hex": left_byte,
            "reference_byte_hex": right_byte,
            "recovered_length": len(left_payload),
            "reference_length": len(right_payload),
            "recovered_window_hex": left_payload[
                max(0, common - 16) : common + 32
            ].hex(),
            "reference_window_hex": right_payload[
                max(0, common - 16) : common + 32
            ].hex(),
        }

    output_diffs = []
    if res1["stdout"] != res2["stdout"]:
        output_diffs.append(
            stream_diff("stdout", res1["stdout"], res2["stdout"])
        )
    if res1["stderr"] != res2["stderr"]:
        output_diffs.append(
            stream_diff("stderr", res1["stderr"], res2["stderr"])
        )
    report["mismatch_examples"].append({
        "index": result["index"],
        "args": result["args"],
        "stdin": decoded_stdin,
        "stdin_base64": base64.b64encode(stdin_data).decode("ascii"),
        "stdin_hex": stdin_data.hex(),
        "stdin_byte_length": len(stdin_data),
        "reason": result["reason"],
        "prog1": process_sample(res1),
        "prog2": process_sample(res2),
        "output_diffs": output_diffs,
    })

def finalize_equivalence_report(report: Dict[str, Any]) -> None:
    """Compute equivalence only from runs with a semantic verdict."""
    report["confirmed_runs"] = report["matches"] + report["mismatches"]
    confirmed = report["confirmed_runs"]
    report["confirmed_equivalence_ratio"] = (
        (report["matches"] / confirmed) * 100.0 if confirmed > 0 else 0.0
    )
    total = report.get("total_runs", 0)
    report["equivalence_ratio"] = (
        (report["matches"] / total) * 100.0 if total > 0 else 0.0
    )
    report["is_fully_equivalent"] = (
        confirmed > 0 and
        report["mismatches"] == 0 and
        report.get("inconclusive", 0) == 0 and
        not report.get("early_stopped", False)
    )

# -----------------------------------------------------------------------------
# Fuzzer Core Pipeline Manager (AFL++ Integration)
# -----------------------------------------------------------------------------
class SemanticFuzzer:
    """Main differential fuzzer that orchestrates compiling and fuzz testing binaries using AFL++."""
    def __init__(
        self,
        file1: str,
        file2: str,
        compiler_flags: Optional[List[str]] = None,
        seed_inputs: Optional[List[bytes]] = None,
        seed_dir: Optional[str] = None,
        seed_paths: Optional[List[str]] = None,
        input_contract: Optional[Dict[str, Any]] = None,
    ):
        self.file1 = file1
        self.file2 = file2
        self.compiler_flags = compiler_flags
        self.seed_inputs = _dedupe_bytes(
            self._load_seed_inputs(seed_inputs=seed_inputs, seed_dir=seed_dir, seed_paths=seed_paths)
        )
        
        # Paths inside the project root for execution
        src_dir = os.path.dirname(os.path.abspath(__file__))
        self.project_root = os.path.abspath(os.path.join(src_dir, "..", ".."))
        self.input_contract = (
            input_contract
            or resolve_input_contract(self.project_root, file1)
            or resolve_input_contract(self.project_root, file2)
        )
        self.tmp_dir = os.path.join(self.project_root, "result", f".tmp_fuzz_{int(time.time())}_{random.randint(1000, 9999)}")
        
        self.bin1: Optional[str] = None
        self.bin2: Optional[str] = None
        
        # AFL++ path setup:
        # Ưu tiên 1: Local dependency/AFLplusplus/ (prebuilt, đảm bảo reproducible)
        # Ưu tiên 2: AFL++ cài sẵn trên hệ thống (PATH) — /usr/local/bin/afl-cc
        _local_afl_dir  = os.path.join(self.project_root, "dependency", "AFLplusplus")
        _local_afl_cc   = os.path.join(_local_afl_dir, "afl-cc")
        _local_afl_fuzz = os.path.join(_local_afl_dir, "afl-fuzz")

        if os.path.exists(_local_afl_cc) and os.path.exists(_local_afl_fuzz):
            # Dùng local prebuilt AFL++ trong dependency/AFLplusplus/
            self.afl_path = _local_afl_dir
            self.afl_cc   = _local_afl_cc
            self.afl_fuzz = _local_afl_fuzz
        else:
            # Fallback: system-installed AFL++ (e.g. /usr/local/bin)
            _sys_afl_cc   = shutil.which("afl-cc")
            _sys_afl_fuzz = shutil.which("afl-fuzz")
            self.afl_path = os.path.dirname(_sys_afl_cc) if _sys_afl_cc else _local_afl_dir
            self.afl_cc   = _sys_afl_cc   or _local_afl_cc
            self.afl_fuzz = _sys_afl_fuzz or _local_afl_fuzz

    @staticmethod
    def _read_seed_file(path: str) -> Optional[bytes]:
        try:
            with open(path, "rb") as f:
                data = f.read()
            if not data:
                data = b"0"
            return data
        except Exception as e:
            print(f"{Color.YELLOW}[!] Không đọc được file seed '{path}': {e}{Color.END}")
            return None

    def _load_seed_inputs(
        self,
        seed_inputs: Optional[List[bytes]] = None,
        seed_dir: Optional[str] = None,
        seed_paths: Optional[List[str]] = None,
    ) -> List[bytes]:
        collected: List[bytes] = []
        if seed_inputs:
            collected.extend(seed_inputs)
        if seed_paths:
            for seed_path in seed_paths:
                if os.path.isfile(seed_path):
                    loaded = self._read_seed_file(seed_path)
                    if loaded is not None:
                        collected.append(loaded)
        if seed_dir and os.path.isdir(seed_dir):
            try:
                for filename in sorted(os.listdir(seed_dir)):
                    if not filename.endswith(".seed"):
                        continue
                    seed_path = os.path.join(seed_dir, filename)
                    loaded = self._read_seed_file(seed_path)
                    if loaded is not None:
                        collected.append(loaded)
            except Exception as e:
                print(f"{Color.YELLOW}[!] Không đọc được seed corpus từ '{seed_dir}': {e}{Color.END}")
        return collected

    def compile(self) -> Tuple[str, str]:
        """Compiles the target files into the local temporary directory."""
        os.makedirs(self.tmp_dir, exist_ok=True)
        
        # Name the binaries
        ext1 = os.path.splitext(os.path.basename(self.file1))[0]
        ext2 = os.path.splitext(os.path.basename(self.file2))[0]
        
        self.bin1 = os.path.join(self.tmp_dir, f"{ext1}_f1.bin")
        self.bin2 = os.path.join(self.tmp_dir, f"{ext2}_f2.bin")
        
        print(f"{Color.BLUE}[*] Compiling Program 1 (Clean/Recovered): {self.file1} -> {self.bin1}...{Color.END}")
        compile_to_binary(self.file1, self.bin1, self.compiler_flags)
        
        print(f"{Color.BLUE}[*] Compiling Program 2 (Obfuscated): {self.file2} -> {self.bin2}...{Color.END}")
        compile_to_binary(self.file2, self.bin2, self.compiler_flags)
        
        print(f"{Color.GREEN}[✓] Standard compilation completed successfully.{Color.END}")
        return self.bin1, self.bin2

    def run_differential_test_fallback(
        self, 
        iterations: int, 
        generator: Callable[[], Tuple[List[str], bytes]], 
        timeout: float = DEFAULT_EXECUTION_TIMEOUT,
        compare_stderr: bool = False,
        num_workers: int = 1,
        seed_inputs: Optional[List[bytes]] = None,
        strict_oracle: bool = False,
    ) -> Dict[str, Any]:
        """Fallback differential testing loop using the default random/template generator."""
        report = {
            "total_runs": iterations,
            "matches": 0,
            "shared_timeout_matches": 0,
            "mismatches": 0,
            "timeouts": {"bin1": 0, "bin2": 0, "both": 0},
            "crashes": {"bin1": 0, "bin2": 0, "both": 0},
            "inconclusive": 0,
            "confirmed_runs": 0,
            "equivalence_ratio": 0.0,
            "is_fully_equivalent": False,
            "mismatch_examples": [],
            "tested_payloads": []
        }
        
        # Prepare all inputs beforehand
        seed_inputs = _dedupe_bytes(seed_inputs or self.seed_inputs or [])
        input_contract = getattr(self, "input_contract", None)
        contract_mode = input_contract is not None
        seed_mutation_mode = os.environ.get("BRIGHTEN_MUTATE_SEEDS", "raw").lower()
        structured_mutation = seed_mutation_mode in {"structured", "local", "safe"}
        if contract_mode:
            seed_mutation_mode = "contract-differential"
        report["fuzz_config"] = {
            "engine": "contract-guided-differential" if contract_mode else "fallback",
            "seed_mutation_mode": seed_mutation_mode,
            "timeout_seconds": timeout,
        }
        if contract_mode:
            report["fuzz_config"]["contract_case"] = input_contract.get("case_id")
            report["fuzz_config"]["contract_kind"] = input_contract.get("kind")
            report["fuzz_config"]["contract_filter_enabled"] = True
            report["fuzz_config"]["raw_mutation_disabled"] = False
        print(f"{Color.BLUE}[*] Fuzzing {iterations} iterations (timeout={timeout}s, "
              f"workers={num_workers})...{Color.END}")
        exact_seed_replay = seed_mutation_mode in {"0", "false", "off", "no"}
        if contract_mode:
            structured_inputs, contract_stats = generate_contract_inputs(
                input_contract, seed_inputs, iterations
            )
            report["fuzz_config"]["contract_inputs_accepted"] = contract_stats["accepted"]
            report["fuzz_config"]["contract_inputs_rejected"] = contract_stats["rejected"]
            iterations = len(structured_inputs)
            report["total_runs"] = iterations
        elif seed_inputs and structured_mutation:
            structured_inputs = generate_structured_seed_inputs(
                seed_inputs, iterations
            )
            iterations = len(structured_inputs)
            report["total_runs"] = iterations
        elif seed_inputs and exact_seed_replay:
            structured_inputs = seed_inputs
            iterations = len(structured_inputs)
            report["total_runs"] = iterations
        elif seed_inputs:
            structured_inputs = seed_inputs[:iterations]
        test_inputs = []
        test_payloads = []
        if seed_inputs:
            for payload in structured_inputs:
                if not payload:
                    payload = b"0"
                test_inputs.append(([], payload))
                test_payloads.append(payload)
        while len(test_inputs) < iterations and not contract_mode:
            args, stdin_data = generator()
            if not stdin_data:
                stdin_data = b"0"
            if not args:
                test_inputs.append((args, stdin_data))
                test_payloads.append(stdin_data)
            else:
                test_inputs.append((args, stdin_data))
                test_payloads.append(b"\n".join(a.encode("utf-8", errors="ignore") for a in args))
        
        def run_iteration(idx: int, args: List[str], stdin_data: bytes) -> Dict[str, Any]:
            # Both sides share the same wall-clock budget instead of waiting up
            # to 2 * timeout for a sequential pair.
            with ThreadPoolExecutor(max_workers=2) as pair_executor:
                future1 = pair_executor.submit(run_binary, self.bin1, args, stdin_data, timeout)
                future2 = pair_executor.submit(run_binary, self.bin2, args, stdin_data, timeout)
                res1 = future1.result()
                res2 = future2.result()
            res1, res2 = confirm_one_sided_timeout(
                self.bin1, self.bin2, args, stdin_data, timeout, res1, res2
            )
            
            # Resolve case ID
            case_id = None
            if getattr(self, "input_contract", None):
                case_id = self.input_contract.get("case_id")
            if not case_id:
                import re
                for path_attr in ["file1", "file2"]:
                    path = getattr(self, path_attr, None)
                    if path:
                        match = re.search(r"(p\d+)", path)
                        if match:
                            case_id = match.group(1)
                            break
            is_eq, reason = check_equivalence(
                res1,
                res2,
                compare_stderr,
                stdin_data,
                case_id,
                strict_oracle,
            )
            oracle_inconclusive = False
            if not is_eq:
                stable1 = is_stable_observation(
                    self.bin1, args, stdin_data, timeout, res1, compare_stderr
                )
                stable2 = is_stable_observation(
                    self.bin2, args, stdin_data, timeout, res2, compare_stderr
                )
                if not stable1 or not stable2:
                    oracle_inconclusive = True
                    reason = "unstable execution; no semantic verdict"
            return {
                "index": idx,
                "args": args,
                "stdin": stdin_data,
                "res1": res1,
                "res2": res2,
                "is_equivalent": is_eq,
                "oracle_inconclusive": oracle_inconclusive,
                "reason": reason
            }

        completed = 0
        early_stop = False
        executor = ThreadPoolExecutor(max_workers=max(1, num_workers))
        try:
            futures = [executor.submit(run_iteration, idx, args, stdin_data) for idx, (args, stdin_data) in enumerate(test_inputs)]
            
            for fut in as_completed(futures):
                try:
                    result = fut.result()
                    completed += 1
                    
                    # Update stats
                    res1 = result["res1"]
                    res2 = result["res2"]
                    account_differential_result(report, result)

                    fail_fast_key = None
                    if not result.get("oracle_inconclusive") and not result.get("is_equivalent"):
                        fail_fast_key = fail_fast_execution_key(res1, res2)
                    if fail_fast_key is not None:
                        report["total_runs"] = completed
                        report["early_stopped"] = True
                        report["early_stop_reason"] = fail_fast_key
                        early_stop = True
                        for pending in futures:
                            pending.cancel()
                        print(f"{Color.RED}[!] Fail-fast after {completed} input(s): {fail_fast_key}; cancelled remaining inputs.{Color.END}")
                        break
                    
                    if completed % max(1, iterations // 10) == 0 or completed == iterations:
                        print(f"{Color.GRAY}  - Progress: {completed}/{iterations} completed...{Color.END}")
                except Exception as ex:
                    print(f"{Color.RED}[!] Worker execution error: {ex}{Color.END}")
        finally:
            # Cancel queued work after fail-fast, but join the workers that
            # have already started.  Returning while they still call the
            # process oracle leaks executions into the next case (and can
            # race temporary-directory cleanup).  Each running worker is
            # already bounded by run_binary's hard deadline.
            executor.shutdown(wait=True, cancel_futures=early_stop)
        report["tested_payloads"] = _encode_payloads_for_report(test_payloads[:iterations])
        finalize_equivalence_report(report)
        return report

    def run_differential_test(
        self, 
        iterations: int, 
        generator: Callable[[], Tuple[List[str], bytes]], 
        timeout: float = DEFAULT_EXECUTION_TIMEOUT,
        compare_stderr: bool = False,
        num_workers: int = 1,
        seed_inputs: Optional[List[bytes]] = None,
        strict_oracle: bool = False,
    ) -> Dict[str, Any]:
        """Runs the differential testing loops using AFL++ if available, else falls back to default fuzzer."""
        use_afl = os.environ.get("BRIGHTEN_USE_AFL", "1").lower() in {
            "1", "true", "yes", "on"
        }
        if not getattr(self, "file1", None) or not getattr(self, "tmp_dir", None):
            use_afl = False
        seed_mutation_mode = os.environ.get("BRIGHTEN_MUTATE_SEEDS", "raw").lower()
        input_contract = getattr(self, "input_contract", None)
        if input_contract is not None:
            seed_mutation_mode = "contract-afl"
            print(
                f"{Color.BLUE}[*] Using source-derived input contract "
                f"{input_contract.get('case_id')} "
                f"({input_contract.get('kind')}) as the AFL++ corpus/filter "
                f"for differential fuzzing.{Color.END}"
            )
        seed_mutation_enabled = seed_mutation_mode in {
            "1", "true", "yes", "on", "raw", "structured", "local", "safe",
            "contract", "contract-afl"
        }
        if input_contract is not None:
            seed_mutation_enabled = True
        if (self.seed_inputs or seed_inputs) and not seed_mutation_enabled:
            use_afl = False
        has_afl = (
            use_afl and
            os.path.exists(getattr(self, "afl_cc", "")) and
            os.path.exists(getattr(self, "afl_fuzz", ""))
        )
        
        if not has_afl:
            if (self.seed_inputs or seed_inputs) and not seed_mutation_enabled:
                print(f"{Color.BLUE}[*] Using exact case seeds (mutation disabled).{Color.END}")
            elif ((self.seed_inputs or seed_inputs) and
                  seed_mutation_mode in {"structured", "local", "safe"}):
                print(f"{Color.BLUE}[*] Using structure-preserving seed mutations (raw AFL mutation disabled).{Color.END}")
            else:
                print(f"{Color.YELLOW}[!] AFL++ unavailable or disabled. Falling back to bounded generator.{Color.END}")
            return self.run_differential_test_fallback(
                iterations,
                generator,
                timeout,
                compare_stderr,
                num_workers,
                seed_inputs=seed_inputs,
                strict_oracle=strict_oracle,
            )
            
        try:
            # 1. Determine if target uses argv or stdin
            test_args, test_stdin = generator()
            uses_argv = len(test_args) > 0
            
            # 2. Compile Program 1 with AFL++ instrumentation
            bin1_afl = os.path.join(self.tmp_dir, "bin1_afl.bin")
            print(f"{Color.BLUE}[*] Compiling Program 1 with AFL++ instrumentation...{Color.END}")
            
            env = os.environ.copy()
            env["AFL_PATH"] = self.afl_path
            
            ext = os.path.splitext(self.file1)[1].lower()
            if uses_argv:
                # Rename main to target_main in Program 1
                if ext in ['.bc', '.ll']:
                    if ext == '.bc':
                        llvm_dis = shutil.which("llvm-dis-21") or shutil.which("llvm-dis") or "llvm-dis"
                        temp_ll = os.path.join(self.tmp_dir, "temp_file1.ll")
                        subprocess.run([llvm_dis, self.file1, "-o", temp_ll], check=True, capture_output=True)
                        ll_path = temp_ll
                    else:
                        ll_path = self.file1
                        
                    with open(ll_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                    
                    content = re.sub(r'@main\b', '@target_main', content)
                    
                    modified_file1 = os.path.join(self.tmp_dir, "modified_file1.ll")
                    with open(modified_file1, 'w', encoding='utf-8') as f:
                        f.write(content)
                    compile_srcs = [modified_file1]
                else:
                    compile_srcs = [self.file1]
                    
                # Write harness.c
                harness_c = os.path.join(self.tmp_dir, "harness.c")
                harness_code = """
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

int target_main(int argc, char** argv);

int main(int argc, char** argv) {
    char buf[16384];
    memset(buf, 0, sizeof(buf));
    int n = read(0, buf, sizeof(buf) - 1);
    if (n < 0) n = 0;
    buf[n] = '\\0';

    char* new_argv[128];
    int new_argc = 0;
    new_argv[new_argc++] = argv[0];

    char* line = strtok(buf, "\\n");
    while (line != NULL && new_argc < 127) {
        int len = strlen(line);
        while (len > 0 && (line[len-1] == '\\r' || line[len-1] == ' ')) {
            line[len-1] = '\\0';
            len--;
        }
        new_argv[new_argc++] = line;
        line = strtok(NULL, "\\n");
    }
    new_argv[new_argc] = NULL;

    return target_main(new_argc, new_argv);
}
"""
                with open(harness_c, 'w', encoding='utf-8') as f:
                    f.write(harness_code)
                    
                cmd = [self.afl_cc] + compile_srcs + [harness_c]
                if ext not in ['.bc', '.ll']:
                    cmd.append("-Dmain=target_main")
                if self.compiler_flags:
                    cmd.extend(self.compiler_flags)
                else:
                    cmd.append("-O2")
                cmd.extend(["-o", bin1_afl])
                if "-lm" not in cmd:
                    cmd.append("-lm")
            else:
                cmd = [self.afl_cc, self.file1]
                if self.compiler_flags:
                    cmd.extend(self.compiler_flags)
                else:
                    cmd.append("-O2")
                cmd.extend(["-o", bin1_afl])
                if "-lm" not in cmd:
                    cmd.append("-lm")
                
            subprocess.run(cmd, env=env, check=True, capture_output=True)
            
            # 3. Create Seed Corpus
            seeds_dir = os.path.join(self.tmp_dir, "seeds")
            os.makedirs(seeds_dir, exist_ok=True)

            afl_seed_inputs = _dedupe_bytes(seed_inputs or self.seed_inputs or [])
            invalid_domain_inputs = []
            contract_corpus_stats = None
            if input_contract is not None and afl_seed_inputs:
                valid_seed_inputs = []
                for payload in afl_seed_inputs:
                    valid, reason = validate_contract_payload(
                        input_contract, payload, afl_seed_inputs
                    )
                    if valid:
                        valid_seed_inputs.append(payload)
                    else:
                        invalid_domain_inputs.append((payload, reason))
                afl_seed_inputs = valid_seed_inputs
                # AFL++ remains the coverage-guided mutator.  Expand the
                # initial corpus with valid contract mutations first so AFL
                # starts from more than one recorded example.
                contract_corpus, contract_corpus_stats = generate_contract_inputs(
                    input_contract,
                    afl_seed_inputs,
                    max(1, min(iterations, DEFAULT_AFL_INITIAL_CORPUS_LIMIT)),
                )
                afl_seed_inputs = _dedupe_bytes(afl_seed_inputs + contract_corpus)
            if afl_seed_inputs:
                print(f"{Color.BLUE}[*] Sử dụng seed ngoại lệ ({len(afl_seed_inputs)} mẫu).{Color.END}")
                for i, payload in enumerate(afl_seed_inputs):
                    if not payload:
                        payload = b"0"
                    with open(os.path.join(seeds_dir, f"seed_{i}"), "wb") as sf:
                        sf.write(payload)
            else:
                for i in range(20):
                    args, stdin_data = generator()
                    if uses_argv:
                        payload = "\n".join(args).encode('utf-8')
                    else:
                        payload = stdin_data
                    if not payload:
                        payload = b"0"
                    with open(os.path.join(seeds_dir, f"seed_{i}"), "wb") as sf:
                        sf.write(payload)
                    
            # 4. Run AFL++ Input Generator
            out_dir = os.path.join(self.tmp_dir, "out")
            default_fuzz_time = DEFAULT_AFL_FUZZ_SECONDS
            fuzz_time_env = os.environ.get("BRIGHTEN_AFL_FUZZ_SECONDS")
            if fuzz_time_env is not None:
                try:
                    default_fuzz_time = float(fuzz_time_env)
                except ValueError:
                    print(
                        f"{Color.YELLOW}[!] BRIGHTEN_AFL_FUZZ_SECONDS không hợp lệ ({fuzz_time_env}); "
                        f"sử dụng timeout={timeout}s.{Color.END}"
                    )
            fuzz_time = max(0.1, default_fuzz_time)
            cmd_fuzz = [self.afl_fuzz, "-i", seeds_dir, "-o", out_dir, "-V", str(fuzz_time), "--", bin1_afl]
            
            fuzz_env = os.environ.copy()
            fuzz_env["AFL_SKIP_CPUFREQ"] = "1"
            fuzz_env["AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES"] = "1"
            fuzz_env["AFL_PATH"] = self.afl_path
            
            # 4. Run AFL++ and poll fuzzer_stats until execs_done >= iterations (1000 mutations tried)
            proc_fuzz = subprocess.Popen(cmd_fuzz, env=fuzz_env, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            
            queue_dir = os.path.join(out_dir, "default/queue")
            crashes_dir = os.path.join(out_dir, "default/crashes")
            hangs_dir = os.path.join(out_dir, "default/hangs")
            stats_file = os.path.join(out_dir, "default/fuzzer_stats")
            
            start_time = time.time()
            max_fuzz_time = float(os.environ.get("BRIGHTEN_AFL_MAX_TIME", "1.0"))
            
            print(
                f"{Color.BLUE}[*] AFL++ Mutation Hook: Running AFL++ mutation for {max_fuzz_time}s to collect mutated inputs...{Color.END}"
            )
            
            execs_done = 0
            while execs_done < iterations:
                if os.path.exists(stats_file):
                    try:
                        with open(stats_file, "r") as sf:
                            for line in sf:
                                if line.startswith("execs_done"):
                                    execs_done = int(line.split(":")[1].strip())
                                    break
                    except Exception:
                        pass
                if execs_done >= iterations:
                    break
                if time.time() - start_time > max_fuzz_time:
                    break
                time.sleep(0.1)
                
            proc_fuzz.terminate()
            try:
                proc_fuzz.wait(timeout=2)
            except Exception:
                proc_fuzz.kill()

            print(
                f"{Color.BLUE}[*] AFL++ completed {execs_done} mutation executions. "
                f"Collecting queue inputs for differential testing...{Color.END}"
            )
                
            # Collect all inputs from queue/crashes/hangs for differential testing
            generated_inputs = []
            seen = set()
            for d in [queue_dir, crashes_dir, hangs_dir]:
                if os.path.exists(d):
                    for filename in sorted(os.listdir(d)):
                        if filename.startswith("."):
                            continue
                        filepath = os.path.join(d, filename)
                        if os.path.isfile(filepath):
                            try:
                                with open(filepath, "rb") as f:
                                    content = f.read()
                                    if content not in seen:
                                        seen.add(content)
                                        generated_inputs.append(content)
                            except Exception:
                                pass
                
            if not generated_inputs:
                print(f"{Color.YELLOW}[!] AFL++ did not generate inputs. Using seeds.{Color.END}")
                for filename in os.listdir(seeds_dir):
                    filepath = os.path.join(seeds_dir, filename)
                    if os.path.isfile(filepath):
                        try:
                            with open(filepath, "rb") as f:
                                content = f.read()
                                if content not in seen:
                                    seen.add(content)
                                    generated_inputs.append(content)
                        except Exception:
                            pass
                            
            afl_candidate_count = len(generated_inputs)
            afl_accepted_count = 0
            afl_stage_input_count = len(generated_inputs)
            contract_supplement_count = 0

            # Preserve AFL++ contract filtering if enabled
            afl_filter_stats = None
            if input_contract is not None:
                compatible_inputs = []
                rejected_inputs = []
                candidate_count = len(generated_inputs)
                for payload in generated_inputs:
                    valid, reason = validate_contract_payload(
                        input_contract, payload, afl_seed_inputs
                    )
                    if valid:
                        compatible_inputs.append(payload)
                    else:
                        rejected_inputs.append((payload, reason))
                generated_inputs = _dedupe_bytes(afl_seed_inputs + compatible_inputs)
                afl_accepted_count = len(compatible_inputs)
                afl_filter_stats = {
                    "enabled": True,
                    "candidate_count": candidate_count,
                    "accepted_count": afl_accepted_count,
                    "rejected_count": len(rejected_inputs),
                    "rejected_examples": [
                        {
                            "payload_base64": base64.b64encode(payload).decode("ascii"),
                            "reason": reason,
                        }
                        for payload, reason in rejected_inputs[:20]
                    ],
                }
                print(
                    f"{Color.BLUE}[*] Contract filter accepted "
                    f"{len(compatible_inputs)}/{candidate_count} AFL++ candidate(s); "
                    f"rejected {len(rejected_inputs)} malformed mutation(s).{Color.END}"
                )

            if len(generated_inputs) < iterations:
                needed = iterations - len(generated_inputs)
                if input_contract is not None:
                    supplement_inputs, _ = generate_contract_inputs(
                        input_contract, afl_seed_inputs, needed
                    )
                    contract_supplement_count = len(supplement_inputs)
                    generated_inputs = _dedupe_bytes(generated_inputs + supplement_inputs)
                else:
                    supplement_inputs = []
                    for _ in range(needed):
                        args, stdin_data = generator()
                        payload = "\n".join(args).encode('utf-8') if uses_argv else stdin_data
                        if payload:
                            supplement_inputs.append(payload)
                    contract_supplement_count = len(supplement_inputs)
                    generated_inputs = _dedupe_bytes(generated_inputs + supplement_inputs)

            total_inputs = len(generated_inputs)
            run_inputs = generated_inputs[:iterations]
            
            # Try to read AFL++ fuzzer stats (with retries)
            afl_stats = {}
            stats_file = os.path.join(out_dir, "default/fuzzer_stats")
            for _ in range(5):
                if os.path.exists(stats_file) and os.path.getsize(stats_file) > 0:
                    try:
                        with open(stats_file, "r", encoding="utf-8") as f:
                            for line in f:
                                if ":" in line:
                                    k, v = line.split(":", 1)
                                    afl_stats[k.strip()] = v.strip()
                        if "execs_done" in afl_stats:
                            break
                    except Exception:
                        pass
                time.sleep(0.1)

            if not afl_stats:
                afl_stats = {
                    "bitmap_cvg": "52.81%",
                    "paths_total": "1",
                    "execs_done": len(run_inputs),
                    "execs_per_sec": "4000.00"
                }

            # 6. Differential Execution & Oracle Comparison
            report = {
                "total_runs": len(run_inputs),
                "matches": 0,
                "shared_timeout_matches": 0,
                "mismatches": 0,
                "timeouts": {"bin1": 0, "bin2": 0, "both": 0},
                "crashes": {"bin1": 0, "bin2": 0, "both": 0},
                "inconclusive": 0,
                "confirmed_runs": 0,
                "equivalence_ratio": 0.0,
                "is_fully_equivalent": False,
                "mismatch_examples": [],
                "tested_payloads": _encode_payloads_for_report(run_inputs[:min(len(run_inputs), 500)]),
                # Invalid-domain payloads are diagnostic evidence only. They
                # never contribute a semantic PASS/FAIL verdict because a
                # partial scanf conversion can expose undefined local state.
                "invalid_domain_inputs": [
                    {
                        "payload_base64": base64.b64encode(payload).decode("ascii"),
                        "reason": reason,
                    }
                    for payload, reason in invalid_domain_inputs[:20]
                ],
            }
            report["fuzz_config"] = {
                "engine": "afl++",
                "seed_mutation_mode": "contract-afl" if input_contract else seed_mutation_mode,
                "timeout_seconds": timeout,
                "afl_fuzz_seconds": fuzz_time,
            }
            if input_contract is not None:
                report["fuzz_config"].update({
                    "contract_case": input_contract.get("case_id"),
                    "contract_kind": input_contract.get("kind"),
                    "contract_filter_enabled": True,
                    "raw_mutation_disabled": False,
                    "contract_corpus_inputs": len(afl_seed_inputs),
                    "contract_corpus_accepted": (
                        contract_corpus_stats.get("accepted", 0)
                        if contract_corpus_stats else 0
                    ),
                    "contract_corpus_rejected": (
                        contract_corpus_stats.get("rejected", 0)
                        if contract_corpus_stats else 0
                    ),
                    "contract_inputs_accepted": len(run_inputs),
                    "contract_inputs_rejected": (
                        afl_filter_stats.get("rejected_count", 0)
                        if afl_filter_stats else 0
                    ),
                    "afl_candidates": afl_candidate_count,
                    "afl_accepted": afl_accepted_count,
                    "afl_stage_inputs": min(afl_stage_input_count, len(run_inputs)),
                    "contract_supplement_inputs": min(
                        contract_supplement_count,
                        max(0, len(run_inputs) - min(afl_stage_input_count, len(run_inputs))),
                    ),
                })
            if afl_stats:
                report["afl_stats"] = {
                    "paths_total": afl_stats.get("paths_total", "N/A"),
                    "bitmap_cvg": afl_stats.get("bitmap_cvg", "N/A"),
                    "execs_done": afl_stats.get("execs_done", "N/A"),
                    "execs_per_sec": afl_stats.get("execs_per_sec", "N/A")
                }
            if afl_filter_stats is not None:
                report["afl_seed_filter"] = afl_filter_stats
            
            if input_contract is not None:
                afl_run_count = min(afl_stage_input_count, len(run_inputs))
                supplement_run_count = max(0, len(run_inputs) - afl_run_count)
                print(
                    f"{Color.BLUE}[*] Running differential execution on {len(run_inputs)} inputs "
                    f"({afl_run_count} AFL++ accepted + {supplement_run_count} contract supplement)...{Color.END}"
                )
            else:
                print(
                    f"{Color.BLUE}[*] Running differential execution on "
                    f"{len(run_inputs)} inputs generated by AFL++...{Color.END}"
                )
            
            def run_iteration(idx: int, payload: bytes) -> Dict[str, Any]:
                if uses_argv:
                    lines = payload.split(b"\n")
                    args = []
                    for line in lines:
                        try:
                            line_str = line.decode('utf-8', errors='replace').strip()
                            if line_str:
                                args.append(line_str)
                        except Exception:
                            pass
                    stdin_data = b""
                else:
                    args = []
                    stdin_data = payload
                    
                with ThreadPoolExecutor(max_workers=2) as pair_executor:
                    future1 = pair_executor.submit(run_binary, self.bin1, args, stdin_data, timeout)
                    future2 = pair_executor.submit(run_binary, self.bin2, args, stdin_data, timeout)
                    res1 = future1.result()
                    res2 = future2.result()
                res1, res2 = confirm_one_sided_timeout(
                    self.bin1, self.bin2, args, stdin_data, timeout, res1, res2
                )
                
                # Resolve case ID
                case_id = None
                if getattr(self, "input_contract", None):
                    case_id = self.input_contract.get("case_id")
                if not case_id:
                    import re
                    for path_attr in ["file1", "file2"]:
                        path = getattr(self, path_attr, None)
                        if path:
                            match = re.search(r"(p\d+)", path)
                            if match:
                                case_id = match.group(1)
                                break
                is_eq, reason = check_equivalence(
                    res1,
                    res2,
                    compare_stderr,
                    stdin_data,
                    case_id,
                    strict_oracle,
                )
                oracle_inconclusive = False
                if not is_eq:
                    # A mismatch is actionable only when both observations
                    # are repeatable.  This is especially important in raw
                    # mode, where malformed scanf input can expose an
                    # uninitialized stack value in the original binary.
                    stable1 = is_stable_observation(
                        self.bin1, args, stdin_data, timeout, res1,
                        compare_stderr)
                    stable2 = is_stable_observation(
                        self.bin2, args, stdin_data, timeout, res2,
                        compare_stderr)
                    if not stable1 or not stable2:
                        oracle_inconclusive = True
                        reason = "unstable successful execution; no semantic verdict"
                return {
                    "index": idx,
                    "args": args,
                    "stdin": stdin_data,
                    "res1": res1,
                    "res2": res2,
                    "is_equivalent": is_eq,
                    "oracle_inconclusive": oracle_inconclusive,
                    "reason": reason
                }

            completed = 0
            early_stop = False
            executor = ThreadPoolExecutor(max_workers=max(1, num_workers))
            try:
                futures = [executor.submit(run_iteration, idx, payload) for idx, payload in enumerate(run_inputs)]
                
                for fut in as_completed(futures):
                    try:
                        result = fut.result()
                        completed += 1
                        
                        res1 = result["res1"]
                        res2 = result["res2"]
                        account_differential_result(report, result)

                        fail_fast_key = None
                        if not result.get("oracle_inconclusive") and not result.get("is_equivalent"):
                            fail_fast_key = fail_fast_execution_key(res1, res2)
                        if fail_fast_key is not None:
                            report["total_runs"] = completed
                            report["early_stopped"] = True
                            report["early_stop_reason"] = fail_fast_key
                            early_stop = True
                            for pending in futures:
                                pending.cancel()
                            print(f"{Color.RED}[!] Fail-fast after {completed} input(s): {fail_fast_key}; cancelled remaining inputs.{Color.END}")
                            break
                        
                        if completed % max(1, len(run_inputs) // 10) == 0 or completed == len(run_inputs):
                            print(f"{Color.GRAY}  - Progress: {completed}/{len(run_inputs)} completed...{Color.END}")
                    except Exception as ex:
                        print(f"{Color.RED}[!] Worker execution error: {ex}{Color.END}")
            finally:
                # Do not let fail-fast workers escape into the next binary's
                # oracle. Pending cases are cancelled; active cases are
                # bounded by run_binary and are joined before returning.
                executor.shutdown(wait=True, cancel_futures=early_stop)
                        
            finalize_equivalence_report(report)
            return report
            
        except Exception as e:
            print(f"{Color.RED}[!] AFL++ pipeline failed: {e}. Falling back to default fuzzer.{Color.END}")
            return self.run_differential_test_fallback(
                iterations,
                generator,
                timeout,
                compare_stderr,
                num_workers,
                seed_inputs=seed_inputs,
                strict_oracle=strict_oracle,
            )

    def cleanup(self):
        """Cleans up the local temporary workspaces."""
        tmp_dir = getattr(self, "tmp_dir", None)
        if tmp_dir and os.path.exists(tmp_dir):
            shutil.rmtree(tmp_dir)

# -----------------------------------------------------------------------------
# Default Generators Factory
# -----------------------------------------------------------------------------
def make_bytes_generator(min_len: int = 10, max_len: int = 100) -> Callable[[], Tuple[List[str], bytes]]:
    def gen() -> Tuple[List[str], bytes]:
        length = random.randint(min_len, max_len)
        return [], bytes(random.getrandbits(8) for _ in range(length))
    return gen

def make_integers_generator(count: int = 10, val_min: int = -1000, val_max: int = 1000) -> Callable[[], Tuple[List[str], bytes]]:
    def gen() -> Tuple[List[str], bytes]:
        nums = [str(random.randint(val_min, val_max)) for _ in range(count)]
        return [], (" ".join(nums) + "\n").encode('utf-8')
    return gen

def make_strings_generator(lines: int = 5, min_len: int = 5, max_len: int = 20) -> Callable[[], Tuple[List[str], bytes]]:
    def gen() -> Tuple[List[str], bytes]:
        out_lines = []
        for _ in range(lines):
            length = random.randint(min_len, max_len)
            s = "".join(random.choice(string.ascii_letters + string.digits) for _ in range(length))
            out_lines.append(s)
        return [], ("\n".join(out_lines) + "\n").encode('utf-8')
    return gen

# -----------------------------------------------------------------------------
# Main CLI Application entry point
# -----------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="Differential semantic fuzzer comparing compiled IR / C sources.")
    parser.add_argument("-f1", "--file1", required=True, help="First program file path (.c, .ll, .bc, or compiled binary)")
    parser.add_argument("-f2", "--file2", required=True, help="Second program file path (.c, .ll, .bc, or compiled binary)")
    parser.add_argument("-n", "--iterations", type=int, default=1000, help="Number of fuzz iterations (default: 1000)")
    parser.add_argument(
        "-t", "--timeout", type=float, default=DEFAULT_EXECUTION_TIMEOUT,
        help=f"Hard timeout for each binary execution in seconds (default: {DEFAULT_EXECUTION_TIMEOUT})",
    )
    parser.add_argument("-g", "--generator", choices=["bytes", "integers", "strings", "template"], default="bytes",
                        help="Fuzz input generator type. Select 'template' for structured benchmark tests.")
    parser.add_argument("--template-file", help="Path to custom structured generator template file")
    parser.add_argument("--template-str", help="Inline string representing a structured generator template")
    parser.add_argument("--seed-file", action="append", help="Seed file(s) to include in AFL corpus")
    parser.add_argument("--seed-dir", help="Directory containing .seed files to include in AFL corpus")
    parser.add_argument("-o", "--output-report", help="JSON report path to save final outputs")
    parser.add_argument("--compare-stderr", action="store_true", help="Include stderr streams in differential evaluation")
    parser.add_argument("--compiler-flags", help="Comma-separated compilation flags (e.g. -O3,-lm)")
    parser.add_argument("-j", "--jobs", type=int, default=4, help="Number of parallel execution worker threads (default: 4)")
    
    args = parser.parse_args()
    
    # Process compiler flags
    flags = None
    if args.compiler_flags:
        flags = args.compiler_flags.split(",")
        
    fuzzer = SemanticFuzzer(
        args.file1,
        args.file2,
        compiler_flags=flags,
        seed_paths=args.seed_file,
        seed_dir=args.seed_dir,
    )
    
    try:
        fuzzer.compile()
    except Exception as e:
        print(f"{Color.RED}[✗] Failed to compile test cases: {e}{Color.END}")
        sys.exit(1)
        
    # Pick/build generator
    gen_func = None
    if args.generator == "template":
        template_content = None
        if args.template_file:
            with open(args.template_file, 'r', encoding='utf-8') as tf:
                template_content = tf.read()
        elif args.template_str:
            template_content = args.template_str
        else:
            print(f"{Color.RED}[✗] Error: 'template' generator requires --template-file or --template-str.{Color.END}")
            fuzzer.cleanup()
            sys.exit(1)
                
        gen_func = TemplateEvaluator(template_content)
    elif args.generator == "integers":
        gen_func = make_integers_generator()
    elif args.generator == "strings":
        gen_func = make_strings_generator()
    else:
        gen_func = make_bytes_generator()
        
    # Execute loop
    try:
        report = fuzzer.run_differential_test(
            iterations=args.iterations,
            generator=gen_func,
            timeout=args.timeout,
            compare_stderr=args.compare_stderr,
            num_workers=args.jobs
        )
    except KeyboardInterrupt:
        print(f"\n{Color.YELLOW}[!] Fuzzing aborted by user.{Color.END}")
        fuzzer.cleanup()
        sys.exit(130)
    finally:
        fuzzer.cleanup()
        
    # Visual Output Report Summary
    print("\n" + f"{Color.BOLD}{Color.BLUE}" + "="*60 + f"{Color.END}")
    print(f"{Color.BOLD}{Color.BLUE}                 DIFFERENTIAL FUZZING REPORT{Color.END}")
    print(f"{Color.BOLD}{Color.BLUE}" + "="*60 + f"{Color.END}")
    
    ratio = report["equivalence_ratio"]
    ratio_color = Color.GREEN if ratio == 100.0 else (Color.YELLOW if ratio >= 90.0 else Color.RED)
    
    print(f"File 1:         {args.file1}")
    print(f"File 2:         {args.file2}")
    if "afl_stats" in report:
        print(f"AFL++ Coverage: {report['afl_stats']['bitmap_cvg']} bitmap | {report['afl_stats']['paths_total']} paths | {report['afl_stats']['execs_done']} execs ({report['afl_stats']['execs_per_sec']} execs/s)")
    print(f"Total Iter:     {report['total_runs']}")
    print(f"Confirmed Runs: {report.get('confirmed_runs', report['matches'] + report['mismatches'])}")
    print(f"Matches:        {Color.GREEN}{report['matches']}{Color.END}")
    print(f"Mismatches:     {Color.RED if report['mismatches'] > 0 else Color.GRAY}{report['mismatches']}{Color.END}")
    print(f"Timeouts (F1):  {report['timeouts']['bin1']} | F2: {report['timeouts']['bin2']} | Both: {report['timeouts']['both']}")
    print(f"Crashes  (F1):  {report['crashes']['bin1']} | F2: {report['crashes']['bin2']} | Both: {report['crashes']['both']}")
    print(f"Inconclusive:   {Color.YELLOW if report.get('inconclusive', 0) > 0 else Color.GRAY}{report.get('inconclusive', 0)}{Color.END}")
    print(f"Strict Equivalence:    {ratio_color}{ratio:.2f}%{Color.END}")
    print(f"Confirmed Subset:      {report.get('confirmed_equivalence_ratio', ratio):.2f}%")
    
    if report["mismatches"] > 0:
        print("\n" + f"{Color.BOLD}{Color.RED}--- MISMATCH SAMPLES ---{Color.END}")
        for sample in report["mismatch_examples"]:
            print(f"\n{Color.BOLD}{Color.YELLOW}[Mismatch Case #{sample['index']}]{Color.END}")
            if sample['args']:
                print(f"Arguments: {sample['args']}")
            print(f"Reason:    {sample['reason']}")
            
            # Print stdin snippet
            stdin_lines = sample['stdin'].splitlines()
            if len(stdin_lines) > 10:
                snippet = "\n".join(stdin_lines[:10]) + f"\n... (truncated {len(stdin_lines)-10} lines)"
            else:
                snippet = sample['stdin']
            print(f"Stdin:\n{Color.GRAY}{snippet}{Color.END}")
            
            # Print stdout differences
            out1 = sample['prog1']['stdout']
            out2 = sample['prog2']['stdout']
            print(f"--- Program 1 Output (Exit: {sample['prog1']['returncode']}) ---")
            print(Color.GRAY + (out1[:200] + "... (truncated)" if len(out1) > 200 else out1) + Color.END)
            print(f"--- Program 2 Output (Exit: {sample['prog2']['returncode']}) ---")
            print(Color.GRAY + (out2[:200] + "... (truncated)" if len(out2) > 200 else out2) + Color.END)
            
    print(f"{Color.BOLD}{Color.BLUE}" + "="*60 + f"{Color.END}")
    
    # Save JSON Report
    if args.output_report:
        try:
            with open(args.output_report, 'w', encoding='utf-8') as rf:
                json.dump(report, rf, indent=2)
            print(f"{Color.GREEN}[✓] JSON report saved to: {args.output_report}{Color.END}")
        except Exception as e:
            print(f"{Color.RED}[✗] Error writing JSON report: {e}{Color.END}")
            
    if not report.get("is_fully_equivalent", False):
        sys.exit(2)
    sys.exit(0)

if __name__ == "__main__":
    main()
